//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UmamusumeResponseAnalyzer.Localization {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Config {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Config() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UmamusumeResponseAnalyzer.Localization.Config", typeof(Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 Invalid configuration file &quot;{0}&quot;, field {1}: {2}. 的本地化字符串。
        /// </summary>
        internal static string InvalidField {
            get {
                return ResourceManager.GetString("InvalidField", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 must not contain null content 的本地化字符串。
        /// </summary>
        internal static string InvalidNullContent {
            get {
                return ResourceManager.GetString("InvalidNullContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 must not be null 的本地化字符串。
        /// </summary>
        internal static string InvalidNullValue {
            get {
                return ResourceManager.GetString("InvalidNullValue", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Configuration file &quot;{0}&quot; does not match the current schema ({1}:{2}): {3} 的本地化字符串。
        /// </summary>
        internal static string InvalidSchema {
            get {
                return ResourceManager.GetString("InvalidSchema", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cannot assign null to {0}. 的本地化字符串。
        /// </summary>
        internal static string NullAssignment {
            get {
                return ResourceManager.GetString("NullAssignment", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Cannot open settings because the plugin was unloaded: {0} 的本地化字符串。
        /// </summary>
        internal static string PluginUnloaded {
            get {
                return ResourceManager.GetString("PluginUnloaded", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Return 的本地化字符串。
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Listen address 的本地化字符串。
        /// </summary>
        internal static string Tabs_Core_ListenAddress {
            get {
                return ResourceManager.GetString("Tabs_Core_ListenAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Enter the listen address (default: 127.0.0.1; 0.0.0.0 with administrator privileges) 的本地化字符串。
        /// </summary>
        internal static string Tabs_Core_ListenAddressPrompt {
            get {
                return ResourceManager.GetString("Tabs_Core_ListenAddressPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Listen port 的本地化字符串。
        /// </summary>
        internal static string Tabs_Core_ListenPort {
            get {
                return ResourceManager.GetString("Tabs_Core_ListenPort", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Enter the listen port (default: 4693) 的本地化字符串。
        /// </summary>
        internal static string Tabs_Core_ListenPortPrompt {
            get {
                return ResourceManager.GetString("Tabs_Core_ListenPortPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Show initial setup 的本地化字符串。
        /// </summary>
        internal static string Tabs_Core_ShowFirstRunPrompt {
            get {
                return ResourceManager.GetString("Tabs_Core_ShowFirstRunPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Core 的本地化字符串。
        /// </summary>
        internal static string Tabs_Core_Title {
            get {
                return ResourceManager.GetString("Tabs_Core_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Save communication files 的本地化字符串。
        /// </summary>
        internal static string Tabs_Debug_SaveResponseForDebug {
            get {
                return ResourceManager.GetString("Tabs_Debug_SaveResponseForDebug", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        internal static string Tabs_Debug_Title {
            get {
                return ResourceManager.GetString("Tabs_Debug_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Auto-detect 的本地化字符串。
        /// </summary>
        internal static string Tabs_Language_AutoDetect {
            get {
                return ResourceManager.GetString("Tabs_Language_AutoDetect", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string Tabs_Language_English {
            get {
                return ResourceManager.GetString("Tabs_Language_English", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 日本語 的本地化字符串。
        /// </summary>
        internal static string Tabs_Language_Japanese {
            get {
                return ResourceManager.GetString("Tabs_Language_Japanese", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        internal static string Tabs_Language_SimplifiedChinese {
            get {
                return ResourceManager.GetString("Tabs_Language_SimplifiedChinese", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Tabs_Language_Title {
            get {
                return ResourceManager.GetString("Tabs_Language_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Enter the localization file path 的本地化字符串。
        /// </summary>
        internal static string Tabs_Localization_InputPath {
            get {
                return ResourceManager.GetString("Tabs_Localization_InputPath", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Localization file path 的本地化字符串。
        /// </summary>
        internal static string Tabs_Localization_Path {
            get {
                return ResourceManager.GetString("Tabs_Localization_Path", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Localization 的本地化字符串。
        /// </summary>
        internal static string Tabs_Localization_Title {
            get {
                return ResourceManager.GetString("Tabs_Localization_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Miscellaneous 的本地化字符串。
        /// </summary>
        internal static string Tabs_Misc_Title {
            get {
                return ResourceManager.GetString("Tabs_Misc_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 AI 的本地化字符串。
        /// </summary>
        internal static string Tabs_Misc_WriteAIInfo {
            get {
                return ResourceManager.GetString("Tabs_Misc_WriteAIInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Plugins 的本地化字符串。
        /// </summary>
        internal static string Tabs_Plugin_Title {
            get {
                return ResourceManager.GetString("Tabs_Plugin_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Custom database repository 的本地化字符串。
        /// </summary>
        internal static string Tabs_Updater_CustomDatabaseRepository {
            get {
                return ResourceManager.GetString("Tabs_Updater_CustomDatabaseRepository", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Enter the custom database repository URL:  的本地化字符串。
        /// </summary>
        internal static string Tabs_Updater_CustomDatabaseRepositoryPrompt {
            get {
                return ResourceManager.GetString("Tabs_Updater_CustomDatabaseRepositoryPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Data language 的本地化字符串。
        /// </summary>
        internal static string Tabs_Updater_DatabaseLanguage {
            get {
                return ResourceManager.GetString("Tabs_Updater_DatabaseLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Force updates through GitHub 的本地化字符串。
        /// </summary>
        internal static string Tabs_Updater_ForceUseGithubToUpdate {
            get {
                return ResourceManager.GetString("Tabs_Updater_ForceUseGithubToUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string Tabs_Updater_Title {
            get {
                return ResourceManager.GetString("Tabs_Updater_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Male trainer 的本地化字符串。
        /// </summary>
        internal static string Tabs_Updater_TrainerIsMale {
            get {
                return ResourceManager.GetString("Tabs_Updater_TrainerIsMale", resourceCulture);
            }
        }
    }
}
