// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<AccountDeletionRequestRequest>))]
public class AccountDeletionRequestRequest : RequestBase<AccountDeletionRequestResponse>
{
}
