// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<AccountChainDisconnectResponse>))]
public class AccountChainDisconnectResponse : ResponseCommon
{
    [Key("data")] public AccountChainDisconnectResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<AccountChainDisconnectResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
