// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<AddMatchPointData>))]
public class AddMatchPointData
{
    [Key("add_match_point_total")] public int add_match_point_total; // 0x10
    [Key("add_match_point_base")] public int add_match_point_base; // 0x14
    [Key("add_match_point_match_bonus_skill")] public int add_match_point_match_bonus_skill; // 0x18
    [Key("point_detail_array")] public ChallengeMatchResultPoint[] point_detail_array; // 0x20
}
