// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<AppAnnounce>))]
public class AppAnnounce
{
    [Key("app_announce_id")] public int app_announce_id; // 0x10
    [Key("message")] public string message; // 0x18
    [Key("begin_date")] public string begin_date; // 0x20
    [Key("end_date")] public string end_date; // 0x28
    [Key("announce2_date")] public string announce2_date; // 0x30
    [Key("announce3_date")] public string announce3_date; // 0x38
    [Key("announce4_date")] public string announce4_date; // 0x40
}
