// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ArcRivalPotential>))]
public class ArcRivalPotential
{
    [Key("potential_id")] public int potential_id; // 0x10
    [Key("level")] public int level; // 0x14
}
