// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<BadConditionGuardInfo>))]
public class BadConditionGuardInfo
{
    [Key("chara_effect_id")] public int chara_effect_id; // 0x10
    [Key("target_chara_effect_id")] public int target_chara_effect_id; // 0x14
}
