// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CallPaymentStartDummyRequest>))]
public class CallPaymentStartDummyRequest : RequestBase<CallPaymentStartDummyResponse>
{
    [Key("payment")] public PaymentStartParam payment; // 0x88
    [Key("isalertagree")] public int isalertagree; // 0x90
    [Key("isalertactive")] public int isalertactive; // 0x94
}
