// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CallPaymentStartDummyResponse>))]
public class CallPaymentStartDummyResponse : ResponseCommon
{
    [Key("data")] public CallPaymentStartDummyResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CallPaymentStartDummyResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("dmm_point_balance")] public int dmm_point_balance; // 0x10
        [Key("is_refund_caution")] public int is_refund_caution; // 0x14
    }
}
