// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CardUnlockRequest>))]
public class CardUnlockRequest : RequestBase<CardUnlockResponse>
{
    [Key("card_id")] public int card_id; // 0x88
}
