// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CardTalentStrengthenRequest>))]
public class CardTalentStrengthenRequest : RequestBase<CardTalentStrengthenResponse>
{
    [Key("card_id")] public int card_id; // 0x88
    [Key("talent_level")] public int talent_level; // 0x8C
    [Key("new_talent_level")] public int new_talent_level; // 0x90
}
