// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CardSellPieceRequest>))]
public class CardSellPieceRequest : RequestBase<CardSellPieceResponse>
{
    [Key("sell_piece_data_array")] public PieceData[] sell_piece_data_array; // 0x88
}
