// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CardGetReleaseCardResponse>))]
public class CardGetReleaseCardResponse : ResponseCommon
{
    [Key("data")] public CardGetReleaseCardResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CardGetReleaseCardResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("release_card_array")] public int[] release_card_array; // 0x10
    }
}
