// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CardRarityUpgradeRequest>))]
public class CardRarityUpgradeRequest : RequestBase<CardRarityUpgradeResponse>
{
    [Key("card_id")] public int card_id; // 0x88
    [Key("new_rarity")] public int new_rarity; // 0x8C
    [Key("now_rarity")] public int now_rarity; // 0x90
}
