// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChallengeMatchReflectItemEffectRequest>))]
public class ChallengeMatchReflectItemEffectRequest : RequestBase<ChallengeMatchReflectItemEffectResponse>
{
    [Key("challenge_match_race_id")] public int challenge_match_race_id; // 0x88
    [Key("item_id_array")] public int[] item_id_array; // 0x90
}
