// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChallengeMatchRaceEndResponse>))]
public class ChallengeMatchRaceEndResponse : ResponseCommon
{
    [Key("data")] public ChallengeMatchRaceEndResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ChallengeMatchRaceEndResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("rank")] public int rank; // 0x10
        [Key("match_point")] public int match_point; // 0x14
        [Key("add_match_point_array")] public AddMatchPointData add_match_point_array; // 0x18
        [Key("first_clear_reward_array")] public RaceRewardData[] first_clear_reward_array; // 0x20
        [Key("drop_reward_array")] public RaceRewardData[] drop_reward_array; // 0x28
        [Key("victory_reward_array")] public RaceRewardData[] victory_reward_array; // 0x30
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x38
        [Key("trained_chara_id")] public int trained_chara_id; // 0x40
        [Key("trained_chara_array")] public TrainedChara[] trained_chara_array; // 0x48
        [Key("state")] public int state; // 0x50
        [Key("mission_badge_num")] public int mission_badge_num; // 0x54
    }
}
