// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChallengeMatchRaceRewardLimit>))]
public class ChallengeMatchRaceRewardLimit
{
    [Key("item_category")] public int item_category; // 0x10
    [Key("item_id")] public int item_id; // 0x14
    [Key("item_num")] public int item_num; // 0x18
    [Key("current_count")] public int current_count; // 0x1C
    [Key("limit_count")] public int limit_count; // 0x20
}
