// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChallengeMatchRaceOpenResponse>))]
public class ChallengeMatchRaceOpenResponse : ResponseCommon
{
    [Key("data")] public ChallengeMatchRaceOpenResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ChallengeMatchRaceOpenResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("challenge_match_race_id")] public int challenge_match_race_id; // 0x10
        [Key("end_date")] public string end_date; // 0x18
        [Key("challenge_race_extreme_count")] public int challenge_race_extreme_count; // 0x20
    }
}
