// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsPaddockIndexRequest>))]
public class ChampionsPaddockIndexRequest : RequestBase<ChampionsPaddockIndexResponse>
{
    [Key("race_num")] public int race_num; // 0x88
}
