// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsStampSendStampRequest>))]
public class ChampionsStampSendStampRequest : RequestBase<ChampionsStampSendStampResponse>
{
    [Key("race_num")] public int race_num; // 0x88
    [Key("term_id")] public int term_id; // 0x8C
    [Key("stamp_id")] public int stamp_id; // 0x90
}
