// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsRankingEntryCharaInfo>))]
public class ChampionsRankingEntryCharaInfo
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("trained_chara_id")] public int trained_chara_id; // 0x18
    [Key("team_member_id")] public int team_member_id; // 0x1C
    [Key("card_id")] public int card_id; // 0x20
    [Key("final_grade")] public int final_grade; // 0x24
    [Key("rarity")] public int rarity; // 0x28
    [Key("talent_level")] public int talent_level; // 0x2C
    [Key("race_cloth_id")] public int race_cloth_id; // 0x30
    [Key("running_style")] public int running_style; // 0x34
}
