// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsUserCharaTop>))]
public class ChampionsUserCharaTop
{
    [Key("card_id")] public int card_id; // 0x10
    [Key("chara_id")] public int chara_id; // 0x14
    [Key("race_cloth_id")] public int race_cloth_id; // 0x18
    [Key("nick_name_id")] public int nick_name_id; // 0x1C
    [Key("team_member_id")] public int team_member_id; // 0x20
}
