// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsPaddockIndexResponse>))]
public class ChampionsPaddockIndexResponse : ResponseCommon
{
    [Key("data")] public ChampionsPaddockIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsPaddockIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("news_title_id")] public int news_title_id; // 0x10
    }
}
