// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsSelectLeagueRequest>))]
public class ChampionsSelectLeagueRequest : RequestBase<ChampionsSelectLeagueResponse>
{
    [Key("league_type")] public int league_type; // 0x88
}
