// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsCancelRequest>))]
public class ChampionsCancelRequest : RequestBase<ChampionsCancelResponse>
{
    [Key("room_id_array")] public long[] room_id_array; // 0x88
}
