// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsRoundEndRequest>))]
public class ChampionsRoundEndRequest : RequestBase<ChampionsRoundEndResponse>
{
    [Key("is_present")] public int is_present; // 0x88
}
