// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsRankingUserInfo>))]
public class ChampionsRankingUserInfo
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("name")] public string name; // 0x18
    [Key("honor_data")] public HonorData honor_data; // 0x20
    [Key("leader_chara_id")] public int leader_chara_id; // 0x28
    [Key("leader_chara_dress_id")] public int leader_chara_dress_id; // 0x2C
}
