// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsGetNewsInfoResponse>))]
public class ChampionsGetNewsInfoResponse : ResponseCommon
{
    [Key("data")] public ChampionsGetNewsInfoResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsGetNewsInfoResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("news_race_id_array")] public int[] news_race_id_array; // 0x10
        [Key("news_trainer_info")] public ChampionsNewsTrainerInfo news_trainer_info; // 0x18
        [Key("news_chara_info_array")] public ChampionsNewsCharaInfo[] news_chara_info_array; // 0x20
        [Key("news_chara_result_info_array")] public ChampionsNewsCharaResultInfo[] news_chara_result_info_array; // 0x28
    }
}
