// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsCancelResponse>))]
public class ChampionsCancelResponse : ResponseCommon
{
    [Key("data")] public ChampionsCancelResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsCancelResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("is_success")] public int is_success; // 0x10
    }
}
