// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsFinalRaceEndRequest>))]
public class ChampionsFinalRaceEndRequest : RequestBase<ChampionsFinalRaceEndResponse>
{
}
