// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsCharaResult>))]
public class ChampionsCharaResult
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("team_member_id")] public int team_member_id; // 0x18
    [Key("rank")] public int rank; // 0x1C
}
