// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsStampPollResponse>))]
public class ChampionsStampPollResponse : ResponseCommon
{
    [Key("data")] public ChampionsStampPollResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsStampPollResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("stamp_array")] public ChampionsStampInfo[] stamp_array; // 0x10
    }
}
