// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsRewardInfo>))]
public class ChampionsRewardInfo
{
    [Key("league_type")] public int league_type; // 0x10
    [Key("round_id")] public int round_id; // 0x14
    [Key("win_count")] public int win_count; // 0x18
    [Key("ranking")] public int ranking; // 0x1C
    [Key("item_array")] public ResponseItem[] item_array; // 0x20
}
