// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsIndexResponse>))]
public class ChampionsIndexResponse : ResponseCommon
{
    [Key("data")] public ChampionsIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("champions_info")] public ChampionsInfo champions_info; // 0x10
        [Key("race_result_array")] public ChampionsRaceResult[] race_result_array; // 0x18
        [Key("entry_chara_array")] public ChampionsUserCharaTop[] entry_chara_array; // 0x20
        [Key("last_entry_chara_array")] public ChampionsEntryChara[] last_entry_chara_array; // 0x28
        [Key("champions_mission_array")] public UserMission[] champions_mission_array; // 0x30
        [Key("reward_array")] public ChampionsRewardInfo[] reward_array; // 0x38
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x40
        [Key("first_check_round_flag")] public int first_check_round_flag; // 0x48
        [Key("last_checked_time")] public long last_checked_time; // 0x50
        [Key("news_rank_count_info_array")] public ChampionsNewsRankCountInfo[] news_rank_count_info_array; // 0x58
        [Key("item_info_array")] public UserItem[] item_info_array; // 0x60
    }
}
