// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsFinalLobbyRequest>))]
public class ChampionsFinalLobbyRequest : RequestBase<ChampionsFinalLobbyResponse>
{
}
