// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsNewsWinInfo>))]
public class ChampionsNewsWinInfo
{
    [Key("news_win_title_id")] public int news_win_title_id; // 0x10
    [Key("news_win_comment_id")] public int news_win_comment_id; // 0x14
    [Key("news_win_id_array")] public int[] news_win_id_array; // 0x18
}
