// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsRaceEntryResponse>))]
public class ChampionsRaceEntryResponse : ResponseCommon
{
    [Key("data")] public ChampionsRaceEntryResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsRaceEntryResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("room_info_array")] public ChampionsRoomInfo[] room_info_array; // 0x10
        [Key("room_user_array")] public ChampionsRoomUser[] room_user_array; // 0x18
        [Key("state")] public int state; // 0x20
    }
}
