// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ChampionsNewsCharaInfo>))]
public class ChampionsNewsCharaInfo
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("team_id")] public int team_id; // 0x18
    [Key("team_member_id")] public int team_member_id; // 0x1C
    [Key("news_chara_id_array")] public int[] news_chara_id_array; // 0x20
    [Key("news_chara_comment_id")] public int news_chara_comment_id; // 0x28
}
