// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<changeCommentRequest>))]
public class changeCommentRequest : RequestBase<changeCommentResponse>
{
    [Key("comment")] public string comment; // 0x88
}
