// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CharaRaceReward>))]
public class CharaRaceReward
{
    [Key("result_rank")] public int result_rank; // 0x10
    [Key("result_time")] public int result_time; // 0x14
    [Key("race_reward")] public RaceRewardData[] race_reward; // 0x18
    [Key("race_reward_bonus")] public RaceRewardData[] race_reward_bonus; // 0x20
    [Key("race_reward_plus_bonus")] public RaceRewardData[] race_reward_plus_bonus; // 0x28
    [Key("race_reward_bonus_win")] public RaceRewardData[] race_reward_bonus_win; // 0x30
    [Key("race_reward_limit")] public RaceRewardLimitData[] race_reward_limit; // 0x38
    [Key("gained_fans")] public int gained_fans; // 0x40
    [Key("campaign_id_array")] public int[] campaign_id_array; // 0x48
    [Key("subscription_effect_id_array")] public int[] subscription_effect_id_array; // 0x50
}
