// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CharacterStoryData>))]
public class CharacterStoryData
{
    [Key("episode_id")] public int episode_id; // 0x10
    [Key("state")] public int state; // 0x14
}
