// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserScoutResponse>))]
public class CircleUserScoutResponse : ResponseCommon
{
    [Key("data")] public CircleUserScoutResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserScoutResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("is_scout_max")] public bool is_scout_max; // 0x10
    }
}
