// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserCancelJoinRequestResponse>))]
public class CircleUserCancelJoinRequestResponse : ResponseCommon
{
    [Key("data")] public CircleUserCancelJoinRequestResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserCancelJoinRequestResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
