// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserUserJoinRequestResponse>))]
public class CircleUserUserJoinRequestResponse : ResponseCommon
{
    [Key("data")] public CircleUserUserJoinRequestResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserUserJoinRequestResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("circle_user")] public CircleUser circle_user; // 0x10
    }
}
