// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleItemRequestDonateMultipleRequest>))]
public class CircleItemRequestDonateMultipleRequest : RequestBase<CircleItemRequestDonateMultipleResponse>
{
    [Key("request_id_array")] public int[] request_id_array; // 0x88
    [Key("client_item_data_array")] public UserItem[] client_item_data_array; // 0x90
}
