// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleChatUser>))]
public class CircleChatUser
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("name")] public string name; // 0x18
    [Key("leader_chara_id")] public int leader_chara_id; // 0x20
    [Key("leader_chara_dress_id")] public int leader_chara_dress_id; // 0x24
}
