// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleSetProfileCardInfoRequest>))]
public class CircleSetProfileCardInfoRequest : RequestBase<CircleSetProfileCardInfoResponse>
{
    [Key("profile_card_info")] public CircleProfileCardInfo profile_card_info; // 0x88
    [Key("image_file")] public string image_file; // 0x90
    [Key("name")] public string name; // 0x98
    [Key("comment")] public string comment; // 0xA0
    [Key("join_style")] public int join_style; // 0xA8
    [Key("policy")] public int policy; // 0xAC
}
