// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserApproveJoinRequestRequest>))]
public class CircleUserApproveJoinRequestRequest : RequestBase<CircleUserApproveJoinRequestResponse>
{
    [Key("target_viewer_id")] public long target_viewer_id; // 0x88
}
