// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleRoomEnterResponse>))]
public class CircleRoomEnterResponse : ResponseCommon
{
    [Key("data")] public CircleRoomEnterResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleRoomEnterResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("circle_info")] public CircleInfo circle_info; // 0x10
        [Key("circle_user_array")] public CircleUser[] circle_user_array; // 0x18
        [Key("summary_user_info_array")] public UserInfoAtFriend[] summary_user_info_array; // 0x20
        [Key("change_leader")] public bool change_leader; // 0x28
        [Key("is_scout_able")] public bool is_scout_able; // 0x29
        [Key("is_show_ranking_result")] public bool is_show_ranking_result; // 0x2A
        [Key("circle_chat_message_array")] public CircleChatMessage[] circle_chat_message_array; // 0x30
        [Key("circle_item_request_array")] public CircleItemRequest[] circle_item_request_array; // 0x38
        [Key("circle_item_donate_array")] public CircleItemDonate[] circle_item_donate_array; // 0x40
        [Key("daily_donated_count")] public int daily_donated_count; // 0x48
        [Key("circle_ranking_this_month")] public CircleRanking circle_ranking_this_month; // 0x50
        [Key("circle_ranking_last_month")] public CircleRanking circle_ranking_last_month; // 0x58
        [Key("is_calculate")] public bool is_calculate; // 0x60
        [Key("room_match_info_array")] public RoomMatchRoomInfo[] room_match_info_array; // 0x68
        [Key("room_info_array")] public RoomMatchRoomInfo[] room_info_array; // 0x70
        [Key("room_user_array")] public RoomMatchUser[] room_user_array; // 0x78
        [Key("circle_post_partner_array")] public CirclePostPartner[] circle_post_partner_array; // 0x80
        [Key("daily_post_partner_count")] public int daily_post_partner_count; // 0x88
        [Key("chat_polling_interval")] public int chat_polling_interval; // 0x8C
    }
}
