// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserCheckedRequestResponse>))]
public class CircleUserCheckedRequestResponse : ResponseCommon
{
    [Key("data")] public CircleUserCheckedRequestResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserCheckedRequestResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("last_checked_time")] public long last_checked_time; // 0x10
    }
}
