// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserChangeLeaderRequest>))]
public class CircleUserChangeLeaderRequest : RequestBase<CircleUserChangeLeaderResponse>
{
    [Key("target_viewer_id")] public long target_viewer_id; // 0x88
}
