// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserGetProfileCardInfoResponse>))]
public class CircleUserGetProfileCardInfoResponse : ResponseCommon
{
    [Key("data")] public CircleUserGetProfileCardInfoResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserGetProfileCardInfoResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("profile_card_info")] public UserProfileCardInfo profile_card_info; // 0x10
    }
}
