// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserSetProfileRequest>))]
public class CircleUserSetProfileRequest : RequestBase<CircleUserSetProfileResponse>
{
    [Key("chara_id")] public int chara_id; // 0x88
    [Key("bg_id")] public int bg_id; // 0x8C
    [Key("recruit_comment")] public string recruit_comment; // 0x90
    [Key("dress_id")] public int dress_id; // 0x98
}
