// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUpdateResponse>))]
public class CircleUpdateResponse : ResponseCommon
{
    [Key("data")] public CircleUpdateResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUpdateResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("circle_info")] public CircleInfo circle_info; // 0x10
    }
}
