// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleItemRequestGetRequestDataResponse>))]
public class CircleItemRequestGetRequestDataResponse : ResponseCommon
{
    [Key("data")] public CircleItemRequestGetRequestDataResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleItemRequestGetRequestDataResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("circle_item_request_array")] public CircleItemRequest[] circle_item_request_array; // 0x10
        [Key("circle_item_donate_array")] public CircleItemDonate[] circle_item_donate_array; // 0x18
    }
}
