// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserChangeSubLeaderRequest>))]
public class CircleUserChangeSubLeaderRequest : RequestBase<CircleUserChangeSubLeaderResponse>
{
    [Key("target_viewer_id")] public long target_viewer_id; // 0x88
    [Key("is_set")] public bool is_set; // 0x90
}
