// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserUserJoinRequestRequest>))]
public class CircleUserUserJoinRequestRequest : RequestBase<CircleUserUserJoinRequestResponse>
{
    [Key("circle_id")] public int circle_id; // 0x88
}
