// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserApproveJoinRequestResponse>))]
public class CircleUserApproveJoinRequestResponse : ResponseCommon
{
    [Key("data")] public CircleUserApproveJoinRequestResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserApproveJoinRequestResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("circle_user")] public CircleUser circle_user; // 0x10
    }
}
