// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleItemRequest>))]
public class CircleItemRequest
{
    [Key("request_id")] public int request_id; // 0x10
    [Key("viewer_id")] public long viewer_id; // 0x18
    [Key("item_id")] public int item_id; // 0x20
    [Key("end_time")] public string end_time; // 0x28
    [Key("state")] public int state; // 0x30
}
