// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserDeclineJoinRequestResponse>))]
public class CircleUserDeclineJoinRequestResponse : ResponseCommon
{
    [Key("data")] public CircleUserDeclineJoinRequestResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserDeclineJoinRequestResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
