// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserLeaveResponse>))]
public class CircleUserLeaveResponse : ResponseCommon
{
    [Key("data")] public CircleUserLeaveResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleUserLeaveResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("circle_user")] public CircleUser circle_user; // 0x10
    }
}
