// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleItemDonate>))]
public class CircleItemDonate
{
    [Key("donate_id")] public int donate_id; // 0x10
    [Key("request_id")] public int request_id; // 0x14
    [Key("viewer_id")] public long viewer_id; // 0x18
    [Key("item_num")] public int item_num; // 0x20
    [Key("state")] public int state; // 0x24
    [Key("create_time")] public string create_time; // 0x28
}
