// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleDirectResponse>))]
public class CircleDirectResponse : ResponseCommon
{
    [Key("data")] public CircleDirectResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleDirectResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("reward_info_array")] public DisplayRewardInfo[] reward_info_array; // 0x10
        [Key("after_rank")] public int after_rank; // 0x18
        [Key("best_team_evaluation_point")] public int best_team_evaluation_point; // 0x1C
    }
}
