// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CircleChatSendItemRequestRequest>))]
public class CircleChatSendItemRequestRequest : RequestBase<CircleChatSendItemRequestResponse>
{
    [Key("item_id")] public int item_id; // 0x88
}
