// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ClearedRaceInfo>))]
public class ClearedRaceInfo
{
    [Key("ultimate_race_id")] public int ultimate_race_id; // 0x10
    [Key("cleared_trained_chara_array")] public ClearedTrainedChara[] cleared_trained_chara_array; // 0x18
}
