// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CoinInfo>))]
public class CoinInfo
{
    [Key("coin")] public int coin; // 0x10
    [Key("fcoin")] public int fcoin; // 0x14
}
