// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CollectRaidPollingResponse>))]
public class CollectRaidPollingResponse : ResponseCommon
{
    [Key("data")] public CollectRaidPollingResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CollectRaidPollingResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("all_gained_collect_item_num")] public long all_gained_collect_item_num; // 0x10
        [Key("raid_polling_interval")] public int raid_polling_interval; // 0x18
        [Key("watchable_episodes")] public CollectRaidWatchableEpisode[] watchable_episodes; // 0x20
    }
}
