// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CollectRaidRegisterMessageRequest>))]
public class CollectRaidRegisterMessageRequest : RequestBase<CollectRaidRegisterMessageResponse>
{
    [Key("message_id_1")] public int message_id_1; // 0x88
    [Key("message_id_2")] public int message_id_2; // 0x8C
}
