// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ConstWalkingIndexResponse>))]
public class ConstWalkingIndexResponse : ResponseCommon
{
    [Key("data")] public ConstWalkingIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ConstWalkingIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_walking_act_array")] public NoteDataForDisplay[] chara_walking_act_array; // 0x10
        [Key("resume_state")] public int resume_state; // 0x18
        [Key("resume_chara_id")] public int resume_chara_id; // 0x1C
        [Key("resume_location_id_array")] public int[] resume_location_id_array; // 0x20
        [Key("resume_campaign_id_array")] public int[] resume_campaign_id_array; // 0x28
        [Key("is_received_daily_ticket")] public bool is_received_daily_ticket; // 0x30
        [Key("const_walking_login_time")] public string const_walking_login_time; // 0x38
    }
}
