// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ConstWalkingResult>))]
public class ConstWalkingResult
{
    [Key("chara_id")] public int chara_id; // 0x10
    [Key("love_point_info")] public LovePointInfo love_point_info; // 0x18
    [Key("const_walking_release_array")] public ConstWalkingRelease[] const_walking_release_array; // 0x20
    [Key("new_chara_profile_array")] public CharaProfileData[] new_chara_profile_array; // 0x28
}
