// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DailyLegendRaceReflectItemEffectRequest>))]
public class DailyLegendRaceReflectItemEffectRequest : RequestBase<DailyLegendRaceReflectItemEffectResponse>
{
    [Key("item_id_array")] public int[] item_id_array; // 0x88
}
