// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DailyRaceReplayCheckResponse>))]
public class DailyRaceReplayCheckResponse : ResponseCommon
{
    [Key("data")] public DailyRaceReplayCheckResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DailyRaceReplayCheckResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("rank")] public int rank; // 0x10
        [Key("first_clear_reward_array")] public RaceRewardData[] first_clear_reward_array; // 0x18
        [Key("normal_reward_array")] public RaceRewardData[] normal_reward_array; // 0x20
        [Key("rare_reward_array")] public RaceRewardData[] rare_reward_array; // 0x28
        [Key("bonus_reward_array")] public RaceRewardData[] bonus_reward_array; // 0x30
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x38
        [Key("state")] public int state; // 0x40
        [Key("limited_shop_info")] public LimitedShopInfo limited_shop_info; // 0x48
        [Key("campaign_walking_gauge_info")] public CampaignWalkingGaugeInfo campaign_walking_gauge_info; // 0x50
        [Key("factor_research_gauge_info")] public FactorResearchGaugeInfo factor_research_gauge_info; // 0x58
    }
}
