// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DailyRaceResumeResponse>))]
public class DailyRaceResumeResponse : ResponseCommon
{
    [Key("data")] public DailyRaceResumeResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DailyRaceResumeResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("race_horse_data_array")] public RaceHorseData[] race_horse_data_array; // 0x10
        [Key("season")] public int season; // 0x18
        [Key("weather")] public int weather; // 0x1C
        [Key("ground_condition")] public int ground_condition; // 0x20
        [Key("random_seed")] public int random_seed; // 0x24
        [Key("race_instance_id")] public int race_instance_id; // 0x28
        [Key("race_scenario")] public string race_scenario; // 0x30
        [Key("state")] public int state; // 0x38
        [Key("purchase_num")] public int purchase_num; // 0x3C
        [Key("is_cleared")] public int is_cleared; // 0x40
    }
}
