// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DailyRaceRecoveryTicketResponse>))]
public class DailyRaceRecoveryTicketResponse : ResponseCommon
{
    [Key("data")] public DailyRaceRecoveryTicketResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DailyRaceRecoveryTicketResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("coin_info")] public CoinInfo coin_info; // 0x10
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x18
        [Key("purchase_num")] public int purchase_num; // 0x20
    }
}
