// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DailyLegendRaceIndexResponse>))]
public class DailyLegendRaceIndexResponse : ResponseCommon
{
    [Key("data")] public DailyLegendRaceIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DailyLegendRaceIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("daily_legend_race_record_array")] public DailyLegendRaceData[] daily_legend_race_record_array; // 0x10
        [Key("update_item_array")] public UserItem[] update_item_array; // 0x18
        [Key("last_start_info")] public LastStartRaceInfo last_start_info; // 0x20
    }
}
