// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DailyRaceReflectItemEffectResponse>))]
public class DailyRaceReflectItemEffectResponse : ResponseCommon
{
    [Key("data")] public DailyRaceReflectItemEffectResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DailyRaceReflectItemEffectResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("weather")] public int weather; // 0x10
        [Key("ground_condition")] public int ground_condition; // 0x14
        [Key("race_horse_data_array")] public RaceHorseData[] race_horse_data_array; // 0x18
        [Key("item_info_array")] public UserItem[] item_info_array; // 0x20
        [Key("state")] public int state; // 0x28
    }
}
