// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DailyLegendRaceRaceEntryRequest>))]
public class DailyLegendRaceRaceEntryRequest : RequestBase<DailyLegendRaceRaceEntryResponse>
{
    [Key("daily_legend_race_id")] public int daily_legend_race_id; // 0x88
    [Key("trained_chara_id")] public int trained_chara_id; // 0x8C
}
