// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DataLinkChainBySocialAccountResponse>))]
public class DataLinkChainBySocialAccountResponse : ResponseCommon
{
    [Key("data")] public DataLinkChainBySocialAccountResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DataLinkChainBySocialAccountResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("social_account_id")] public string social_account_id; // 0x10
        [Key("social_account_type")] public int social_account_type; // 0x18
        [Key("auth_key")] public string auth_key; // 0x20
        [Key("last_account_type")] public int last_account_type; // 0x28
    }
}
