// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DataLinkGetByTransitionCodeRequest>))]
public class DataLinkGetByTransitionCodeRequest : RequestBase<DataLinkGetByTransitionCodeResponse>
{
    [Key("password")] public string password; // 0x88
    [Key("input_viewer_id")] public string input_viewer_id; // 0x90
}
