// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DataLinkPublishTransitionCodeResponse>))]
public class DataLinkPublishTransitionCodeResponse : ResponseCommon
{
    [Key("data")] public DataLinkPublishTransitionCodeResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DataLinkPublishTransitionCodeResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
