// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DataLinkGetGameDataBySocialAccountResponse>))]
public class DataLinkGetGameDataBySocialAccountResponse : ResponseCommon
{
    [Key("data")] public DataLinkGetGameDataBySocialAccountResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DataLinkGetGameDataBySocialAccountResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("viewer_id")] public long viewer_id; // 0x10
        [Key("name")] public string name; // 0x18
        [Key("is_chained")] public int is_chained; // 0x20
        [Key("request_user_name")] public string request_user_name; // 0x28
    }
}
