// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DataLinkChainByTransitionCodeRequest>))]
public class DataLinkChainByTransitionCodeRequest : RequestBase<DataLinkChainByTransitionCodeResponse>
{
    [Key("password")] public string password; // 0x88
    [Key("input_viewer_id")] public long input_viewer_id; // 0x90
}
