// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DataLinkGetByTransitionCodeResponse>))]
public class DataLinkGetByTransitionCodeResponse : ResponseCommon
{
    [Key("data")] public DataLinkGetByTransitionCodeResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DataLinkGetByTransitionCodeResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("target_viewer_id")] public long target_viewer_id; // 0x10
        [Key("name")] public string name; // 0x18
        [Key("request_user_name")] public string request_user_name; // 0x20
    }
}
