// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugSetTrainedParamResponse>))]
public class DebugSetTrainedParamResponse : ResponseCommon
{
    [Key("data")] public DebugSetTrainedParamResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugSetTrainedParamResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
