// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugUpdateTeamRankResponse>))]
public class DebugUpdateTeamRankResponse : ResponseCommon
{
    [Key("data")] public DebugUpdateTeamRankResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugUpdateTeamRankResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
