// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugRaceSimulateRequest>))]
public class DebugRaceSimulateRequest : RequestBase<DebugRaceSimulateResponse>
{
    [Key("simulator_version")] public string simulator_version; // 0x88
    [Key("simulate_resource_version")] public string simulate_resource_version; // 0x90
    [Key("race_instance_id")] public int race_instance_id; // 0x98
    [Key("random_seed")] public int random_seed; // 0x9C
    [Key("season")] public int season; // 0xA0
    [Key("weather")] public int weather; // 0xA4
    [Key("ground_condition")] public int ground_condition; // 0xA8
    [Key("race_horse_data")] public RaceHorseData[] race_horse_data; // 0xB0
    [Key("race_type")] public int race_type; // 0xB8
    [Key("self_evaluate")] public int self_evaluate; // 0xBC
    [Key("opponent_evaluate")] public int opponent_evaluate; // 0xC0
    [Key("score_calc_team_id")] public int score_calc_team_id; // 0xC4
    [Key("win_count")] public int win_count; // 0xC8
    [Key("support_card_bonus")] public int support_card_bonus; // 0xCC
    [Key("challenge_match_difficulty")] public int challenge_match_difficulty; // 0xD0
    [Key("sp_rule_data_id")] public int sp_rule_data_id; // 0xD4
    [Key("challenge_match_retry_count")] public int challenge_match_retry_count; // 0xD8
    [Key("unlock_flags")] public int unlock_flags; // 0xDC
    [Key("is_record_interval_simulate")] public int is_record_interval_simulate; // 0xE0
}
