// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugSingleModeStoryDirectResponse>))]
public class DebugSingleModeStoryDirectResponse : ResponseCommon
{
    [Key("data")] public DebugSingleModeStoryDirectResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugSingleModeStoryDirectResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("event_gain")] public StoryDirectEventReward[] event_gain; // 0x10
        [Key("skill_set")] public StoryDirectSkillSet[] skill_set; // 0x18
    }
}
