// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugAddAllItemsRequest>))]
public class DebugAddAllItemsRequest : RequestBase<DebugAddAllItemsResponse>
{
}
