// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugSetParamMaxAllRequest>))]
public class DebugSetParamMaxAllRequest : RequestBase<DebugSetParamMaxAllResponse>
{
}
