// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugSetTrainedParamRequest>))]
public class DebugSetTrainedParamRequest : RequestBase<DebugSetTrainedParamResponse>
{
    [Key("param_id")] public int param_id; // 0x88
}
