// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugUpdateDebugTimeRequest>))]
public class DebugUpdateDebugTimeRequest : RequestBase<DebugUpdateDebugTimeResponse>
{
    [Key("debug_time")] public string debug_time; // 0x88
}
