// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugSingleModeLegendAddBuffGaugeResponse>))]
public class DebugSingleModeLegendAddBuffGaugeResponse : ResponseCommon
{
    [Key("data")] public DebugSingleModeLegendAddBuffGaugeResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugSingleModeLegendAddBuffGaugeResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
