// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugRaceSimulateResponse>))]
public class DebugRaceSimulateResponse : ResponseCommon
{
    [Key("data")] public DebugRaceSimulateResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugRaceSimulateResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("race_scenario")] public string race_scenario; // 0x10
        [Key("result_array")] public RaceSimulateResult[] result_array; // 0x18
        [Key("result_team")] public TeamStadiumResultTeam result_team; // 0x20
    }
}
