// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugSetParamMaxAllResponse>))]
public class DebugSetParamMaxAllResponse : ResponseCommon
{
    [Key("data")] public DebugSetParamMaxAllResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugSetParamMaxAllResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
