// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DefaultRunningStyle>))]
public class DefaultRunningStyle
{
    [Key("card_id")] public int card_id; // 0x10
    [Key("running_style")] public int running_style; // 0x14
}
