// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DetermineTargetRaceRequest>))]
public class DetermineTargetRaceRequest : RequestBase<DetermineTargetRaceResponse>
{
    [Key("assistance_id")] public int assistance_id; // 0x88
    [Key("event_sub_id")] public int event_sub_id; // 0x8C
    [Key("running_style")] public int running_style; // 0x90
}
