// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DirectoryScoreSummary>))]
public class DirectoryScoreSummary
{
    [Key("directory_card")] public int directory_card; // 0x10
    [Key("album")] public DirectoryCategoryScoreSummary album; // 0x18
    [Key("story")] public DirectoryCategoryScoreSummary story; // 0x20
    [Key("act")] public DirectoryCategoryScoreSummary act; // 0x28
    [Key("voice")] public DirectoryCategoryScoreSummary voice; // 0x30
    [Key("nickname")] public DirectoryCategoryScoreSummary nickname; // 0x38
    [Key("gallery")] public DirectoryCategoryScoreSummary gallery; // 0x40
}
