// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<EventSkill>))]
public class EventSkill
{
    [Key("story_id")] public int story_id; // 0x10
    [Key("skill_id_array")] public int[] skill_id_array; // 0x18
}
