// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<EventChoiceRewardGainParam>))]
public class EventChoiceRewardGainParam
{
    [Key("display_id")] public int display_id; // 0x10
    [Key("effect_value_0")] public int effect_value_0; // 0x14
    [Key("effect_value_1")] public int effect_value_1; // 0x18
    [Key("effect_value_2")] public int effect_value_2; // 0x1C
}
