// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ExchangeItemInfo>))]
public class ExchangeItemInfo
{
    [Key("exchange_id")] public int exchange_id; // 0x10
    [Key("count")] public int count; // 0x14
    [Key("ex_param")] public ExchangeItemInfoExParam ex_param; // 0x18
}
