// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ExchangeItemInfoExParam>))]
public class ExchangeItemInfoExParam
{
    [Key("open_count")] public int open_count; // 0x10
}
