// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ExtraStoryFirstClearResponse>))]
public class ExtraStoryFirstClearResponse : ResponseCommon
{
    [Key("data")] public ExtraStoryFirstClearResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ExtraStoryFirstClearResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("extra_story_data")] public StoryExtraStoryData extra_story_data; // 0x10
        [Key("reward_array")] public DisplayRewardInfo[] reward_array; // 0x18
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x20
        [Key("add_music_array")] public UserMusic[] add_music_array; // 0x28
    }
}
