// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ExtraCmIndexInfo>))]
public class ExtraCmIndexInfo
{
    [Key("trained_chara_id")] public int trained_chara_id; // 0x10
    [Key("cm_detail_id")] public int cm_detail_id; // 0x14
    [Key("is_saved")] public bool is_saved; // 0x18
    [Key("delete_time")] public string delete_time; // 0x20
}
