// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ExtraStoryData>))]
public class ExtraStoryData
{
    [Key("story_event")] public StoryEventStoryData[] story_event; // 0x10
    [Key("story_event_shiori_data")] public StoryEventShioriData[] story_event_shiori_data; // 0x18
    [Key("story_extra")] public StoryExtraStoryData[] story_extra; // 0x20
    [Key("extra_cm_data")] public ExtraCmData extra_cm_data; // 0x28
}
