// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ExtraCmData>))]
public class ExtraCmData
{
    [Key("is_extra_cm_new")] public bool is_extra_cm_new; // 0x10
    [Key("cm_save_trained_chara_id_array")] public int[] cm_save_trained_chara_id_array; // 0x18
}
