// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorExtend>))]
public class FactorExtend
{
    [Key("position_id")] public int position_id; // 0x10
    [Key("base_factor_id")] public int base_factor_id; // 0x14
    [Key("factor_id")] public int factor_id; // 0x18
    [Key("register_time")] public string register_time; // 0x20
}
