// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorResearchFactorUpdateResponse>))]
public class FactorResearchFactorUpdateResponse : ResponseCommon
{
    [Key("data")] public FactorResearchFactorUpdateResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorResearchFactorUpdateResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("trained_chara")] public TrainedChara trained_chara; // 0x10
        [Key("factor_update_item_array")] public ResponseItem factor_update_item_array; // 0x18
    }
}
