// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorNextLotteryInfo>))]
public class FactorNextLotteryInfo
{
    [Key("request_lottery_type")] public int request_lottery_type; // 0x10
    [Key("need_tp")] public int need_tp; // 0x14
    [Key("need_coin")] public int need_coin; // 0x18
    [Key("need_item")] public int need_item; // 0x1C
    [Key("pass_remain_num")] public int pass_remain_num; // 0x20
}
