// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorSelectInfo>))]
public class FactorSelectInfo
{
    [Key("lottery_id")] public int lottery_id; // 0x10
    [Key("factor_info_array")] public FactorInfo[] factor_info_array; // 0x18
}
