// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FetchRaceFitAssistanceResponse>))]
public class FetchRaceFitAssistanceResponse : ResponseCommon
{
    [Key("data")] public FetchRaceFitAssistanceResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<FetchRaceFitAssistanceResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("race_fit_assistance_array")] public RaceFitAssistance[] race_fit_assistance_array; // 0x10
        [Key("recommended_scenario_support_card_array")] public RecommendedScenarioSupportCard[] recommended_scenario_support_card_array; // 0x18
    }
}
