// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendTrainedCharaChangeLockRequest>))]
public class FriendTrainedCharaChangeLockRequest : RequestBase<FriendTrainedCharaChangeLockResponse>
{
    [Key("friend_viewer_id")] public long friend_viewer_id; // 0x88
    [Key("trained_chara_id")] public int trained_chara_id; // 0x90
    [Key("lock_flag")] public int lock_flag; // 0x94
    [Key("icon_type")] public int icon_type; // 0x98
}
