// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendSimpleSearchResponse>))]
public class FriendSimpleSearchResponse : ResponseCommon
{
    [Key("data")] public FriendSimpleSearchResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendSimpleSearchResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("user_info_summary")] public UserInfoAtFriend user_info_summary; // 0x10
    }
}
