// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendGetTeamStadiumTeamDataRequest>))]
public class FriendGetTeamStadiumTeamDataRequest : RequestBase<FriendGetTeamStadiumTeamDataResponse>
{
    [Key("friend_viewer_id")] public long friend_viewer_id; // 0x88
}
