// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendLoadResponse>))]
public class FriendLoadResponse : ResponseCommon
{
    [Key("data")] public FriendLoadResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendLoadResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("friend_list")] public UserFriend[] friend_list; // 0x10
        [Key("recommend_list")] public UserFriend[] recommend_list; // 0x18
        [Key("user_info_summary_list")] public UserInfoAtFriend[] user_info_summary_list; // 0x20
        [Key("follower_info_summary_list")] public UserInfoAtFollower[] follower_info_summary_list; // 0x28
        [Key("last_friend_checked_time")] public string last_friend_checked_time; // 0x30
        [Key("follower_num")] public int follower_num; // 0x38
        [Key("succession_info_array")] public FriendSuccessionInfo[] succession_info_array; // 0x40
    }
}
