// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendUnFollowResponse>))]
public class FriendUnFollowResponse : ResponseCommon
{
    [Key("data")] public FriendUnFollowResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendUnFollowResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("friend_data")] public UserFriend friend_data; // 0x10
        [Key("deleted_friend_trained_chara_favorite")] public DeletedFriendTrainedCharaFavorite deleted_friend_trained_chara_favorite; // 0x18
    }
}
