// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendUnFollowerResponse>))]
public class FriendUnFollowerResponse : ResponseCommon
{
    [Key("data")] public FriendUnFollowerResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendUnFollowerResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("friend_data")] public UserFriend friend_data; // 0x10
    }
}
