// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GachaLimitExchangeResponse>))]
public class GachaLimitExchangeResponse : ResponseCommon
{
    [Key("data")] public GachaLimitExchangeResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<GachaLimitExchangeResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("exchange_result")] public GachaResultData exchange_result; // 0x10
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x18
        [Key("limit_item_info")] public GachaLimitItemInfo limit_item_info; // 0x20
    }
}
