// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GachaPrizeHistory>))]
public class GachaPrizeHistory
{
    [Key("result_info_array")] public GachaPrizeResultInfo[] result_info_array; // 0x10
    [Key("exec_time")] public string exec_time; // 0x18
}
