// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GachaResultData>))]
public class GachaResultData
{
    [Key("card_type")] public int card_type; // 0x10
    [Key("card_id")] public int card_id; // 0x14
    [Key("piece_id")] public int piece_id; // 0x18
    [Key("common_item_category")] public int common_item_category; // 0x1C
    [Key("common_item_id")] public int common_item_id; // 0x20
    [Key("convert_piece_num")] public int convert_piece_num; // 0x24
    [Key("convert_common_item_num")] public int convert_common_item_num; // 0x28
    [Key("additional_piece_num")] public int additional_piece_num; // 0x2C
    [Key("new_flag")] public int new_flag; // 0x30
    [Key("win_prize")] public int win_prize; // 0x34
}
