// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GachaSelectPickupStampsheetInfo>))]
public class GachaSelectPickupStampsheetInfo
{
    [Key("gacha_id")] public int gacha_id; // 0x10
    [Key("sheet_num")] public int sheet_num; // 0x14
    [Key("stamp_num")] public int stamp_num; // 0x18
    [Key("guarantee_draw_num")] public int guarantee_draw_num; // 0x1C
    [Key("guarantee_draw_right_num")] public int guarantee_draw_right_num; // 0x20
    [Key("selected_info_array")] public GachaSelectPickupSelectedInfo[] selected_info_array; // 0x28
}
