// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GachaGroupInfo>))]
public class GachaGroupInfo
{
    [Key("group_id")] public int group_id; // 0x10
    [Key("remain_draw_num")] public int remain_draw_num; // 0x14
}
