// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GachaLimitExchangeRequest>))]
public class GachaLimitExchangeRequest : RequestBase<GachaLimitExchangeResponse>
{
    [Key("gacha_id")] public int gacha_id; // 0x88
    [Key("card_type")] public int card_type; // 0x8C
    [Key("card_id")] public int card_id; // 0x90
    [Key("current_num")] public int current_num; // 0x94
    [Key("is_force_exchange")] public bool is_force_exchange; // 0x98
}
