// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GachaGetPrizeHistoryResponse>))]
public class GachaGetPrizeHistoryResponse : ResponseCommon
{
    [Key("data")] public GachaGetPrizeHistoryResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<GachaGetPrizeHistoryResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("prize_history_array")] public GachaPrizeHistory[] prize_history_array; // 0x10
    }
}
