// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GachaSelectPickupStampsheetResponse>))]
public class GachaSelectPickupStampsheetResponse : ResponseCommon
{
    [Key("data")] public GachaSelectPickupStampsheetResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<GachaSelectPickupStampsheetResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("select_pickup_info")] public GachaSelectPickupInfo select_pickup_info; // 0x10
    }
}
