// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GachaSelectPickUpRequest>))]
public class GachaSelectPickUpRequest : RequestBase<GachaSelectPickUpResponse>
{
    [Key("select_pickup_info")] public GachaSelectPickupInfo select_pickup_info; // 0x88
}
