// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GainSkillInfo>))]
public class GainSkillInfo
{
    [Key("skill_id")] public int skill_id; // 0x10
    [Key("level")] public int level; // 0x14
}
