// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GalleryPlayEventRequest>))]
public class GalleryPlayEventRequest : RequestBase<GalleryPlayEventResponse>
{
    [Key("story_id")] public int story_id; // 0x88
    [Key("select_index")] public int select_index; // 0x8C
    [Key("continuous_play_mode")] public int continuous_play_mode; // 0x90
    [Key("chara_id")] public int chara_id; // 0x94
    [Key("story_id_select_index_info_array")] public GalleryStoryIdSelectIndexInfo[] story_id_select_index_info_array; // 0x98
}
