// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

#nullable enable

using System;
using System.Collections.Frozen;
using System.Linq;
using System.Reflection;
using MessagePack;
using MessagePack.Formatters;

namespace Gallop;

internal sealed class GallopMessagePackFormatter<T> : IMessagePackFormatter<T?>
    where T : class, new()
{
    public void Serialize(ref MessagePackWriter writer, T? value, MessagePackSerializerOptions options)
    {
        if (value is null)
        {
            writer.WriteNil();
            return;
        }

        var metadata = GallopMessagePackTypeMetadata<T>.Instance;
        writer.WriteMapHeader(metadata.Fields.Length);
        foreach (var field in metadata.Fields)
        {
            writer.Write(field.Key);
            MessagePackSerializer.Serialize(field.Type, ref writer, field.Get(value), options);
        }
    }

    public T? Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)
    {
        if (reader.TryReadNil())
            return null;

        var metadata = GallopMessagePackTypeMetadata<T>.Instance;
        var value = new T();
        var count = reader.ReadMapHeader();
        for (var i = 0; i < count; i++)
        {
            var key = reader.ReadString()
                ?? throw new MessagePackSerializationException($"{typeof(T).FullName} contains a nil MessagePack map key.");

            if (!metadata.ByKey.TryGetValue(key, out var field))
            {
                reader.Skip();
                continue;
            }

            if (reader.TryReadNil())
                continue;

            field.Set(value, MessagePackSerializer.Deserialize(field.Type, ref reader, options));
        }

        return value;
    }
}

internal sealed class GallopMessagePackTypeMetadata<T>
    where T : class
{
    public static readonly GallopMessagePackTypeMetadata<T> Instance = new();

    public GallopMessagePackField[] Fields { get; }

    public FrozenDictionary<string, GallopMessagePackField> ByKey { get; }

    private GallopMessagePackTypeMetadata()
    {
        Fields = [.. typeof(T)
            .GetFields(BindingFlags.Instance | BindingFlags.Public)
            .Select(CreateField)
            .OrderBy(x => x.Key, StringComparer.Ordinal)];

        var duplicateKey = Fields
            .GroupBy(x => x.Key, StringComparer.Ordinal)
            .FirstOrDefault(x => x.Count() > 1);
        if (duplicateKey is not null)
            throw new MessagePackSerializationException($"{typeof(T).FullName} contains duplicate MessagePack key: {duplicateKey.Key}");

        ByKey = Fields.ToFrozenDictionary(x => x.Key, StringComparer.Ordinal);
    }

    private static GallopMessagePackField CreateField(FieldInfo field)
    {
        var key = field.GetCustomAttribute<KeyAttribute>()
            ?? throw new MessagePackSerializationException($"{typeof(T).FullName}.{field.Name} is missing MessagePack KeyAttribute.");

        if (key.StringKey is not { Length: > 0 } text)
            throw new MessagePackSerializationException($"{typeof(T).FullName}.{field.Name} must use a string MessagePack key.");

        return new(text, field);
    }
}

internal sealed record GallopMessagePackField(string Key, FieldInfo Field)
{
    public Type Type => Field.FieldType;

    public object? Get(object instance) => Field.GetValue(instance);

    public void Set(object instance, object? value) => Field.SetValue(instance, value);
}
