// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GenerateSuccessionUpdateSuccessionDeckSetRequest>))]
public class GenerateSuccessionUpdateSuccessionDeckSetRequest : RequestBase<GenerateSuccessionUpdateSuccessionDeckSetResponse>
{
    [Key("deck_array")] public SuccessionDeckForRequest[] deck_array; // 0x88
}
