// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GenerateSuccessionExecRequest>))]
public class GenerateSuccessionExecRequest : RequestBase<GenerateSuccessionExecResponse>
{
    [Key("start_chara")] public GenerateSuccessionStartChara start_chara; // 0x88
    [Key("use_ticket_num")] public int use_ticket_num; // 0x90
    [Key("is_valid_factor_premium_pass")] public bool is_valid_factor_premium_pass; // 0x94
}
