// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GenerateSuccessionFactorSelectRequest>))]
public class GenerateSuccessionFactorSelectRequest : RequestBase<GenerateSuccessionFactorSelectResponse>
{
    [Key("request_type")] public int request_type; // 0x88
    [Key("use_coin")] public int use_coin; // 0x8C
    [Key("factor_order_array")] public GenerateSuccessionFactorOrder[] factor_order_array; // 0x90
}
