// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GetTrophyDetailRequest>))]
public class GetTrophyDetailRequest : RequestBase<GetTrophyDetailResponse>
{
    [Key("trophy_id")] public int trophy_id; // 0x88
}
