// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GetTrophyInfoResponse>))]
public class GetTrophyInfoResponse : ResponseCommon
{
    [Key("data")] public GetTrophyInfoResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<GetTrophyInfoResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("user_trophy_info_array")] public UserTrophyInfo[] user_trophy_info_array; // 0x10
        [Key("last_checked_time")] public long last_checked_time; // 0x18
    }
}
