// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesFinalSetUmaineResponse>))]
public class HeroesFinalSetUmaineResponse : ResponseCommon
{
    [Key("data")] public HeroesFinalSetUmaineResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesFinalSetUmaineResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x10
        [Key("received_reward_group_array")] public int[] received_reward_group_array; // 0x18
    }
}
