// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesStage1HonorSelectCharaListRequest>))]
public class HeroesStage1HonorSelectCharaListRequest : RequestBase<HeroesStage1HonorSelectCharaListResponse>
{
}
