// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesFinalCharaResult>))]
public class HeroesFinalCharaResult
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("trained_chara_id")] public int trained_chara_id; // 0x18
    [Key("frame_order")] public int frame_order; // 0x1C
    [Key("rank")] public int rank; // 0x20
    [Key("finish_time")] public int finish_time; // 0x24
    [Key("horse_length")] public int horse_length; // 0x28
}
