// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesStage1EditTeamResponse>))]
public class HeroesStage1EditTeamResponse : ResponseCommon
{
    [Key("data")] public HeroesStage1EditTeamResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesStage1EditTeamResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("team_edit_reward_array")] public ResponseItem[] team_edit_reward_array; // 0x10
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x18
    }
}
