// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesFinalCheckRaceResponse>))]
public class HeroesFinalCheckRaceResponse : ResponseCommon
{
    [Key("data")] public HeroesFinalCheckRaceResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesFinalCheckRaceResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x10
        [Key("next_play_info")] public HeroesFinalNextPlayInfo next_play_info; // 0x18
    }
}
