// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesFinalLoadIndexInfo>))]
public class HeroesFinalLoadIndexInfo
{
    [Key("first_access_final_stage1_ranking_flag")] public int first_access_final_stage1_ranking_flag; // 0x10
    [Key("next_play_info")] public HeroesFinalNextPlayInfo next_play_info; // 0x18
    [Key("received_reward_group_array")] public int[] received_reward_group_array; // 0x20
    [Key("race_group_id")] public int race_group_id; // 0x28
    [Key("race_num")] public int race_num; // 0x2C
    [Key("team_edit_change_flag")] public int team_edit_change_flag; // 0x30
}
