// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesStage1GetOpponentTeamsRequest>))]
public class HeroesStage1GetOpponentTeamsRequest : RequestBase<HeroesStage1GetOpponentTeamsResponse>
{
}
