// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesStage1GetOpponentTeamsResponse>))]
public class HeroesStage1GetOpponentTeamsResponse : ResponseCommon
{
    [Key("data")] public HeroesStage1GetOpponentTeamsResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesStage1GetOpponentTeamsResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("get_opponent_team_info")] public HeroesResponseStage1GetOpponentTeamInfo get_opponent_team_info; // 0x10
    }
}
