// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesStage1EditTeamNameResponse>))]
public class HeroesStage1EditTeamNameResponse : ResponseCommon
{
    [Key("data")] public HeroesStage1EditTeamNameResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesStage1EditTeamNameResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("name")] public string name; // 0x10
    }
}
