// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesFinalIndexCharaInfo>))]
public class HeroesFinalIndexCharaInfo
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("card_id")] public int card_id; // 0x18
    [Key("rarity")] public int rarity; // 0x1C
    [Key("rank")] public int rank; // 0x20
    [Key("nickname_id")] public int nickname_id; // 0x24
    [Key("team_name")] public string team_name; // 0x28
    [Key("group_id")] public int group_id; // 0x30
    [Key("race_num")] public int race_num; // 0x34
}
