// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HeroesResponseStage1FinishSet>))]
public class HeroesResponseStage1FinishSet
{
    [Key("reward_array")] public ResponseItem[] reward_array; // 0x10
    [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x18
    [Key("hero_gauge")] public int hero_gauge; // 0x20
    [Key("hero_skill_id")] public int hero_skill_id; // 0x24
}
