// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HomeStoryDataForRegist>))]
public class HomeStoryDataForRegist
{
    [Key("id")] public int id; // 0x10
}
