// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HonorInfo>))]
public class HonorInfo
{
    [Key("honor_list")] public HonorData[] honor_list; // 0x10
    [Key("is_need_new_icon")] public bool is_need_new_icon; // 0x18
}
