// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HonorChangeHonorRequest>))]
public class HonorChangeHonorRequest : RequestBase<HonorChangeHonorResponse>
{
    [Key("honor_id")] public int honor_id; // 0x88
}
