// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HonorData>))]
public class HonorData
{
    [Key("honor_id")] public int honor_id; // 0x10
    [Key("honor_data_step_array")] public HonorDataStep[] honor_data_step_array; // 0x18
}
