// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModeMultiRaceReserveDeckRequest>))]
public class IdleSingleModeMultiRaceReserveDeckRequest : RequestBase<IdleSingleModeMultiRaceReserveDeckResponse>
{
    [Key("scenario_id")] public int scenario_id; // 0x88
    [Key("multi_race_reserve_deck")] public SingleModeMultiRaceReserveDeck multi_race_reserve_deck; // 0x90
}
