// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModeStatusResponse>))]
public class IdleSingleModeStatusResponse : ResponseCommon
{
    [Key("data")] public IdleSingleModeStatusResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModeStatusResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("progress_info")] public IdleSingleModeProgressInfo progress_info; // 0x10
    }
}
