// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModeSuccessionFactorGainInfo>))]
public class IdleSingleModeSuccessionFactorGainInfo
{
    [Key("year")] public int year; // 0x10
    [Key("gain_factor_info_array")] public FactorInfo[] gain_factor_info_array; // 0x18
}
