// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModeCheckProgressLogRequest>))]
public class IdleSingleModeCheckProgressLogRequest : RequestBase<IdleSingleModeCheckProgressLogResponse>
{
}
