// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModePrioritySkill>))]
public class IdleSingleModePrioritySkill
{
    [Key("priority")] public int priority; // 0x10
    [Key("skill_id")] public int skill_id; // 0x14
}
