// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModeStartResponse>))]
public class IdleSingleModeStartResponse : ResponseCommon
{
    [Key("data")] public IdleSingleModeStartResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModeStartResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("progress_info")] public IdleSingleModeProgressInfo progress_info; // 0x10
        [Key("tp_info")] public TpInfo tp_info; // 0x18
        [Key("user_item_array")] public UserItem[] user_item_array; // 0x20
        [Key("mission_list")] public UserMission[] mission_list; // 0x28
        [Key("story_event_mission_list")] public UserMission[] story_event_mission_list; // 0x30
        [Key("story_event_chara_bonus_list")] public StoryEventCharaBonus[] story_event_chara_bonus_list; // 0x38
        [Key("add_trained_chara_array")] public TrainedChara[] add_trained_chara_array; // 0x40
    }
}
