// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ItemExchangeAddFrameResponse>))]
public class ItemExchangeAddFrameResponse : ResponseCommon
{
    [Key("data")] public ItemExchangeAddFrameResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ItemExchangeAddFrameResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("updated_user_info")] public UserInfo updated_user_info; // 0x10
        [Key("use_item_info")] public UserItem use_item_info; // 0x18
        [Key("limited_shop_info")] public LimitedShopInfo limited_shop_info; // 0x20
    }
}
