// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ItemSellResponse>))]
public class ItemSellResponse : ResponseCommon
{
    [Key("data")] public ItemSellResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ItemSellResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x10
        [Key("use_item_info")] public UserItem[] use_item_info; // 0x18
    }
}
