// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ItemExchangeStartDashRequest>))]
public class ItemExchangeStartDashRequest : RequestBase<ItemExchangeStartDashResponse>
{
    [Key("item_id")] public int item_id; // 0x88
    [Key("card_id")] public int card_id; // 0x8C
    [Key("current_num")] public long current_num; // 0x90
}
