// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ItemExchangeLimit>))]
public class ItemExchangeLimit
{
    [Key("item_exchange_id")] public int item_exchange_id; // 0x10
    [Key("exchange_count")] public int exchange_count; // 0x14
}
