// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ItemExchangeMultiResourceRequest>))]
public class ItemExchangeMultiResourceRequest : RequestBase<ItemExchangeMultiResourceResponse>
{
    [Key("exchange_item_info_array")] public ExchangeItemInfo[] exchange_item_info_array; // 0x88
    [Key("use_item_info_array")] public UserItem[] use_item_info_array; // 0x90
    [Key("get_list_time")] public string get_list_time; // 0x98
}
