// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ItemShowExchangeRequest>))]
public class ItemShowExchangeRequest : RequestBase<ItemShowExchangeResponse>
{
    [Key("is_not_update")] public bool is_not_update; // 0x88
}
