// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<JobsStartRequest>))]
public class JobsStartRequest : RequestBase<JobsStartResponse>
{
    [Key("jobs_restart_flag")] public int jobs_restart_flag; // 0x88
    [Key("jobs_start_job_info_array")] public JobsStartJobInfo[] jobs_start_job_info_array; // 0x90
}
