// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<JobsGoingInfo>))]
public class JobsGoingInfo
{
    [Key("jobs_reward_id")] public int jobs_reward_id; // 0x10
    [Key("attend_card_info_array")] public JobsAttendCardInfo[] attend_card_info_array; // 0x18
    [Key("end_time")] public string end_time; // 0x20
    [Key("local_push_type_index")] public int local_push_type_index; // 0x28
}
