// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<JobsIndexResponse>))]
public class JobsIndexResponse : ResponseCommon
{
    [Key("data")] public JobsIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<JobsIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("jobs_going_info_array")] public JobsGoingInfo[] jobs_going_info_array; // 0x10
        [Key("jobs_limited_info_array")] public JobsLimitedInfo[] jobs_limited_info_array; // 0x18
        [Key("jobs_job_log_array")] public JobsJobLog[] jobs_job_log_array; // 0x20
        [Key("jobs_limited_top_new")] public int jobs_limited_top_new; // 0x28
        [Key("schedule_book_setting")] public ScheduleBookJobsCardSetting[] schedule_book_setting; // 0x30
    }
}
