// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<JukeboxChangeRandomRequestResponse>))]
public class JukeboxChangeRandomRequestResponse : ResponseCommon
{
    [Key("data")] public JukeboxChangeRandomRequestResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<JukeboxChangeRandomRequestResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
