// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LastStartRaceInfo>))]
public class LastStartRaceInfo
{
    [Key("race_id")] public int race_id; // 0x10
    [Key("trained_chara_id")] public int trained_chara_id; // 0x14
}
