// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LegendRacePlayingInfo>))]
public class LegendRacePlayingInfo
{
    [Key("state")] public int state; // 0x10
    [Key("group_id")] public int group_id; // 0x14
    [Key("next_group_id")] public int next_group_id; // 0x18
    [Key("trained_chara_id")] public int trained_chara_id; // 0x1C
    [Key("legend_race_record_array")] public LegendRaceData[] legend_race_record_array; // 0x20
}
