// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LegendRaceRecoveryTicketRequest>))]
public class LegendRaceRecoveryTicketRequest : RequestBase<LegendRaceRecoveryTicketResponse>
{
    [Key("client_coin_num")] public int client_coin_num; // 0x88
}
