// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LegendRaceGetRewardListResponse>))]
public class LegendRaceGetRewardListResponse : ResponseCommon
{
    [Key("data")] public LegendRaceGetRewardListResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<LegendRaceGetRewardListResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("reward_array")] public RaceRewardData[] reward_array; // 0x10
    }
}
