// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LegendRaceIndexResponse>))]
public class LegendRaceIndexResponse : ResponseCommon
{
    [Key("data")] public LegendRaceIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<LegendRaceIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("legend_race_record_array")] public LegendRaceData[] legend_race_record_array; // 0x10
        [Key("purchase_num")] public int purchase_num; // 0x18
        [Key("update_item_array")] public UserItem[] update_item_array; // 0x20
        [Key("legend_race_mission_num")] public int legend_race_mission_num; // 0x28
    }
}
