// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LegendRaceReplayCheckResponse>))]
public class LegendRaceReplayCheckResponse : ResponseCommon
{
    [Key("data")] public LegendRaceReplayCheckResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<LegendRaceReplayCheckResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("rank")] public int rank; // 0x10
        [Key("first_clear_reward_array")] public RaceRewardData[] first_clear_reward_array; // 0x18
        [Key("drop_reward_array")] public RaceRewardData[] drop_reward_array; // 0x20
        [Key("victory_reward_array")] public RaceRewardData[] victory_reward_array; // 0x28
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x30
        [Key("state")] public int state; // 0x38
        [Key("add_trophy_info")] public LoginUserTrophyInfo add_trophy_info; // 0x40
        [Key("trophy_reward_info")] public RaceRewardData trophy_reward_info; // 0x48
        [Key("limited_shop_info")] public LimitedShopInfo limited_shop_info; // 0x50
        [Key("campaign_reward_array")] public RaceRewardData[] campaign_reward_array; // 0x58
    }
}
