// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LiveTheaterPerformersPresetUpdateRequest>))]
public class LiveTheaterPerformersPresetUpdateRequest : RequestBase<LiveTheaterPerformersPresetUpdateResponse>
{
    [Key("preset")] public LiveTheaterPerformersPreset preset; // 0x88
}
