// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LiveTheaterPerformersPresetIndexResponse>))]
public class LiveTheaterPerformersPresetIndexResponse : ResponseCommon
{
    [Key("data")] public LiveTheaterPerformersPresetIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<LiveTheaterPerformersPresetIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("preset_array")] public LiveTheaterPerformersPreset[] preset_array; // 0x10
    }
}
