// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LiveTheaterIndexResponse>))]
public class LiveTheaterIndexResponse : ResponseCommon
{
    [Key("data")] public LiveTheaterIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<LiveTheaterIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("live_theater_save_info_array")] public LiveTheaterSaveInfo[] live_theater_save_info_array; // 0x10
        [Key("live_theater_last_checked_time")] public long live_theater_last_checked_time; // 0x18
    }
}
