// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LoginResponse>))]
public class LoginResponse : ResponseCommon
{
    [Key("data")] public LoginResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<LoginResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("common_define")] public CommonDefine common_define; // 0x10
        [Key("user_info")] public UserInfo user_info; // 0x18
        [Key("coin_info")] public CoinInfo coin_info; // 0x20
        [Key("trained_chara")] public TrainedChara[] trained_chara; // 0x28
        [Key("trained_chara_favorite_array")] public TrainedCharaFavorite[] trained_chara_favorite_array; // 0x30
        [Key("trained_chara_extend_save_num")] public int trained_chara_extend_save_num; // 0x38
        [Key("chara_list")] public UserChara[] chara_list; // 0x40
        [Key("card_list")] public UserCard[] card_list; // 0x48
        [Key("support_card_list")] public UserSupportCard[] support_card_list; // 0x50
        [Key("support_card_deck_array")] public UserSupportCardDeck[] support_card_deck_array; // 0x58
        [Key("last_select_support_card_deck_id")] public int last_select_support_card_deck_id; // 0x60
        [Key("rental_deck_info")] public RentalDeckInfo rental_deck_info; // 0x68
        [Key("item_list")] public UserItem[] item_list; // 0x70
        [Key("piece_list")] public PieceData[] piece_list; // 0x78
        [Key("cloth_list")] public UserCloth[] cloth_list; // 0x80
        [Key("card_dress_array")] public UserCardDress[] card_dress_array; // 0x88
        [Key("music_list")] public UserMusic[] music_list; // 0x90
        [Key("res_version")] public string res_version; // 0x98
        [Key("tp_info")] public TpInfo tp_info; // 0xA0
        [Key("rp_info")] public RpInfo rp_info; // 0xA8
        [Key("gacha_banner_info")] public GachaBannerInfo[] gacha_banner_info; // 0xB0
        [Key("gacha_campaign_info_array")] public GachaCampaignInfo[] gacha_campaign_info_array; // 0xB8
        [Key("gacha_group_info_array")] public GachaGroupInfo[] gacha_group_info_array; // 0xC0
        [Key("user_last_checked_time_list")] public LastCheckedTime[] user_last_checked_time_list; // 0xC8
        [Key("menu_badge_info")] public MenuBadgeInfo menu_badge_info; // 0xD0
        [Key("payment_purchased_times_list")] public PaymentPurchasedTimes[] payment_purchased_times_list; // 0xD8
        [Key("user_birth")] public string user_birth; // 0xE0
        [Key("recheck_dmm_jewel")] public string recheck_dmm_jewel; // 0xE8
        [Key("main_story_data_list")] public MainStoryData[] main_story_data_list; // 0xF0
        [Key("character_story_data_list")] public CharacterStoryData[] character_story_data_list; // 0xF8
        [Key("circle_data")] public CircleAtLoad circle_data; // 0x100
        [Key("single_mode_chara_light")] public SingleModeCharaLight single_mode_chara_light; // 0x108
        [Key("home_position_info")] public HomeCharacterDressInfo home_position_info; // 0x110
        [Key("is_linkage")] public int is_linkage; // 0x118
        [Key("season_pack_info")] public PaymentSeasonPackInfo season_pack_info; // 0x120
        [Key("event_data_array")] public NoteDataForDisplay[] event_data_array; // 0x128
        [Key("comeback_campaign_info")] public ComebackCampaignInfo comeback_campaign_info; // 0x130
        [Key("chara_profile_array")] public CharaProfileData[] chara_profile_array; // 0x138
        [Key("login_bonus_list")] public LoginBonusData[] login_bonus_list; // 0x140
        [Key("team_data_array")] public TeamStadiumTeamData[] team_data_array; // 0x148
        [Key("directory_card_num")] public int directory_card_num; // 0x150
        [Key("add_friend_point")] public int add_friend_point; // 0x154
        [Key("support_user_num")] public int support_user_num; // 0x158
        [Key("team_stadium_user")] public TeamStadiumUser team_stadium_user; // 0x160
        [Key("daily_race_playing_info")] public DailyRacePlayingInfo daily_race_playing_info; // 0x168
        [Key("legend_race_playing_info")] public LegendRacePlayingInfo legend_race_playing_info; // 0x170
        [Key("daily_legend_race_playing_info")] public DailyLegendRacePlayingInfo daily_legend_race_playing_info; // 0x178
        [Key("single_mode_scenario_id_array")] public int[] single_mode_scenario_id_array; // 0x180
        [Key("single_mode_rental_succession_num")] public int single_mode_rental_succession_num; // 0x188
        [Key("single_mode_succession_free_rental_time")] public long single_mode_succession_free_rental_time; // 0x190
        [Key("single_mode_difficulty_info_array")] public SingleModeDifficultyInfo[] single_mode_difficulty_info_array; // 0x198
        [Key("honor_info")] public HonorInfo honor_info; // 0x1A0
        [Key("login_trophy_info_array")] public LoginUserTrophyInfo[] login_trophy_info_array; // 0x1A8
        [Key("team_stadium_race_status")] public int team_stadium_race_status; // 0x1B0
        [Key("limited_shop_info")] public LimitedShopInfo limited_shop_info; // 0x1B8
        [Key("release_item_flag")] public int release_item_flag; // 0x1C0
        [Key("home_story_data_array")] public HomeStoryDataForDisplay[] home_story_data_array; // 0x1C8
        [Key("short_episode_data_array")] public ShortEpisodeDataForDisplay[] short_episode_data_array; // 0x1D0
        [Key("home_poster_data_array")] public HomePosterDataForDisplay[] home_poster_data_array; // 0x1D8
        [Key("home_banner_data_array")] public HomeBannerDataForDisplay[] home_banner_data_array; // 0x1E0
        [Key("ranking")] public TeamStadiumRanking ranking; // 0x1E8
        [Key("border_line")] public TeamStadiumBorderLine border_line; // 0x1F0
        [Key("tutorial_guide_data_array")] public TutorialGuideDataForDisplay[] tutorial_guide_data_array; // 0x1F8
        [Key("last_information_update_time")] public string last_information_update_time; // 0x200
        [Key("champions_info")] public ChampionsInfo champions_info; // 0x208
        [Key("release_card_array")] public int[] release_card_array; // 0x210
        [Key("unread_announce_id_array")] public int[] unread_announce_id_array; // 0x218
        [Key("released_episode_data_array")] public ReleasedEpisodeDataForDisplay[] released_episode_data_array; // 0x220
        [Key("stadium_race_chara_id_array")] public int[] stadium_race_chara_id_array; // 0x228
        [Key("extra_story_data_list")] public ExtraStoryData extra_story_data_list; // 0x230
        [Key("story_event_id")] public int story_event_id; // 0x238
        [Key("story_event_first_flag")] public bool story_event_first_flag; // 0x23C
        [Key("story_event_mission_list")] public UserMission[] story_event_mission_list; // 0x240
        [Key("story_event_roulette_coin_num")] public int story_event_roulette_coin_num; // 0x248
        [Key("notice_data")] public UserNoticeData notice_data; // 0x250
        [Key("transfer_event_info")] public TransferEventInfo transfer_event_info; // 0x258
        [Key("transfer_rotation_info")] public TransferRotationInfo transfer_rotation_info; // 0x260
        [Key("added_gacha_stock_info")] public AddedGachaStockInfo added_gacha_stock_info; // 0x268
        [Key("practice_partner_chara_array")] public TrainedChara[] practice_partner_chara_array; // 0x270
        [Key("practice_partner_owner_info_array")] public PracticePartnerOwnerInfo[] practice_partner_owner_info_array; // 0x278
        [Key("practice_race_state")] public int practice_race_state; // 0x280
        [Key("jukebox_info")] public JukeboxInfo jukebox_info; // 0x288
        [Key("jukebox_request_history")] public JukeboxRequest jukebox_request_history; // 0x290
        [Key("training_challenge_user_info")] public TrainingChallengeUserInfo training_challenge_user_info; // 0x298
        [Key("training_challenge_exam_infos")] public TrainingChallengeExamInfo[] training_challenge_exam_infos; // 0x2A0
        [Key("valentine_campaign_received_array")] public ValentineReceivedData valentine_campaign_received_array; // 0x2A8
        [Key("valentine_campaign_special_received_array")] public ValentineSpecialReceivedData valentine_campaign_special_received_array; // 0x2B0
        [Key("challenge_match_load_info")] public ChallengeMatchLoadInfo challenge_match_load_info; // 0x2B8
        [Key("talk_gallery_list")] public TalkGalleryList[] talk_gallery_list; // 0x2C0
        [Key("team_building_load_info")] public TeamBuildingLoadInfo team_building_load_info; // 0x2C8
        [Key("story_favorite_array")] public StoryFavorite[] story_favorite_array; // 0x2D0
        [Key("team_rank_reward_info_array")] public DisplayRewardInfo[] team_rank_reward_info_array; // 0x2D8
        [Key("before_team_rank")] public int before_team_rank; // 0x2E0
        [Key("after_team_rank")] public int after_team_rank; // 0x2E4
        [Key("campaign_walking_load_info")] public CampaignWalkingLoadInfo campaign_walking_load_info; // 0x2E8
        [Key("payment_maintenance_flag")] public bool payment_maintenance_flag; // 0x2F0
        [Key("collect_raid_login_info")] public CollectRaidLoginInfo collect_raid_login_info; // 0x2F8
        [Key("raffle_campaign_response_data")] public RaffleCampaignResponseData raffle_campaign_response_data; // 0x300
        [Key("single_mode_love_point_up_campaign_response_data")] public SingleModeLovePointUpCampaignResponseData single_mode_love_point_up_campaign_response_data; // 0x308
        [Key("user_campaign_info_array")] public UserCampaignInfo[] user_campaign_info_array; // 0x310
        [Key("map_event_load_info")] public MapEventLoadInfo map_event_load_info; // 0x318
        [Key("factor_research_load_info")] public FactorResearchLoadInfo factor_research_load_info; // 0x320
        [Key("heroes_load_info")] public HeroesLoadInfo heroes_load_info; // 0x328
        [Key("available_banner_id_array")] public int[] available_banner_id_array; // 0x330
        [Key("new_plushie_exists")] public bool new_plushie_exists; // 0x338
        [Key("factor_relottery_info_array")] public CampaignFactorReLotteryInfo[] factor_relottery_info_array; // 0x340
        [Key("option_info_array")] public OptionInfo[] option_info_array; // 0x348
        [Key("product_open_info_array")] public ProductOpenInfo[] product_open_info_array; // 0x350
        [Key("ultimate_race_load_info")] public UltimateRaceLoadInfo ultimate_race_load_info; // 0x358
        [Key("lock_gacha_id_array")] public int[] lock_gacha_id_array; // 0x360
        [Key("gacha_limit_state_array")] public int[] gacha_limit_state_array; // 0x368
        [Key("user_subscription_info")] public PaymentSubscriptionInfo user_subscription_info; // 0x370
        [Key("user_subscription_info_array")] public PaymentSubscriptionInfo[] user_subscription_info_array; // 0x378
        [Key("subscription_item_array")] public SubscriptionItem[] subscription_item_array; // 0x380
        [Key("viewed_latest_op_version")] public int viewed_latest_op_version; // 0x388
        [Key("training_report_info")] public TrainingReportInfo training_report_info; // 0x390
        [Key("factor_premium_pass_info")] public FactorPremiumPassInfo factor_premium_pass_info; // 0x398
        [Key("factor_order_pass_info")] public FactorOrderPassInfo factor_order_pass_info; // 0x3A0
        [Key("factor_premium_pass_purchase_info_array")] public FactorPassPurchaseInfo[] factor_premium_pass_purchase_info_array; // 0x3A8
        [Key("factor_order_pass_purchase_info_array")] public FactorPassPurchaseInfo[] factor_order_pass_purchase_info_array; // 0x3B0
        [Key("notify_product_info")] public NotifyProductInfo notify_product_info; // 0x3B8
        [Key("jobs_load_info")] public JobsLoadInfo jobs_load_info; // 0x3C0
        [Key("term_limit_campaign_array")] public TermLimitCampaign[] term_limit_campaign_array; // 0x3C8
        [Key("notify_expiration_load_info")] public NotifyExpirationLoadInfo notify_expiration_load_info; // 0x3D0
        [Key("race_fit_assistance")] public RaceFitAssistance race_fit_assistance; // 0x3D8
        [Key("selected_race_fit_assistance_info")] public SelectedRaceFitAssistanceInfo selected_race_fit_assistance_info; // 0x3E0
        [Key("recommended_scenario_support_card_array")] public RecommendedScenarioSupportCard[] recommended_scenario_support_card_array; // 0x3E8
        [Key("cygames_id_apply_product_flag")] public bool cygames_id_apply_product_flag; // 0x3F0
        [Key("cygames_id_serial_code_reward_info_array")] public SerialCodeRewardInfo[] cygames_id_serial_code_reward_info_array; // 0x3F8
        [Key("recheck_steam_product_master_id")] public int recheck_steam_product_master_id; // 0x400
        [Key("recheck_steam_order_id")] public string recheck_steam_order_id; // 0x408
        [Key("succession_deck_using_trained_chara_id_array")] public int[] succession_deck_using_trained_chara_id_array; // 0x410
        [Key("schedule_book_load_info")] public ScheduleBookLoadInfo schedule_book_load_info; // 0x418
        [Key("is_received_daily_walking_ticket")] public bool is_received_daily_walking_ticket; // 0x420
        [Key("const_walking_login_time")] public string const_walking_login_time; // 0x428
        [Key("generate_succession_chara")] public TrainedChara[] generate_succession_chara; // 0x430
        [Key("generate_succession_chara_extend_save_num")] public int generate_succession_chara_extend_save_num; // 0x438
        [Key("generate_succession_chara_manage_data")] public GenerateSuccessionCharaManageData generate_succession_chara_manage_data; // 0x440
        [Key("generate_succession_deck_using_trained_chara_id_array")] public int[] generate_succession_deck_using_trained_chara_id_array; // 0x448
        [Key("generate_succession_exec_using_trained_chara_id_array")] public int[] generate_succession_exec_using_trained_chara_id_array; // 0x450
        [Key("is_campaign_draw_enable_continuous_daily")] public int is_campaign_draw_enable_continuous_daily; // 0x458
        [Key("idle_single_mode_load_info")] public IdleSingleModeLoadInfo idle_single_mode_load_info; // 0x460
    }
}
