// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LoginBonusData>))]
public class LoginBonusData
{
    [Key("login_bonus_id")] public int login_bonus_id; // 0x10
    [Key("total_count")] public int total_count; // 0x14
}
