// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LogStoryView>))]
public class LogStoryView
{
    [Key("story_type")] public int story_type; // 0x10
    [Key("episode_id")] public int episode_id; // 0x14
    [Key("is_skipped")] public int is_skipped; // 0x18
    [Key("is_first_time")] public int is_first_time; // 0x1C
    [Key("finish_viewing_time")] public long finish_viewing_time; // 0x20
}
