// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<LovePointChangeData>))]
public class LovePointChangeData
{
    [Key("chara_id")] public int chara_id; // 0x10
    [Key("love_point")] public int[] love_point; // 0x18
}
