// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<MainStoryRaceGetEntryListRequest>))]
public class MainStoryRaceGetEntryListRequest : RequestBase<MainStoryRaceGetEntryListResponse>
{
    [Key("episode_id")] public int episode_id; // 0x88
}
