// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<MainStoryRaceRaceEndRequest>))]
public class MainStoryRaceRaceEndRequest : RequestBase<MainStoryRaceRaceEndResponse>
{
    [Key("episode_id")] public int episode_id; // 0x88
}
