// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<MainStoryRaceRaceStartRequest>))]
public class MainStoryRaceRaceStartRequest : RequestBase<MainStoryRaceRaceStartResponse>
{
    [Key("episode_id")] public int episode_id; // 0x88
    [Key("trained_chara_id")] public int trained_chara_id; // 0x8C
    [Key("running_style")] public int running_style; // 0x90
}
