// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<MapEventEndingReadRequest>))]
public class MapEventEndingReadRequest : RequestBase<MapEventEndingReadResponse>
{
}
