// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<MapEventEndingReadResponse>))]
public class MapEventEndingReadResponse : ResponseCommon
{
    [Key("data")] public MapEventEndingReadResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<MapEventEndingReadResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
