// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<MapEventFlavorTextReadRequest>))]
public class MapEventFlavorTextReadRequest : RequestBase<MapEventFlavorTextReadResponse>
{
    [Key("flavor_text_id")] public int flavor_text_id; // 0x88
}
