// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<MissionLoadResponse>))]
public class MissionLoadResponse : ResponseCommon
{
    [Key("data")] public MissionLoadResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<MissionLoadResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("mission_list")] public UserMission[] mission_list; // 0x10
    }
}
