// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<NoteSaveNoteDataResponse>))]
public class NoteSaveNoteDataResponse : ResponseCommon
{
    [Key("data")] public NoteSaveNoteDataResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<NoteSaveNoteDataResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
