// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<NoteSaveCharaDataRequest>))]
public class NoteSaveCharaDataRequest : RequestBase<NoteSaveCharaDataResponse>
{
    [Key("chara_id")] public int chara_id; // 0x88
    [Key("dress_id")] public int dress_id; // 0x8C
    [Key("mini_dress_id")] public int mini_dress_id; // 0x90
}
