// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<NoteDataForRegist>))]
public class NoteDataForRegist
{
    [Key("chara_id")] public int chara_id; // 0x10
    [Key("data_id")] public int data_id; // 0x14
}
