// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<NoteGetScenarioRecordResponse>))]
public class NoteGetScenarioRecordResponse : ResponseCommon
{
    [Key("data")] public NoteGetScenarioRecordResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<NoteGetScenarioRecordResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("scenario_record_array")] public ScenarioRecord[] scenario_record_array; // 0x10
    }
}
