// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<NoteLoadResponse>))]
public class NoteLoadResponse : ResponseCommon
{
    [Key("data")] public NoteLoadResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<NoteLoadResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("reward_info_array")] public DisplayRewardInfo[] reward_info_array; // 0x10
        [Key("before_directory_level")] public int before_directory_level; // 0x18
        [Key("rank_score")] public int rank_score; // 0x1C
        [Key("release_card_array")] public int[] release_card_array; // 0x20
        [Key("score_summary")] public DirectoryScoreSummary score_summary; // 0x28
        [Key("scenario_record_highest_score_array")] public ScenarioRecordHighestScore[] scenario_record_highest_score_array; // 0x30
        [Key("top_directory_card_array")] public DirectoryCard[] top_directory_card_array; // 0x38
    }
}
