// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PaymentPurchaseItemParam>))]
public class PaymentPurchaseItemParam
{
    [Key("id")] public int id; // 0x10
    [Key("store_product_id")] public string store_product_id; // 0x18
    [Key("name")] public string name; // 0x20
    [Key("disp_order")] public int disp_order; // 0x28
    [Key("price")] public double price; // 0x30
    [Key("formatted_price")] public string formatted_price; // 0x38
    [Key("charge_num")] public int charge_num; // 0x40
    [Key("free_num")] public int free_num; // 0x44
    [Key("limit_num")] public int limit_num; // 0x48
    [Key("limit_type")] public int limit_type; // 0x4C
    [Key("item_pack_id")] public int item_pack_id; // 0x50
    [Key("recommended_flag")] public int recommended_flag; // 0x54
    [Key("item_group")] public int item_group; // 0x58
    [Key("start_time")] public long start_time; // 0x60
    [Key("end_time")] public long end_time; // 0x68
    [Key("number_of_product_purchased")] public int number_of_product_purchased; // 0x70
}
