// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PaymentUpdateBirthResponse>))]
public class PaymentUpdateBirthResponse : ResponseCommon
{
    [Key("data")] public PaymentUpdateBirthResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<PaymentUpdateBirthResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("user_birth")] public string user_birth; // 0x10
    }
}
