// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PaymentSubscriptionInfo>))]
public class PaymentSubscriptionInfo
{
    [Key("is_valid")] public bool is_valid; // 0x10
    [Key("order_id")] public string order_id; // 0x18
    [Key("subscription_end_date")] public long subscription_end_date; // 0x20
    [Key("is_in_grace_period")] public bool is_in_grace_period; // 0x28
    [Key("is_in_account_hold")] public bool is_in_account_hold; // 0x29
    [Key("product_id")] public string product_id; // 0x30
    [Key("subscription_type")] public int subscription_type; // 0x38
    [Key("is_notification_before_expired")] public bool is_notification_before_expired; // 0x3C
}
