// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PaymentStartParam>))]
public class PaymentStartParam
{
    [Key("product_id")] public string product_id; // 0x10
    [Key("price")] public string price; // 0x18
    [Key("currency_code")] public string currency_code; // 0x20
    [Key("error_message")] public string error_message; // 0x28
}
