// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PhotoLibraryResponse>))]
public class PhotoLibraryResponse : ResponseCommon
{
    [Key("data")] public PhotoLibraryResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<PhotoLibraryResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("unique_id")] public string unique_id; // 0x10
        [Key("unique_id_circle")] public string unique_id_circle; // 0x18
    }
}
