// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PlushieCollectionResponse>))]
public class PlushieCollectionResponse : ResponseCommon
{
    [Key("data")] public PlushieCollectionResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<PlushieCollectionResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("collected_plushies")] public CollectedPlushie[] collected_plushies; // 0x10
        [Key("last_checked_time")] public int last_checked_time; // 0x18
    }
}
