// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PracticeRaceSearchPartnerRequest>))]
public class PracticeRaceSearchPartnerRequest : RequestBase<PracticeRaceSearchPartnerResponse>
{
    [Key("is_first")] public int is_first; // 0x88
}
