// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PracticeRaceCreatePartnerIdResponse>))]
public class PracticeRaceCreatePartnerIdResponse : ResponseCommon
{
    [Key("data")] public PracticeRaceCreatePartnerIdResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<PracticeRaceCreatePartnerIdResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("partner_id")] public int partner_id; // 0x10
        [Key("register_time")] public string register_time; // 0x18
        [Key("is_reach_partner_id_create_num_max")] public int is_reach_partner_id_create_num_max; // 0x20
    }
}
