// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PracticeRaceConditionPresetInfo>))]
public class PracticeRaceConditionPresetInfo
{
    [Key("race_condition_preset_id")] public int race_condition_preset_id; // 0x10
    [Key("race_condition_preset_name")] public string race_condition_preset_name; // 0x18
    [Key("race_condition_detail")] public PracticeRaceConditionDetail race_condition_detail; // 0x20
}
