// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PracticeRaceGetPartnerIdRequest>))]
public class PracticeRaceGetPartnerIdRequest : RequestBase<PracticeRaceGetPartnerIdResponse>
{
    [Key("target_trained_chara_id")] public int target_trained_chara_id; // 0x88
}
