// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PracticeRaceRaceReplayResponse>))]
public class PracticeRaceRaceReplayResponse : ResponseCommon
{
    [Key("data")] public PracticeRaceRaceReplayResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<PracticeRaceRaceReplayResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("trained_chara_array")] public TrainedChara[] trained_chara_array; // 0x10
        [Key("race_result_info")] public RaceResultInfo race_result_info; // 0x18
        [Key("entry_info_array")] public PracticeRaceEntryInfo[] entry_info_array; // 0x20
        [Key("before_season")] public int before_season; // 0x28
        [Key("before_weather")] public int before_weather; // 0x2C
        [Key("before_ground_condition")] public int before_ground_condition; // 0x30
        [Key("before_motivation")] public int before_motivation; // 0x34
        [Key("race_condition_preset_id")] public int race_condition_preset_id; // 0x38
        [Key("specified_entry_num")] public int specified_entry_num; // 0x3C
        [Key("npc_name")] public string npc_name; // 0x40
        [Key("practice_partner_owner_info_array")] public PracticePartnerOwnerInfo[] practice_partner_owner_info_array; // 0x48
    }
}
