// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PracticeRaceSavedRaceInfo>))]
public class PracticeRaceSavedRaceInfo
{
    [Key("practice_race_id")] public int practice_race_id; // 0x10
    [Key("race_instance_id")] public int race_instance_id; // 0x14
    [Key("entry_num")] public int entry_num; // 0x18
    [Key("user_entry_num")] public int user_entry_num; // 0x1C
    [Key("is_favorite")] public int is_favorite; // 0x20
    [Key("save_time")] public string save_time; // 0x28
}
