// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PracticeRaceChangeFavoriteRaceResponse>))]
public class PracticeRaceChangeFavoriteRaceResponse : ResponseCommon
{
    [Key("data")] public PracticeRaceChangeFavoriteRaceResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<PracticeRaceChangeFavoriteRaceResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("practice_race_id")] public int practice_race_id; // 0x10
        [Key("is_favorite")] public int is_favorite; // 0x14
    }
}
