// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PracticeRaceIndexResponse>))]
public class PracticeRaceIndexResponse : ResponseCommon
{
    [Key("data")] public PracticeRaceIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<PracticeRaceIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("state")] public int state; // 0x10
        [Key("practice_race_id")] public int practice_race_id; // 0x14
    }
}
