// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PresentReceiveOption>))]
public class PresentReceiveOption
{
    [Key("support_card_favorite_flag")] public OptionSupportCardFavoriteFlag[] support_card_favorite_flag; // 0x10
}
