// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PresentReceiveAllRequest>))]
public class PresentReceiveAllRequest : RequestBase<PresentReceiveAllResponse>
{
    [Key("time_filter_type")] public int time_filter_type; // 0x88
    [Key("category_filter_type")] public int[] category_filter_type; // 0x90
    [Key("is_asc")] public bool is_asc; // 0x98
    [Key("current_rest_present_num")] public int current_rest_present_num; // 0x9C
}
