// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PresetEntryChara>))]
public class PresetEntryChara
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("entry_id")] public int entry_id; // 0x18
    [Key("trained_chara_id")] public int trained_chara_id; // 0x1C
    [Key("running_style")] public int running_style; // 0x20
    [Key("use_type")] public int use_type; // 0x24
}
