// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ProductOpenDataForRegist>))]
public class ProductOpenDataForRegist
{
    [Key("product_master_id")] public int product_master_id; // 0x10
}
