// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RaceSimulateResult>))]
public class RaceSimulateResult
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("single_mode_chara_id")] public int single_mode_chara_id; // 0x18
    [Key("finish_order")] public int finish_order; // 0x1C
    [Key("time")] public int time; // 0x20
    [Key("popularity")] public int popularity; // 0x24
    [Key("popularity_mark_rank_array")] public int[] popularity_mark_rank_array; // 0x28
    [Key("score")] public TeamStadiumResultHorseScore score; // 0x30
}
