// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RaceResultInfo>))]
public class RaceResultInfo
{
    [Key("race_instance_id")] public int race_instance_id; // 0x10
    [Key("race_horse_data_array")] public RaceHorseData[] race_horse_data_array; // 0x18
    [Key("season")] public int season; // 0x20
    [Key("weather")] public int weather; // 0x24
    [Key("ground_condition")] public int ground_condition; // 0x28
    [Key("random_seed")] public int random_seed; // 0x2C
    [Key("race_scenario")] public string race_scenario; // 0x30
}
