// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RaffleCampaignResponseData>))]
public class RaffleCampaignResponseData
{
    [Key("campaign_id")] public int campaign_id; // 0x10
    [Key("state")] public int state; // 0x14
    [Key("campaign_story_condition_value")] public int campaign_story_condition_value; // 0x18
}
