// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RaffleIndexResponse>))]
public class RaffleIndexResponse : ResponseCommon
{
    [Key("data")] public RaffleIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<RaffleIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("response_data")] public RaffleCampaignResponseData response_data; // 0x10
    }
}
