// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ReadInfoRequest>))]
public class ReadInfoRequest : RequestBase<ReadInfoResponse>
{
    [Key("add_home_story_data_array")] public HomeStoryDataForRegist[] add_home_story_data_array; // 0x88
    [Key("add_short_episode_data_array")] public ShortEpisodeDataForRegist[] add_short_episode_data_array; // 0x90
    [Key("add_home_poster_data_array")] public HomePosterDataForRegist[] add_home_poster_data_array; // 0x98
    [Key("add_tutorial_guide_data_array")] public TutorialGuideDataForRegist[] add_tutorial_guide_data_array; // 0xA0
    [Key("add_released_episode_data_array")] public ReleasedEpisodeDataForRegist[] add_released_episode_data_array; // 0xA8
    [Key("add_home_banner_data_array")] public HomeBannerDataForRegist[] add_home_banner_data_array; // 0xB0
    [Key("add_campaign_walking_data")] public CampaignWalkingDataForRegist add_campaign_walking_data; // 0xB8
    [Key("add_viewed_story_array")] public LogStoryView[] add_viewed_story_array; // 0xC0
    [Key("product_open_data_array")] public ProductOpenDataForRegist[] product_open_data_array; // 0xC8
}
