// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RecoveryRacePointRequest>))]
public class RecoveryRacePointRequest : RequestBase<RecoveryRacePointResponse>
{
    [Key("count")] public int count; // 0x88
    [Key("client_own_num")] public int client_own_num; // 0x8C
}
