// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RewardSummaryInfo>))]
public class RewardSummaryInfo
{
    [Key("add_present_num")] public int add_present_num; // 0x10
    [Key("add_item_list")] public UserItem[] add_item_list; // 0x18
    [Key("add_card_list")] public UserCard[] add_card_list; // 0x20
    [Key("add_card_bonus_info")] public RewardSummaryInfo add_card_bonus_info; // 0x28
    [Key("add_support_card_list")] public UserSupportCard[] add_support_card_list; // 0x30
    [Key("add_support_card_num_array")] public RewardAddSupportCardNum[] add_support_card_num_array; // 0x38
    [Key("add_support_card_limit_break_array")] public UserSupportCardLimitBreakInfo[] add_support_card_limit_break_array; // 0x40
    [Key("add_chara_list")] public UserChara[] add_chara_list; // 0x48
    [Key("add_cloth_list")] public UserCloth[] add_cloth_list; // 0x50
    [Key("add_music_list")] public UserMusic[] add_music_list; // 0x58
    [Key("add_fcoin")] public int add_fcoin; // 0x60
    [Key("add_honor_list")] public HonorData[] add_honor_list; // 0x68
    [Key("add_piece_list")] public PieceData[] add_piece_list; // 0x70
    [Key("add_total_fan")] public int add_total_fan; // 0x78
    [Key("new_chara_profile_array")] public CharaProfileData[] new_chara_profile_array; // 0x80
    [Key("force_update_honor_id")] public int force_update_honor_id; // 0x88
}
