// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchRaceSavePresetResponse>))]
public class RoomMatchRaceSavePresetResponse : ResponseCommon
{
    [Key("data")] public RoomMatchRaceSavePresetResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchRaceSavePresetResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("preset_info_array")] public PresetInfo[] preset_info_array; // 0x10
    }
}
