// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchChangeRaceConditionNameResponse>))]
public class RoomMatchChangeRaceConditionNameResponse : ResponseCommon
{
    [Key("data")] public RoomMatchChangeRaceConditionNameResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchChangeRaceConditionNameResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
