// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchWatchRoomResponse>))]
public class RoomMatchWatchRoomResponse : ResponseCommon
{
    [Key("data")] public RoomMatchWatchRoomResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchWatchRoomResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("room_info")] public RoomMatchRoomInfo room_info; // 0x10
    }
}
