// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchGetSavedRaceResultRequest>))]
public class RoomMatchGetSavedRaceResultRequest : RequestBase<RoomMatchGetSavedRaceResultResponse>
{
    [Key("saved_room_id")] public int saved_room_id; // 0x88
    [Key("register_id")] public ulong register_id; // 0x90
}
