// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchRestrictCharaInfo>))]
public class RoomMatchRestrictCharaInfo
{
    [Key("chara_id")] public int chara_id; // 0x10
    [Key("dress_id_array")] public int[] dress_id_array; // 0x18
}
