// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchRaceEndResultResponse>))]
public class RoomMatchRaceEndResultResponse : ResponseCommon
{
    [Key("data")] public RoomMatchRaceEndResultResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchRaceEndResultResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
