// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchGetSavedRaceResultListResponse>))]
public class RoomMatchGetSavedRaceResultListResponse : ResponseCommon
{
    [Key("data")] public RoomMatchGetSavedRaceResultListResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchGetSavedRaceResultListResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("race_result_array")] public RoomMatchSavedRoomInfo[] race_result_array; // 0x10
        [Key("room_user_array")] public RoomMatchUser[] room_user_array; // 0x18
    }
}
