// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchEnterWaitingRoomResponse>))]
public class RoomMatchEnterWaitingRoomResponse : ResponseCommon
{
    [Key("data")] public RoomMatchEnterWaitingRoomResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchEnterWaitingRoomResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("room_info")] public RoomMatchRoomInfo room_info; // 0x10
        [Key("room_user_detail_array")] public RoomMatchUserDetail[] room_user_detail_array; // 0x18
        [Key("polling_interval")] public int polling_interval; // 0x20
    }
}
