// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchEditRoomRequest>))]
public class RoomMatchEditRoomRequest : RequestBase<RoomMatchEditRoomResponse>
{
    [Key("room_id")] public int room_id; // 0x88
    [Key("room_name")] public string room_name; // 0x90
    [Key("message")] public string message; // 0x98
}
