// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchRoomDetailResponse>))]
public class RoomMatchRoomDetailResponse : ResponseCommon
{
    [Key("data")] public RoomMatchRoomDetailResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchRoomDetailResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("room_info")] public RoomMatchRoomInfo room_info; // 0x10
        [Key("room_user_detail_array")] public RoomMatchUserDetail[] room_user_detail_array; // 0x18
    }
}
