// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchRoomSearchResponse>))]
public class RoomMatchRoomSearchResponse : ResponseCommon
{
    [Key("data")] public RoomMatchRoomSearchResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchRoomSearchResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("room_info")] public RoomMatchRoomInfo room_info; // 0x10
        [Key("room_user_array")] public RoomMatchUser[] room_user_array; // 0x18
        [Key("join_watch_room_num")] public int join_watch_room_num; // 0x20
    }
}
