// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchEnterWaitingRoomRequest>))]
public class RoomMatchEnterWaitingRoomRequest : RequestBase<RoomMatchEnterWaitingRoomResponse>
{
    [Key("room_id")] public int room_id; // 0x88
}
