// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchUserDetail>))]
public class RoomMatchUserDetail
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("name")] public string name; // 0x18
    [Key("leader_chara_id")] public int leader_chara_id; // 0x20
    [Key("leader_chara_dress_id")] public int leader_chara_dress_id; // 0x24
    [Key("honor_data")] public HonorData honor_data; // 0x28
    [Key("user_friend_state")] public int user_friend_state; // 0x30
    [Key("trained_chara_array")] public RoomMatchTrainedChara[] trained_chara_array; // 0x38
    [Key("join_type")] public int join_type; // 0x40
    [Key("register_time")] public string register_time; // 0x48
}
