// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<RoomMatchRoomDetailRequest>))]
public class RoomMatchRoomDetailRequest : RequestBase<RoomMatchRoomDetailResponse>
{
    [Key("room_id")] public int room_id; // 0x88
}
