// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ScheduleBookStartResponse>))]
public class ScheduleBookStartResponse : ResponseCommon
{
    [Key("data")] public ScheduleBookStartResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ScheduleBookStartResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
