// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ScheduleBookResetSettingResponse>))]
public class ScheduleBookResetSettingResponse : ResponseCommon
{
    [Key("data")] public ScheduleBookResetSettingResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ScheduleBookResetSettingResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("schedule_book_setting")] public ScheduleBookSettingInfo schedule_book_setting; // 0x10
    }
}
