// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ScheduleBookJobsInfo>))]
public class ScheduleBookJobsInfo
{
    [Key("is_maintenance")] public bool is_maintenance; // 0x10
    [Key("is_skip_open")] public bool is_skip_open; // 0x11
    [Key("jobs_going_info_array")] public JobsGoingInfo[] jobs_going_info_array; // 0x18
    [Key("jobs_limited_info_array")] public JobsLimitedInfo[] jobs_limited_info_array; // 0x20
}
