// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ScheduleBookSettingInfo>))]
public class ScheduleBookSettingInfo
{
    [Key("schedule_book_daily_race_setting")] public ScheduleBookDailyRaceSetting schedule_book_daily_race_setting; // 0x10
    [Key("schedule_book_daily_legend_race_setting")] public ScheduleBookDailyLegendRaceSetting schedule_book_daily_legend_race_setting; // 0x18
    [Key("schedule_book_team_stadium_setting")] public ScheduleBookTeamStadiumSetting schedule_book_team_stadium_setting; // 0x20
    [Key("schedule_book_jobs_setting")] public ScheduleBookJobsSetting schedule_book_jobs_setting; // 0x28
    [Key("schedule_book_jobs_card_setting")] public ScheduleBookJobsCardSetting[] schedule_book_jobs_card_setting; // 0x30
    [Key("schedule_book_const_walking_setting")] public ScheduleBookConstWalkingSetting schedule_book_const_walking_setting; // 0x38
}
