// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ScheduleBookIndexResponse>))]
public class ScheduleBookIndexResponse : ResponseCommon
{
    [Key("data")] public ScheduleBookIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ScheduleBookIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("daily_race_info")] public ScheduleBookDailyRaceInfo daily_race_info; // 0x10
        [Key("daily_legend_race_info")] public ScheduleBookDailyLegendRaceInfo daily_legend_race_info; // 0x18
        [Key("team_stadium_info")] public ScheduleBookTeamStadiumInfo team_stadium_info; // 0x20
        [Key("jobs_info")] public ScheduleBookJobsInfo jobs_info; // 0x28
        [Key("schedule_book_setting")] public ScheduleBookSettingInfo schedule_book_setting; // 0x30
        [Key("const_walking_info")] public ScheduleBookConstWalkingInfo const_walking_info; // 0x38
    }
}
