// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SelectSupportCardList>))]
public class SelectSupportCardList
{
    [Key("partner_id")] public int partner_id; // 0x10
    [Key("card_id")] public int card_id; // 0x14
    [Key("level")] public int level; // 0x18
    [Key("limit_break_count")] public int limit_break_count; // 0x1C
}
