// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFreeFactorRelotteryEndResponse>))]
public class SingleModeFreeFactorRelotteryEndResponse : ResponseCommon
{
    [Key("data")] public SingleModeFreeFactorRelotteryEndResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFreeFactorRelotteryEndResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
