// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLiveTrainingBonus>))]
public class SingleModeLiveTrainingBonus
{
    [Key("target_type")] public int target_type; // 0x10
    [Key("effect_value")] public int effect_value; // 0x14
}
