// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenChangeRunningStyleRequest>))]
public class SingleModeRamenChangeRunningStyleRequest : RequestBase<SingleModeRamenChangeRunningStyleResponse>
{
    [Key("single_mode_change_running_style_request_common")] public SingleModeChangeRunningStyleRequestCommon single_mode_change_running_style_request_common; // 0x88
}
