// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLiveChangeShortCutResponse>))]
public class SingleModeLiveChangeShortCutResponse : ResponseCommon
{
    [Key("data")] public SingleModeLiveChangeShortCutResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLiveChangeShortCutResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("unchecked_event_array")] public SingleModeEventInfo[] unchecked_event_array; // 0x18
        [Key("live_data_set")] public SingleModeLiveDataSet live_data_set; // 0x20
    }
}
