// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusChangeShortCutResponse>))]
public class SingleModeVenusChangeShortCutResponse : ResponseCommon
{
    [Key("data")] public SingleModeVenusChangeShortCutResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusChangeShortCutResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("unchecked_event_array")] public SingleModeEventInfo[] unchecked_event_array; // 0x18
        [Key("venus_data_set")] public SingleModeVenusDataSet venus_data_set; // 0x20
    }
}
