// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendParamGuardInfo>))]
public class SingleModeLegendParamGuardInfo
{
    [Key("effect_legend_chara_id")] public int effect_legend_chara_id; // 0x10
    [Key("status_type")] public int status_type; // 0x14
}
