// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeExecCommandRequestCommon>))]
public class SingleModeExecCommandRequestCommon
{
    [Key("command_type")] public int command_type; // 0x10
    [Key("command_id")] public int command_id; // 0x14
    [Key("command_group_id")] public int command_group_id; // 0x18
    [Key("select_id")] public int select_id; // 0x1C
    [Key("current_turn")] public int current_turn; // 0x20
    [Key("current_vital")] public int current_vital; // 0x24
    [Key("exec_auto_play_plan_id")] public int exec_auto_play_plan_id; // 0x28
}
