// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamSelectSuccessionResponse>))]
public class SingleModeTeamSelectSuccessionResponse : ResponseCommon
{
    [Key("data")] public SingleModeTeamSelectSuccessionResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamSelectSuccessionResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
