// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersRaceStartResponse>))]
public class SingleModeBreedersRaceStartResponse : ResponseCommon
{
    [Key("data")] public SingleModeBreedersRaceStartResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersRaceStartResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("race_start_info")] public SingleRaceStartInfo race_start_info; // 0x10
        [Key("race_scenario")] public string race_scenario; // 0x18
        [Key("breeders_data_set")] public SingleModeBreedersDataSet breeders_data_set; // 0x20
    }
}
