// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCommandResult>))]
public class SingleModeCommandResult
{
    [Key("command_id")] public int command_id; // 0x10
    [Key("sub_id")] public int sub_id; // 0x14
    [Key("result_state")] public int result_state; // 0x18
}
