// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFreeMultiItemExchangeRequest>))]
public class SingleModeFreeMultiItemExchangeRequest : RequestBase<SingleModeFreeMultiItemExchangeResponse>
{
    [Key("exchange_item_info_array")] public SingleModeFreeExchangeItemInfo[] exchange_item_info_array; // 0x88
    [Key("current_turn")] public int current_turn; // 0x90
}
