// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCookCookingRequest>))]
public class SingleModeCookCookingRequest : RequestBase<SingleModeCookCookingResponse>
{
    [Key("dish_id")] public int dish_id; // 0x88
    [Key("care_point")] public int care_point; // 0x8C
    [Key("current_turn")] public int current_turn; // 0x90
    [Key("exec_auto_play_plan_id")] public int exec_auto_play_plan_id; // 0x94
}
