// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLiveChangeRunningStyleResponse>))]
public class SingleModeLiveChangeRunningStyleResponse : ResponseCommon
{
    [Key("data")] public SingleModeLiveChangeRunningStyleResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLiveChangeRunningStyleResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
