// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenBathingResponse>))]
public class SingleModeOnsenBathingResponse : ResponseCommon
{
    [Key("data")] public SingleModeOnsenBathingResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenBathingResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("onsen_data_set")] public SingleModeOnsenDataSet onsen_data_set; // 0x10
        [Key("chara_info")] public SingleModeChara chara_info; // 0x18
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x20
        [Key("not_up_parameter_info")] public NotUpParameterInfo not_up_parameter_info; // 0x28
    }
}
