// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRaceOutResponse>))]
public class SingleModeRaceOutResponse : ResponseCommon
{
    [Key("data")] public SingleModeRaceOutResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRaceOutResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x18
        [Key("unchecked_event_array")] public SingleModeEventInfo[] unchecked_event_array; // 0x20
        [Key("ura_data_set")] public SingleModeUraDataSet ura_data_set; // 0x28
    }
}
