// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersChangeDressOptionResponse>))]
public class SingleModeBreedersChangeDressOptionResponse : ResponseCommon
{
    [Key("data")] public SingleModeBreedersChangeDressOptionResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersChangeDressOptionResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("breeders_data_set")] public SingleModeBreedersDataSet breeders_data_set; // 0x10
    }
}
