// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendCommandInfo>))]
public class SingleModeLegendCommandInfo
{
    [Key("command_type")] public int command_type; // 0x10
    [Key("command_id")] public int command_id; // 0x14
    [Key("legend_id")] public int legend_id; // 0x18
    [Key("gain_gauge")] public int gain_gauge; // 0x1C
    [Key("params_inc_dec_info_array")] public SingleModeParamsIncDecInfo[] params_inc_dec_info_array; // 0x20
    [Key("friend_gauge_gain_array")] public SingleModeLegend9048GaugeGain[] friend_gauge_gain_array; // 0x28
}
