// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenSelectRegionResponse>))]
public class SingleModeRamenSelectRegionResponse : ResponseCommon
{
    [Key("data")] public SingleModeRamenSelectRegionResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenSelectRegionResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x18
        [Key("race_condition_array")] public SingleModeRaceCondition[] race_condition_array; // 0x20
        [Key("unchecked_event_array")] public SingleModeEventInfo[] unchecked_event_array; // 0x28
        [Key("ramen_data_set")] public SingleModeRamenDataSet ramen_data_set; // 0x30
        [Key("reduce_base_turn_info_array")] public SingleModeRamenReduceBaseTurnInfo[] reduce_base_turn_info_array; // 0x38
        [Key("expected_check_point_pt")] public int expected_check_point_pt; // 0x40
    }
}
