// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLivePerformanceIncDecInfo>))]
public class SingleModeLivePerformanceIncDecInfo
{
    [Key("performance_type")] public int performance_type; // 0x10
    [Key("value")] public int value; // 0x14
}
