// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenRegionSelectCheckRequest>))]
public class SingleModeRamenRegionSelectCheckRequest : RequestBase<SingleModeRamenRegionSelectCheckResponse>
{
    [Key("current_turn")] public int current_turn; // 0x88
    [Key("region_id_array")] public int[] region_id_array; // 0x90
}
