// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeNpcResult>))]
public class SingleModeNpcResult
{
    [Key("npc_id")] public int npc_id; // 0x10
    [Key("result_rank")] public int result_rank; // 0x14
}
