// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaSaveSkillFilterSetResponse>))]
public class SingleModeMechaSaveSkillFilterSetResponse : ResponseCommon
{
    [Key("data")] public SingleModeMechaSaveSkillFilterSetResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaSaveSkillFilterSetResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
