// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeStartResponse>))]
public class SingleModeStartResponse : ResponseCommon
{
    [Key("data")] public SingleModeStartResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeStartResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_start_common")] public SingleModeStartCommon single_mode_start_common; // 0x10
        [Key("ura_data_set")] public SingleModeUraDataSet ura_data_set; // 0x18
    }
}
