// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersFactorRelotteryEndResponse>))]
public class SingleModeBreedersFactorRelotteryEndResponse : ResponseCommon
{
    [Key("data")] public SingleModeBreedersFactorRelotteryEndResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersFactorRelotteryEndResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
