// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFinishResponse>))]
public class SingleModeFinishResponse : ResponseCommon
{
    [Key("data")] public SingleModeFinishResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFinishResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_finish_common")] public SingleModeFinishCommon single_mode_finish_common; // 0x10
    }
}
