// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCookInfo>))]
public class SingleModeCookInfo
{
    [Key("care_point")] public int care_point; // 0x10
    [Key("garden_level")] public int garden_level; // 0x14
    [Key("cooking_friends_power")] public int cooking_friends_power; // 0x18
    [Key("cooking_success_point")] public int cooking_success_point; // 0x1C
    [Key("cooking_success_base_point")] public int cooking_success_base_point; // 0x20
    [Key("new_dish_flag")] public int new_dish_flag; // 0x24
    [Key("dish_effect_up_flag")] public int dish_effect_up_flag; // 0x28
    [Key("garden_level_up_flag")] public int garden_level_up_flag; // 0x2C
}
