// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeAutoPlaySavePlanDescriptionResponse>))]
public class SingleModeAutoPlaySavePlanDescriptionResponse : ResponseCommon
{
    [Key("data")] public SingleModeAutoPlaySavePlanDescriptionResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeAutoPlaySavePlanDescriptionResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
