// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaEvaluationInfo>))]
public class SingleModeMechaEvaluationInfo
{
    [Key("target_id")] public int target_id; // 0x10
    [Key("chara_id")] public int chara_id; // 0x14
    [Key("is_research_member")] public int is_research_member; // 0x18
}
