// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenSelectSuccessionResponse>))]
public class SingleModeOnsenSelectSuccessionResponse : ResponseCommon
{
    [Key("data")] public SingleModeOnsenSelectSuccessionResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenSelectSuccessionResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
