// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersStartResponse>))]
public class SingleModeBreedersStartResponse : ResponseCommon
{
    [Key("data")] public SingleModeBreedersStartResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersStartResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_start_common")] public SingleModeStartCommon single_mode_start_common; // 0x10
        [Key("breeders_data_set")] public SingleModeBreedersDataSet breeders_data_set; // 0x18
        [Key("breeders_data_set_start")] public SingleModeBreedersDataSetStart breeders_data_set_start; // 0x20
    }
}
