// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcRaceHistory>))]
public class SingleModeArcRaceHistory
{
    [Key("race_num")] public int race_num; // 0x10
    [Key("turn")] public int turn; // 0x14
    [Key("result_rank")] public int result_rank; // 0x18
}
