// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFactorReloadRequestCommon>))]
public class SingleModeFactorReloadRequestCommon
{
    [Key("lottery_count")] public int lottery_count; // 0x10
}
