// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaUpgradeRaceRequest>))]
public class SingleModeMechaUpgradeRaceRequest : RequestBase<SingleModeMechaUpgradeRaceResponse>
{
    [Key("current_turn")] public int current_turn; // 0x88
}
