// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeResultDifficultyBox>))]
public class SingleModeResultDifficultyBox
{
    [Key("box_id")] public int box_id; // 0x10
    [Key("reward_array")] public DisplayRewardInfo[] reward_array; // 0x18
}
