// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaRivalInfo>))]
public class SingleModeMechaRivalInfo
{
    [Key("speed")] public int speed; // 0x10
    [Key("stamina")] public int stamina; // 0x14
    [Key("power")] public int power; // 0x18
    [Key("guts")] public int guts; // 0x1C
    [Key("wiz")] public int wiz; // 0x20
    [Key("speed_limit")] public int speed_limit; // 0x24
    [Key("stamina_limit")] public int stamina_limit; // 0x28
    [Key("power_limit")] public int power_limit; // 0x2C
    [Key("guts_limit")] public int guts_limit; // 0x30
    [Key("wiz_limit")] public int wiz_limit; // 0x34
    [Key("progress_rate")] public int progress_rate; // 0x38
}
