// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerAutoPlanningDialogCheckedResponse>))]
public class SingleModePioneerAutoPlanningDialogCheckedResponse : ResponseCommon
{
    [Key("data")] public SingleModePioneerAutoPlanningDialogCheckedResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerAutoPlanningDialogCheckedResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
