// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFreeTwinkleRaceNpcInfo>))]
public class SingleModeFreeTwinkleRaceNpcInfo
{
    [Key("npc_id")] public int npc_id; // 0x10
    [Key("chara_id")] public int chara_id; // 0x14
    [Key("dress_id")] public int dress_id; // 0x18
    [Key("talent_level")] public int talent_level; // 0x1C
    [Key("win_points")] public int win_points; // 0x20
    [Key("speed")] public int speed; // 0x24
    [Key("stamina")] public int stamina; // 0x28
    [Key("power")] public int power; // 0x2C
    [Key("guts")] public int guts; // 0x30
    [Key("wiz")] public int wiz; // 0x34
    [Key("proper_distance_short")] public int proper_distance_short; // 0x38
    [Key("proper_distance_mile")] public int proper_distance_mile; // 0x3C
    [Key("proper_distance_middle")] public int proper_distance_middle; // 0x40
    [Key("proper_distance_long")] public int proper_distance_long; // 0x44
    [Key("proper_running_style_nige")] public int proper_running_style_nige; // 0x48
    [Key("proper_running_style_senko")] public int proper_running_style_senko; // 0x4C
    [Key("proper_running_style_sashi")] public int proper_running_style_sashi; // 0x50
    [Key("proper_running_style_oikomi")] public int proper_running_style_oikomi; // 0x54
    [Key("proper_ground_turf")] public int proper_ground_turf; // 0x58
    [Key("proper_ground_dirt")] public int proper_ground_dirt; // 0x5C
    [Key("skill_array")] public SkillData[] skill_array; // 0x60
}
