// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusVenusRaceOutRequest>))]
public class SingleModeVenusVenusRaceOutRequest : RequestBase<SingleModeVenusVenusRaceOutResponse>
{
    [Key("current_turn")] public int current_turn; // 0x88
}
