// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLiveMasterSquareResponse>))]
public class SingleModeLiveMasterSquareResponse : ResponseCommon
{
    [Key("data")] public SingleModeLiveMasterSquareResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLiveMasterSquareResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("not_up_parameter_info")] public NotUpParameterInfo not_up_parameter_info; // 0x18
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x20
        [Key("unchecked_event_array")] public SingleModeEventInfo[] unchecked_event_array; // 0x28
        [Key("live_data_set")] public SingleModeLiveDataSet live_data_set; // 0x30
    }
}
