// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersTeamMemberInfo>))]
public class SingleModeBreedersTeamMemberInfo
{
    [Key("member_id")] public int member_id; // 0x10
    [Key("chara_id")] public int chara_id; // 0x14
    [Key("rank")] public int rank; // 0x18
    [Key("exp")] public int exp; // 0x1C
}
