// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBonusEffect>))]
public class SingleModeBonusEffect
{
    [Key("target_type")] public int target_type; // 0x10
    [Key("min")] public int min; // 0x14
    [Key("max")] public int max; // 0x18
}
