// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenUrafEffectSelectEventCheckedRequest>))]
public class SingleModeRamenUrafEffectSelectEventCheckedRequest : RequestBase<SingleModeRamenUrafEffectSelectEventCheckedResponse>
{
    [Key("current_turn")] public int current_turn; // 0x88
}
