// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSportGainRank>))]
public class SingleModeSportGainRank
{
    [Key("command_id")] public int command_id; // 0x10
    [Key("gain_rank")] public int gain_rank; // 0x14
}
