// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeNpcTeamData>))]
public class SingleModeNpcTeamData
{
    [Key("distance_type")] public int distance_type; // 0x10
    [Key("member_id")] public int member_id; // 0x14
    [Key("base_npc_id")] public int base_npc_id; // 0x18
    [Key("npc_id")] public int npc_id; // 0x1C
    [Key("running_style")] public int running_style; // 0x20
}
