// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenSaveSkillFilterSetRequest>))]
public class SingleModeRamenSaveSkillFilterSetRequest : RequestBase<SingleModeRamenSaveSkillFilterSetResponse>
{
    [Key("setting_array")] public SingleModeSkillFilterSet[] setting_array; // 0x88
}
