// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusRaceAnalyzeResponse>))]
public class SingleModeVenusRaceAnalyzeResponse : ResponseCommon
{
    [Key("data")] public SingleModeVenusRaceAnalyzeResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusRaceAnalyzeResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("race_horse_data_array")] public RaceHorseData[] race_horse_data_array; // 0x10
    }
}
