// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerCheckPointInfo>))]
public class SingleModePioneerCheckPointInfo
{
    [Key("check_point_type")] public int check_point_type; // 0x10
    [Key("result_state")] public int result_state; // 0x14
}
