// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegend9048GaugeGain>))]
public class SingleModeLegend9048GaugeGain
{
    [Key("training_partner_id")] public int training_partner_id; // 0x10
    [Key("gain_value")] public int gain_value; // 0x14
}
