// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerPlanningRequest>))]
public class SingleModePioneerPlanningRequest : RequestBase<SingleModePioneerPlanningResponse>
{
    [Key("planning_info_array")] public SingleModePioneerPlanningInfo[] planning_info_array; // 0x88
    [Key("current_turn")] public int current_turn; // 0x90
}
