// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSelectIndexInfo>))]
public class SingleModeSelectIndexInfo
{
    [Key("branch_number")] public int branch_number; // 0x10
    [Key("select_index")] public int select_index; // 0x14
}
