// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenStartResponse>))]
public class SingleModeOnsenStartResponse : ResponseCommon
{
    [Key("data")] public SingleModeOnsenStartResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenStartResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_start_common")] public SingleModeStartCommon single_mode_start_common; // 0x10
        [Key("onsen_data_set")] public SingleModeOnsenDataSet onsen_data_set; // 0x18
    }
}
