// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcSelectionRivalInfo>))]
public class SingleModeArcSelectionRivalInfo
{
    [Key("chara_id")] public int chara_id; // 0x10
    [Key("mark")] public int mark; // 0x14
    [Key("win_approval_point")] public int win_approval_point; // 0x18
    [Key("lose_approval_point")] public int lose_approval_point; // 0x1C
    [Key("rival_win_approval_point")] public int rival_win_approval_point; // 0x20
    [Key("rival_lose_approval_point")] public int rival_lose_approval_point; // 0x24
}
