// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamGainSkillsResponse>))]
public class SingleModeTeamGainSkillsResponse : ResponseCommon
{
    [Key("data")] public SingleModeTeamGainSkillsResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamGainSkillsResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x18
        [Key("team_data_set")] public SingleModeTeamDataSet team_data_set; // 0x20
    }
}
