// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusFactorSelectResponse>))]
public class SingleModeVenusFactorSelectResponse : ResponseCommon
{
    [Key("data")] public SingleModeVenusFactorSelectResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusFactorSelectResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_factor_select_common")] public SingleModeFactorSelectCommon single_mode_factor_select_common; // 0x10
        [Key("single_mode_factor_order_common")] public SingleModeFactorOrderCommon single_mode_factor_order_common; // 0x18
    }
}
