// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendContinueResponse>))]
public class SingleModeLegendContinueResponse : ResponseCommon
{
    [Key("data")] public SingleModeLegendContinueResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendContinueResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x18
        [Key("race_start_info")] public SingleRaceStartInfo race_start_info; // 0x20
        [Key("unchecked_event_array")] public SingleModeEventInfo[] unchecked_event_array; // 0x28
        [Key("user_item")] public UserItem user_item; // 0x30
        [Key("legend_data_set")] public SingleModeLegendDataSet legend_data_set; // 0x38
    }
}
