// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCookFactorReloadRequest>))]
public class SingleModeCookFactorReloadRequest : RequestBase<SingleModeCookFactorReloadResponse>
{
    [Key("single_mode_factor_reload_request_common")] public SingleModeFactorReloadRequestCommon single_mode_factor_reload_request_common; // 0x88
}
