// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendNotUpParameterInfo>))]
public class SingleModeLegendNotUpParameterInfo
{
    [Key("legend_id_array")] public int[] legend_id_array; // 0x10
    [Key("friend_partner_id_array")] public int[] friend_partner_id_array; // 0x18
    [Key("friend_partner_id_at_random_array")] public int[] friend_partner_id_at_random_array; // 0x20
    [Key("friend_lv_partner_id_array")] public int[] friend_lv_partner_id_array; // 0x28
    [Key("not_up_9046_remain_count")] public bool not_up_9046_remain_count; // 0x30
}
