// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaFinishClawCraneRequest>))]
public class SingleModeMechaFinishClawCraneRequest : RequestBase<SingleModeMechaFinishClawCraneResponse>
{
    [Key("single_mode_finish_claw_crane_request_common")] public SingleModeFinishClawCraneRequestCommon single_mode_finish_claw_crane_request_common; // 0x88
}
