// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenSelectDigOnsenResponse>))]
public class SingleModeOnsenSelectDigOnsenResponse : ResponseCommon
{
    [Key("data")] public SingleModeOnsenSelectDigOnsenResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenSelectDigOnsenResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("onsen_data_set")] public SingleModeOnsenDataSet onsen_data_set; // 0x10
        [Key("unchecked_event_array")] public SingleModeEventInfo[] unchecked_event_array; // 0x18
        [Key("chara_info")] public SingleModeChara chara_info; // 0x20
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x28
        [Key("race_condition_array")] public SingleModeRaceCondition[] race_condition_array; // 0x30
    }
}
