// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamLoadResponse>))]
public class SingleModeTeamLoadResponse : ResponseCommon
{
    [Key("data")] public SingleModeTeamLoadResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamLoadResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_load_common")] public SingleModeLoadCommon single_mode_load_common; // 0x10
        [Key("team_data_set")] public SingleModeTeamDataSet team_data_set; // 0x18
    }
}
