// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamTeamRaceStartResponse>))]
public class SingleModeTeamTeamRaceStartResponse : ResponseCommon
{
    [Key("data")] public SingleModeTeamTeamRaceStartResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamTeamRaceStartResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("team_data_set")] public SingleModeTeamDataSet team_data_set; // 0x18
    }
}
