// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcArcRaceContinueRequest>))]
public class SingleModeArcArcRaceContinueRequest : RequestBase<SingleModeArcArcRaceContinueResponse>
{
    [Key("continue_type")] public int continue_type; // 0x88
    [Key("current_turn")] public int current_turn; // 0x8C
}
