// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSportTraining>))]
public class SingleModeSportTraining
{
    [Key("command_type")] public int command_type; // 0x10
    [Key("command_id")] public int command_id; // 0x14
    [Key("sport_rank")] public int sport_rank; // 0x18
}
