// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSportMultiRaceReserveRequest>))]
public class SingleModeSportMultiRaceReserveRequest : RequestBase<SingleModeSportMultiRaceReserveResponse>
{
    [Key("single_mode_multi_race_reserve_request_common")] public SingleModeMultiRaceReserveRequestCommon single_mode_multi_race_reserve_request_common; // 0x88
}
