// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaFactorOrderLoadRequest>))]
public class SingleModeMechaFactorOrderLoadRequest : RequestBase<SingleModeMechaFactorOrderLoadResponse>
{
}
