// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSportStartRequest>))]
public class SingleModeSportStartRequest : RequestBase<SingleModeSportStartResponse>
{
    [Key("single_mode_start_request_common")] public SingleModeStartRequestCommon single_mode_start_request_common; // 0x88
}
