// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenDataSetLoad>))]
public class SingleModeRamenDataSetLoad
{
    [Key("auto_select_info")] public SingleModeRamenAutoSelectInfo auto_select_info; // 0x10
    [Key("auto_select_set_info")] public SingleModeRamenAutoSelectSetInfo[] auto_select_set_info; // 0x18
    [Key("selected_region_id_array")] public int[] selected_region_id_array; // 0x20
    [Key("reduce_base_turn_info_array")] public SingleModeRamenReduceBaseTurnInfo[] reduce_base_turn_info_array; // 0x28
    [Key("check_point_info_array")] public SingleModeRamenCheckPointInfo[] check_point_info_array; // 0x30
    [Key("last_tasting_info")] public SingleModeRamenLastTastingInfo last_tasting_info; // 0x38
    [Key("check_point_pt")] public int check_point_pt; // 0x40
    [Key("expected_check_point_pt")] public int expected_check_point_pt; // 0x44
    [Key("used_twinkle_text_id_array")] public int[] used_twinkle_text_id_array; // 0x48
    [Key("is_checked_uraf_event")] public int is_checked_uraf_event; // 0x50
}
