// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersDataSetStart>))]
public class SingleModeBreedersDataSetStart
{
    [Key("last_select_bc_group_id")] public int last_select_bc_group_id; // 0x10
    [Key("deck_id")] public int deck_id; // 0x14
    [Key("team_review_result_array")] public SingleModeBreedersTeamReviewResult[] team_review_result_array; // 0x18
    [Key("enhance_group_array")] public SingleModeBreedersEnhanceGroup[] enhance_group_array; // 0x20
}
