// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerFactorRelotteryEndResponse>))]
public class SingleModePioneerFactorRelotteryEndResponse : ResponseCommon
{
    [Key("data")] public SingleModePioneerFactorRelotteryEndResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerFactorRelotteryEndResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
