// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcInfo>))]
public class SingleModeArcInfo
{
    [Key("approval_rate")] public int approval_rate; // 0x10
    [Key("potential_array")] public ArcPotential[] potential_array; // 0x18
    [Key("global_exp")] public int global_exp; // 0x20
    [Key("sp_tag_boost_type")] public int sp_tag_boost_type; // 0x24
    [Key("ss_match_win_count")] public int ss_match_win_count; // 0x28
    [Key("special_ss_match_win_count")] public int special_ss_match_win_count; // 0x2C
}
