// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenChangeRunningStyleResponse>))]
public class SingleModeOnsenChangeRunningStyleResponse : ResponseCommon
{
    [Key("data")] public SingleModeOnsenChangeRunningStyleResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenChangeRunningStyleResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
