// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCookFacilityLevelUpResponse>))]
public class SingleModeCookFacilityLevelUpResponse : ResponseCommon
{
    [Key("data")] public SingleModeCookFacilityLevelUpResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCookFacilityLevelUpResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x18
        [Key("cook_data_set")] public SingleModeCookDataSet cook_data_set; // 0x20
    }
}
