// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenCheckPointRequest>))]
public class SingleModeRamenCheckPointRequest : RequestBase<SingleModeRamenCheckPointResponse>
{
    [Key("current_turn")] public int current_turn; // 0x88
    [Key("twinkle_text_id_array")] public int[] twinkle_text_id_array; // 0x90
}
