// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeHomeInfo>))]
public class SingleModeHomeInfo
{
    [Key("command_info_array")] public SingleModeCommandInfo[] command_info_array; // 0x10
    [Key("race_entry_restriction")] public int race_entry_restriction; // 0x18
    [Key("disable_command_info_array")] public DisableCommandInfo[] disable_command_info_array; // 0x20
    [Key("available_continue_num")] public int available_continue_num; // 0x28
    [Key("available_free_continue_num")] public int available_free_continue_num; // 0x2C
    [Key("free_continue_num")] public int free_continue_num; // 0x30
    [Key("free_continue_time")] public long free_continue_time; // 0x38
    [Key("continue_unlock_flag")] public bool continue_unlock_flag; // 0x40
    [Key("shortened_race_state")] public int shortened_race_state; // 0x44
    [Key("special_home_id")] public int special_home_id; // 0x48
    [Key("disable_race_turn_array")] public int[] disable_race_turn_array; // 0x50
}
