// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersGetChoiceRewardResponse>))]
public class SingleModeBreedersGetChoiceRewardResponse : ResponseCommon
{
    [Key("data")] public SingleModeBreedersGetChoiceRewardResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersGetChoiceRewardResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("choice_reward_array")] public EventChoiceReward[] choice_reward_array; // 0x10
    }
}
