// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusStartResponse>))]
public class SingleModeVenusStartResponse : ResponseCommon
{
    [Key("data")] public SingleModeVenusStartResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusStartResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_start_common")] public SingleModeStartCommon single_mode_start_common; // 0x10
        [Key("venus_data_set")] public SingleModeVenusDataSet venus_data_set; // 0x18
    }
}
