// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenReduceFeelingTurn>))]
public class SingleModeRamenReduceFeelingTurn
{
    [Key("feeling_id")] public int feeling_id; // 0x10
    [Key("turn")] public int turn; // 0x14
}
