// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCookFactorRelotteryEndResponse>))]
public class SingleModeCookFactorRelotteryEndResponse : ResponseCommon
{
    [Key("data")] public SingleModeCookFactorRelotteryEndResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCookFactorRelotteryEndResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
