// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendPopularityEndRequest>))]
public class SingleModeLegendPopularityEndRequest : RequestBase<SingleModeLegendPopularityEndResponse>
{
    [Key("current_turn")] public int current_turn; // 0x88
}
