// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenUrafEffectInfo>))]
public class SingleModeRamenUrafEffectInfo
{
    [Key("uraf_effect_type")] public int uraf_effect_type; // 0x10
    [Key("uraf_effect_state")] public int uraf_effect_state; // 0x14
}
