// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendExchangeBuffRequest>))]
public class SingleModeLegendExchangeBuffRequest : RequestBase<SingleModeLegendExchangeBuffResponse>
{
    [Key("before_buff_id")] public int before_buff_id; // 0x88
    [Key("after_buff_id")] public int after_buff_id; // 0x8C
    [Key("current_turn")] public int current_turn; // 0x90
}
