// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerPioneerCompleteRequest>))]
public class SingleModePioneerPioneerCompleteRequest : RequestBase<SingleModePioneerPioneerCompleteResponse>
{
    [Key("current_turn")] public int current_turn; // 0x88
}
