// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenFactorRelotteryEndResponse>))]
public class SingleModeOnsenFactorRelotteryEndResponse : ResponseCommon
{
    [Key("data")] public SingleModeOnsenFactorRelotteryEndResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenFactorRelotteryEndResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
