// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendFactorLotteryRequest>))]
public class SingleModeLegendFactorLotteryRequest : RequestBase<SingleModeLegendFactorLotteryResponse>
{
    [Key("single_mode_factor_lottery_request_common")] public SingleModeFactorLotteryRequestCommon single_mode_factor_lottery_request_common; // 0x88
}
