// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaFactorRelotteryEndResponse>))]
public class SingleModeMechaFactorRelotteryEndResponse : ResponseCommon
{
    [Key("data")] public SingleModeMechaFactorRelotteryEndResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaFactorRelotteryEndResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
