// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCookRaceEndRequest>))]
public class SingleModeCookRaceEndRequest : RequestBase<SingleModeCookRaceEndResponse>
{
    [Key("single_mode_race_end_request_common")] public SingleModeRaceEndRequestCommon single_mode_race_end_request_common; // 0x88
}
