// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSportSelectSuccessionResponse>))]
public class SingleModeSportSelectSuccessionResponse : ResponseCommon
{
    [Key("data")] public SingleModeSportSelectSuccessionResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSportSelectSuccessionResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
