// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersFactorSelectRequest>))]
public class SingleModeBreedersFactorSelectRequest : RequestBase<SingleModeBreedersFactorSelectResponse>
{
    [Key("single_mode_factor_select_request_common")] public SingleModeFactorSelectRequestCommon single_mode_factor_select_request_common; // 0x88
}
