// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenAutoSelectInfo>))]
public class SingleModeRamenAutoSelectInfo
{
    [Key("is_auto_select")] public int is_auto_select; // 0x10
    [Key("junior_region_set")] public int[] junior_region_set; // 0x18
    [Key("classic_region_set")] public int[] classic_region_set; // 0x20
    [Key("senior_region_set")] public int[] senior_region_set; // 0x28
}
