// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamTeamRaceAnalyzeResponse>))]
public class SingleModeTeamTeamRaceAnalyzeResponse : ResponseCommon
{
    [Key("data")] public SingleModeTeamTeamRaceAnalyzeResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamTeamRaceAnalyzeResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("analyze_mark_array")] public SingleModeTeamAnalyzeMarkArray[] analyze_mark_array; // 0x10
    }
}
