// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCookAvailableDishInfo>))]
public class SingleModeCookAvailableDishInfo
{
    [Key("dish_id")] public int dish_id; // 0x10
    [Key("dish_effect_info_array")] public SingleModeCookDishEffect[] dish_effect_info_array; // 0x18
}
