// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFactorOrderLoadCommon>))]
public class SingleModeFactorOrderLoadCommon
{
    [Key("factor_order_info")] public FactorOrderInfo factor_order_info; // 0x10
    [Key("lottery_remain_num")] public int lottery_remain_num; // 0x18
}
