// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusVenusRaceStartRequest>))]
public class SingleModeVenusVenusRaceStartRequest : RequestBase<SingleModeVenusVenusRaceStartResponse>
{
    [Key("is_short")] public int is_short; // 0x88
    [Key("current_turn")] public int current_turn; // 0x8C
}
