// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcSelectionResultInfo>))]
public class SingleModeArcSelectionResultInfo
{
    [Key("chara_id")] public int chara_id; // 0x10
    [Key("result")] public int result; // 0x14
}
