// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaSubCommandCharaInfo>))]
public class SingleModeMechaSubCommandCharaInfo
{
    [Key("command_id")] public int command_id; // 0x10
    [Key("chara_id")] public int chara_id; // 0x14
}
