// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcRaceAnalyzeRequest>))]
public class SingleModeArcRaceAnalyzeRequest : RequestBase<SingleModeArcRaceAnalyzeResponse>
{
    [Key("single_mode_race_analyze_request_common")] public SingleModeRaceAnalyzeRequestCommon single_mode_race_analyze_request_common; // 0x88
}
