// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaExecCommandRequest>))]
public class SingleModeMechaExecCommandRequest : RequestBase<SingleModeMechaExecCommandResponse>
{
    [Key("single_mode_exec_command_request_common")] public SingleModeExecCommandRequestCommon single_mode_exec_command_request_common; // 0x88
}
