// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenFactorOrderLoadRequest>))]
public class SingleModeRamenFactorOrderLoadRequest : RequestBase<SingleModeRamenFactorOrderLoadResponse>
{
}
