// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerFinishResponse>))]
public class SingleModePioneerFinishResponse : ResponseCommon
{
    [Key("data")] public SingleModePioneerFinishResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerFinishResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_finish_common")] public SingleModeFinishCommon single_mode_finish_common; // 0x10
    }
}
