// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenFinishRequest>))]
public class SingleModeRamenFinishRequest : RequestBase<SingleModeRamenFinishResponse>
{
    [Key("single_mode_finish_request_common")] public SingleModeFinishRequestCommon single_mode_finish_request_common; // 0x88
}
