// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersTeamSpTrainingResponse>))]
public class SingleModeBreedersTeamSpTrainingResponse : ResponseCommon
{
    [Key("data")] public SingleModeBreedersTeamSpTrainingResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersTeamSpTrainingResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x18
        [Key("active_effect_ids")] public int[] active_effect_ids; // 0x20
        [Key("breeders_data_set")] public SingleModeBreedersDataSet breeders_data_set; // 0x28
    }
}
