// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendStartRequest>))]
public class SingleModeLegendStartRequest : RequestBase<SingleModeLegendStartResponse>
{
    [Key("single_mode_start_request_common")] public SingleModeStartRequestCommon single_mode_start_request_common; // 0x88
}
