// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenGetChoiceRewardRequest>))]
public class SingleModeOnsenGetChoiceRewardRequest : RequestBase<SingleModeOnsenGetChoiceRewardResponse>
{
    [Key("event_id")] public int event_id; // 0x88
}
