// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendSelectBuffRequest>))]
public class SingleModeLegendSelectBuffRequest : RequestBase<SingleModeLegendSelectBuffResponse>
{
    [Key("buff_id")] public int buff_id; // 0x88
    [Key("current_turn")] public int current_turn; // 0x8C
}
