// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcSpecialMatchInfo>))]
public class SingleModeArcSpecialMatchInfo
{
    [Key("is_special_match")] public int is_special_match; // 0x10
    [Key("params_inc_dec_info_array")] public SingleModeParamsIncDecInfo[] params_inc_dec_info_array; // 0x18
}
