// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenFinishClawCraneResponse>))]
public class SingleModeRamenFinishClawCraneResponse : ResponseCommon
{
    [Key("data")] public SingleModeRamenFinishClawCraneResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenFinishClawCraneResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("unchecked_event_array")] public SingleModeEventInfo[] unchecked_event_array; // 0x18
        [Key("result_state")] public int result_state; // 0x20
        [Key("is_new_plushie_contained")] public bool is_new_plushie_contained; // 0x24
        [Key("ramen_data_set")] public SingleModeRamenDataSet ramen_data_set; // 0x28
    }
}
