// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamSaveTeamEditFlagRequest>))]
public class SingleModeTeamSaveTeamEditFlagRequest : RequestBase<SingleModeTeamSaveTeamEditFlagResponse>
{
    [Key("team_edit_flag")] public int team_edit_flag; // 0x88
    [Key("current_turn")] public int current_turn; // 0x8C
}
