// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendBadConditionGuardInfo>))]
public class SingleModeLegendBadConditionGuardInfo
{
    [Key("effect_legend_chara_id")] public int effect_legend_chara_id; // 0x10
    [Key("target_chara_effect_id")] public int target_chara_effect_id; // 0x14
}
