// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFreeItemEffect>))]
public class SingleModeFreeItemEffect
{
    [Key("use_id")] public int use_id; // 0x10
    [Key("item_id")] public int item_id; // 0x14
    [Key("effect_type")] public int effect_type; // 0x18
    [Key("effect_value_1")] public int effect_value_1; // 0x1C
    [Key("effect_value_2")] public int effect_value_2; // 0x20
    [Key("effect_value_3")] public int effect_value_3; // 0x24
    [Key("effect_value_4")] public int effect_value_4; // 0x28
    [Key("begin_turn")] public int begin_turn; // 0x2C
    [Key("end_turn")] public int end_turn; // 0x30
}
