// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenAutoSelectSetNameSaveRequest>))]
public class SingleModeRamenAutoSelectSetNameSaveRequest : RequestBase<SingleModeRamenAutoSelectSetNameSaveResponse>
{
    [Key("set_id")] public int set_id; // 0x88
    [Key("set_name")] public string set_name; // 0x90
}
