// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFriendSupportCardInfo>))]
public class SingleModeFriendSupportCardInfo
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("support_card_id")] public int support_card_id; // 0x18
    [Key("position")] public int position; // 0x1C
}
