// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenDigInfo>))]
public class SingleModeOnsenDigInfo
{
    [Key("stratum_id")] public int stratum_id; // 0x10
    [Key("dig_value")] public int dig_value; // 0x14
}
