// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSportLoadResponse>))]
public class SingleModeSportLoadResponse : ResponseCommon
{
    [Key("data")] public SingleModeSportLoadResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSportLoadResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_load_common")] public SingleModeLoadCommon single_mode_load_common; // 0x10
        [Key("sport_data_set")] public SingleModeSportDataSet sport_data_set; // 0x18
    }
}
