// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSportUseItemRequest>))]
public class SingleModeSportUseItemRequest : RequestBase<SingleModeSportUseItemResponse>
{
    [Key("item_id")] public int item_id; // 0x88
    [Key("select_id_1")] public int select_id_1; // 0x8C
    [Key("select_id_2")] public int select_id_2; // 0x90
    [Key("select_id_3")] public int select_id_3; // 0x94
    [Key("current_num")] public int current_num; // 0x98
    [Key("current_turn")] public int current_turn; // 0x9C
}
