// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusChangeRunningStyleResponse>))]
public class SingleModeVenusChangeRunningStyleResponse : ResponseCommon
{
    [Key("data")] public SingleModeVenusChangeRunningStyleResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusChangeRunningStyleResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
