// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRaceRandomProgram>))]
public class SingleModeRaceRandomProgram
{
    [Key("turn")] public int turn; // 0x10
    [Key("program_id")] public int program_id; // 0x14
}
