// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLiveSaveSkillFilterSetResponse>))]
public class SingleModeLiveSaveSkillFilterSetResponse : ResponseCommon
{
    [Key("data")] public SingleModeLiveSaveSkillFilterSetResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLiveSaveSkillFilterSetResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
