// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamRaceEndRequest>))]
public class SingleModeTeamRaceEndRequest : RequestBase<SingleModeTeamRaceEndResponse>
{
    [Key("single_mode_race_end_request_common")] public SingleModeRaceEndRequestCommon single_mode_race_end_request_common; // 0x88
}
