// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenGainSkillsResponse>))]
public class SingleModeOnsenGainSkillsResponse : ResponseCommon
{
    [Key("data")] public SingleModeOnsenGainSkillsResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenGainSkillsResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x18
        [Key("onsen_data_set")] public SingleModeOnsenDataSet onsen_data_set; // 0x20
    }
}
