// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeResultDifficultyDataSet>))]
public class SingleModeResultDifficultyDataSet
{
    [Key("single_mode_difficulty_info_array")] public SingleModeDifficultyInfo[] single_mode_difficulty_info_array; // 0x10
    [Key("type1_reward_info")] public RewardSummaryInfo type1_reward_info; // 0x18
    [Key("type2_reward_info")] public RewardSummaryInfo type2_reward_info; // 0x20
    [Key("box_reward_array")] public SingleModeResultDifficultyBox[] box_reward_array; // 0x28
    [Key("single_reward_array")] public DisplayRewardInfo[] single_reward_array; // 0x30
    [Key("is_boost")] public int is_boost; // 0x38
}
