// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcArcRaceEndResponse>))]
public class SingleModeArcArcRaceEndResponse : ResponseCommon
{
    [Key("data")] public SingleModeArcArcRaceEndResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcArcRaceEndResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x18
        [Key("race_add_reward_info")] public SingleModeRaceAddRewardInfo[] race_add_reward_info; // 0x20
        [Key("win_saddle_id_array")] public int[] win_saddle_id_array; // 0x28
        [Key("race_reward_info")] public CharaRaceReward race_reward_info; // 0x30
        [Key("arc_data_set")] public SingleModeArcDataSet arc_data_set; // 0x38
    }
}
