// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegend9047BonusInfo>))]
public class SingleModeLegend9047BonusInfo
{
    [Key("continuation_zone_count")] public int continuation_zone_count; // 0x10
    [Key("current_step_count")] public int current_step_count; // 0x14
    [Key("zone_end_rate_array")] public SingleModeLegend9047EndRateInfo[] zone_end_rate_array; // 0x18
    [Key("is_zone_end")] public bool is_zone_end; // 0x20
}
