// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFinishRequestCommon>))]
public class SingleModeFinishRequestCommon
{
    [Key("is_force_delete")] public bool is_force_delete; // 0x10
    [Key("factor_lottery_id")] public int factor_lottery_id; // 0x14
    [Key("current_turn")] public int current_turn; // 0x18
}
