// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenMultiRaceReserveResponse>))]
public class SingleModeRamenMultiRaceReserveResponse : ResponseCommon
{
    [Key("data")] public SingleModeRamenMultiRaceReserveResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenMultiRaceReserveResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("reserved_race_info")] public SingleModeReservedRaceInfo reserved_race_info; // 0x10
    }
}
