// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCheckEventRequestCommon>))]
public class SingleModeCheckEventRequestCommon
{
    [Key("event_id")] public int event_id; // 0x10
    [Key("chara_id")] public int chara_id; // 0x14
    [Key("choice_number")] public int choice_number; // 0x18
    [Key("current_turn")] public int current_turn; // 0x1C
    [Key("exec_auto_play_plan_id")] public int exec_auto_play_plan_id; // 0x20
}
