// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeReservedRaceDeck>))]
public class SingleModeReservedRaceDeck
{
    [Key("deck_num")] public int deck_num; // 0x10
    [Key("deck_name")] public string deck_name; // 0x18
    [Key("race_array")] public SingleModeReservedRace[] race_array; // 0x20
}
