// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamFactorRelotteryEndResponse>))]
public class SingleModeTeamFactorRelotteryEndResponse : ResponseCommon
{
    [Key("data")] public SingleModeTeamFactorRelotteryEndResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamFactorRelotteryEndResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
