// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeAutoPlaySaveCustomPlanResponse>))]
public class SingleModeAutoPlaySaveCustomPlanResponse : ResponseCommon
{
    [Key("data")] public SingleModeAutoPlaySaveCustomPlanResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeAutoPlaySaveCustomPlanResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
