// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeVenusFinishClawCraneRequest>))]
public class SingleModeVenusFinishClawCraneRequest : RequestBase<SingleModeVenusFinishClawCraneResponse>
{
    [Key("single_mode_finish_claw_crane_request_common")] public SingleModeFinishClawCraneRequestCommon single_mode_finish_claw_crane_request_common; // 0x88
}
