// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeAutoPlaySavePlanDescriptionRequest>))]
public class SingleModeAutoPlaySavePlanDescriptionRequest : RequestBase<SingleModeAutoPlaySavePlanDescriptionResponse>
{
    [Key("plan_id")] public int plan_id; // 0x88
    [Key("plan_description")] public string plan_description; // 0x90
}
