// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenDataSetStart>))]
public class SingleModeRamenDataSetStart
{
    [Key("auto_select_info")] public SingleModeRamenAutoSelectInfo auto_select_info; // 0x10
    [Key("auto_select_set_info")] public SingleModeRamenAutoSelectSetInfo[] auto_select_set_info; // 0x18
    [Key("is_checked_uraf_event")] public int is_checked_uraf_event; // 0x20
}
