// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendFactorLotteryResponse>))]
public class SingleModeLegendFactorLotteryResponse : ResponseCommon
{
    [Key("data")] public SingleModeLegendFactorLotteryResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendFactorLotteryResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_factor_lottery_common")] public SingleModeFactorLotteryCommon single_mode_factor_lottery_common; // 0x10
    }
}
