// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFinishClawCraneRequestCommon>))]
public class SingleModeFinishClawCraneRequestCommon
{
    [Key("plushies")] public Plushie[] plushies; // 0x10
    [Key("current_turn")] public int current_turn; // 0x18
}
