// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenTrainingExecInfo>))]
public class SingleModeRamenTrainingExecInfo
{
    [Key("base_command_id")] public int base_command_id; // 0x10
    [Key("exec_count")] public int exec_count; // 0x14
}
