// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLoadResponse>))]
public class SingleModeLoadResponse : ResponseCommon
{
    [Key("data")] public SingleModeLoadResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLoadResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_load_common")] public SingleModeLoadCommon single_mode_load_common; // 0x10
        [Key("ura_data_set")] public SingleModeUraDataSet ura_data_set; // 0x18
    }
}
