// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenSaveSkillFilterSetResponse>))]
public class SingleModeRamenSaveSkillFilterSetResponse : ResponseCommon
{
    [Key("data")] public SingleModeRamenSaveSkillFilterSetResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRamenSaveSkillFilterSetResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
