// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSaveSkillFilterSetResponse>))]
public class SingleModeSaveSkillFilterSetResponse : ResponseCommon
{
    [Key("data")] public SingleModeSaveSkillFilterSetResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSaveSkillFilterSetResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
