// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcCommandInfo>))]
public class SingleModeArcCommandInfo
{
    [Key("command_type")] public int command_type; // 0x10
    [Key("command_id")] public int command_id; // 0x14
    [Key("params_inc_dec_info_array")] public SingleModeParamsIncDecInfo[] params_inc_dec_info_array; // 0x18
    [Key("add_global_exp")] public int add_global_exp; // 0x20
}
