// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCharaInfo>))]
public class SingleModeCharaInfo
{
    [Key("trained_chara_id")] public int trained_chara_id; // 0x10
    [Key("program_id")] public int program_id; // 0x14
    [Key("sense_bonus_ids")] public int[] sense_bonus_ids; // 0x18
    [Key("exec_commands")] public SingleModeExecCommand[] exec_commands; // 0x20
}
