// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeBreedersEnhanceGroup>))]
public class SingleModeBreedersEnhanceGroup
{
    [Key("group_type")] public int group_type; // 0x10
    [Key("level")] public int level; // 0x14
}
