// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendLegendRaceEndResponse>))]
public class SingleModeLegendLegendRaceEndResponse : ResponseCommon
{
    [Key("data")] public SingleModeLegendLegendRaceEndResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendLegendRaceEndResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x18
        [Key("race_add_reward_info")] public SingleModeRaceAddRewardInfo[] race_add_reward_info; // 0x20
        [Key("win_saddle_id_array")] public int[] win_saddle_id_array; // 0x28
        [Key("race_reward_info")] public CharaRaceReward race_reward_info; // 0x30
        [Key("add_trophy_info")] public LoginUserTrophyInfo add_trophy_info; // 0x38
        [Key("trophy_reward_info")] public RaceRewardData trophy_reward_info; // 0x40
        [Key("legend_data_set")] public SingleModeLegendDataSet legend_data_set; // 0x48
        [Key("add_music")] public UserMusic add_music; // 0x50
        [Key("race_history")] public SingleRaceHistory[] race_history; // 0x58
    }
}
