// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerPriorityFacility>))]
public class SingleModePioneerPriorityFacility
{
    [Key("priority")] public int priority; // 0x10
    [Key("facility_state_id")] public int facility_state_id; // 0x14
}
