// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamOpponentListResponse>))]
public class SingleModeTeamOpponentListResponse : ResponseCommon
{
    [Key("data")] public SingleModeTeamOpponentListResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamOpponentListResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("team_data_set")] public SingleModeTeamDataSet team_data_set; // 0x10
    }
}
