// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcFactorOrderLoadResponse>))]
public class SingleModeArcFactorOrderLoadResponse : ResponseCommon
{
    [Key("data")] public SingleModeArcFactorOrderLoadResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcFactorOrderLoadResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_factor_order_load_common")] public SingleModeFactorOrderLoadCommon single_mode_factor_order_load_common; // 0x10
    }
}
