// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendPopularityInfo>))]
public class SingleModeLegendPopularityInfo
{
    [Key("popularity_type")] public int popularity_type; // 0x10
    [Key("poster_catchphrase_id")] public int poster_catchphrase_id; // 0x14
    [Key("poster_race_result_info")] public RaceResultInfo poster_race_result_info; // 0x18
    [Key("advertisement_legend_id")] public int advertisement_legend_id; // 0x20
}
