// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamFrameOrder>))]
public class SingleModeTeamFrameOrder
{
    [Key("distance_type")] public int distance_type; // 0x10
    [Key("race_order")] public int race_order; // 0x14
    [Key("random_info_array")] public SingleModeTeamRandomInfo[] random_info_array; // 0x18
}
