// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendGainSkillsResponse>))]
public class SingleModeLegendGainSkillsResponse : ResponseCommon
{
    [Key("data")] public SingleModeLegendGainSkillsResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendGainSkillsResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x18
        [Key("legend_data_set")] public SingleModeLegendDataSet legend_data_set; // 0x20
    }
}
