// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeAutoPlaySelectPlanResponse>))]
public class SingleModeAutoPlaySelectPlanResponse : ResponseCommon
{
    [Key("data")] public SingleModeAutoPlaySelectPlanResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeAutoPlaySelectPlanResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
