// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFreeCheckEventRequest>))]
public class SingleModeFreeCheckEventRequest : RequestBase<SingleModeFreeCheckEventResponse>
{
    [Key("single_mode_check_event_request_common")] public SingleModeCheckEventRequestCommon single_mode_check_event_request_common; // 0x88
}
