// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCookEvaluationInfo>))]
public class SingleModeCookEvaluationInfo
{
    [Key("target_id")] public int target_id; // 0x10
    [Key("chara_id")] public int chara_id; // 0x14
    [Key("is_cooking_friend")] public int is_cooking_friend; // 0x18
    [Key("cooking_value")] public int cooking_value; // 0x1C
}
