// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerSaveSkillFilterSetResponse>))]
public class SingleModePioneerSaveSkillFilterSetResponse : ResponseCommon
{
    [Key("data")] public SingleModePioneerSaveSkillFilterSetResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerSaveSkillFilterSetResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
