// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModePioneerFacilityInfo>))]
public class SingleModePioneerFacilityInfo
{
    [Key("facility_id")] public int facility_id; // 0x10
    [Key("state_id")] public int state_id; // 0x14
}
