// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFreeMultiItemExchangeResponse>))]
public class SingleModeFreeMultiItemExchangeResponse : ResponseCommon
{
    [Key("data")] public SingleModeFreeMultiItemExchangeResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFreeMultiItemExchangeResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x18
        [Key("free_data_set")] public SingleModeFreeDataSet free_data_set; // 0x20
    }
}
