// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendPopularityEndResponse>))]
public class SingleModeLegendPopularityEndResponse : ResponseCommon
{
    [Key("data")] public SingleModeLegendPopularityEndResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendPopularityEndResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x18
        [Key("unchecked_event_array")] public SingleModeEventInfo[] unchecked_event_array; // 0x20
        [Key("legend_data_set")] public SingleModeLegendDataSet legend_data_set; // 0x28
    }
}
