// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamTeamRaceEndOutResponse>))]
public class SingleModeTeamTeamRaceEndOutResponse : ResponseCommon
{
    [Key("data")] public SingleModeTeamTeamRaceEndOutResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeTeamTeamRaceEndOutResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("team_data_set")] public SingleModeTeamDataSet team_data_set; // 0x18
        [Key("add_music")] public UserMusic add_music; // 0x20
        [Key("tmp_team_rank")] public int tmp_team_rank; // 0x28
        [Key("unchecked_event_array")] public SingleModeEventInfo[] unchecked_event_array; // 0x30
    }
}
