// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLiveSaveSkillFilterSetRequest>))]
public class SingleModeLiveSaveSkillFilterSetRequest : RequestBase<SingleModeLiveSaveSkillFilterSetResponse>
{
    [Key("setting_array")] public SingleModeSkillFilterSet[] setting_array; // 0x88
}
