// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendNotDownParameterInfo>))]
public class SingleModeLegendNotDownParameterInfo
{
    [Key("friend_partner_id_array")] public int[] friend_partner_id_array; // 0x10
    [Key("param_guard_array")] public SingleModeLegendParamGuardInfo[] param_guard_array; // 0x18
    [Key("bad_condition_guard_array")] public SingleModeLegendBadConditionGuardInfo[] bad_condition_guard_array; // 0x20
}
