// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeStartChara>))]
public class SingleModeStartChara
{
    [Key("card_id")] public int card_id; // 0x10
    [Key("support_card_ids")] public int[] support_card_ids; // 0x18
    [Key("friend_support_card_info")] public SingleModeFriendSupportCardInfo friend_support_card_info; // 0x20
    [Key("succession_trained_chara_id_1")] public int succession_trained_chara_id_1; // 0x28
    [Key("succession_trained_chara_id_2")] public int succession_trained_chara_id_2; // 0x2C
    [Key("rental_succession_trained_chara")] public SingleModeRentalSuccessionChara rental_succession_trained_chara; // 0x30
    [Key("scenario_id")] public int scenario_id; // 0x38
    [Key("selected_difficulty_info")] public SingleModeSelectedDifficultyInfo selected_difficulty_info; // 0x40
    [Key("select_deck_id")] public int select_deck_id; // 0x48
    [Key("boost_story_event_id")] public int boost_story_event_id; // 0x4C
    [Key("boost_factor_research_event_id")] public int boost_factor_research_event_id; // 0x50
    [Key("training_challenge_mode")] public int training_challenge_mode; // 0x54
    [Key("campaign_rental_support_card_id_array")] public int[] campaign_rental_support_card_id_array; // 0x58
    [Key("rental_deck_id")] public int rental_deck_id; // 0x60
    [Key("request_campaign_id_array")] public int[] request_campaign_id_array; // 0x68
    [Key("running_style")] public int running_style; // 0x70
}
