// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaRaceOutRequest>))]
public class SingleModeMechaRaceOutRequest : RequestBase<SingleModeMechaRaceOutResponse>
{
    [Key("single_mode_race_out_request_common")] public SingleModeRaceOutRequestCommon single_mode_race_out_request_common; // 0x88
}
