// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendFinishRequest>))]
public class SingleModeLegendFinishRequest : RequestBase<SingleModeLegendFinishResponse>
{
    [Key("single_mode_finish_request_common")] public SingleModeFinishRequestCommon single_mode_finish_request_common; // 0x88
}
