// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFreeSaveSkillFilterSetResponse>))]
public class SingleModeFreeSaveSkillFilterSetResponse : ResponseCommon
{
    [Key("data")] public SingleModeFreeSaveSkillFilterSetResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeFreeSaveSkillFilterSetResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
