// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSportFactorReloadResponse>))]
public class SingleModeSportFactorReloadResponse : ResponseCommon
{
    [Key("data")] public SingleModeSportFactorReloadResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSportFactorReloadResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("single_mode_factor_lottery_common")] public SingleModeFactorLotteryCommon single_mode_factor_lottery_common; // 0x10
    }
}
