// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeMechaContinueRequest>))]
public class SingleModeMechaContinueRequest : RequestBase<SingleModeMechaContinueResponse>
{
    [Key("single_mode_continue_request_common")] public SingleModeContinueRequestCommon single_mode_continue_request_common; // 0x88
}
