// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcGainSkillsResponse>))]
public class SingleModeArcGainSkillsResponse : ResponseCommon
{
    [Key("data")] public SingleModeArcGainSkillsResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcGainSkillsResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x18
        [Key("arc_data_set")] public SingleModeArcDataSet arc_data_set; // 0x20
    }
}
