// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRentalSuccessionChara>))]
public class SingleModeRentalSuccessionChara
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("trained_chara_id")] public int trained_chara_id; // 0x18
    [Key("is_circle_member")] public bool is_circle_member; // 0x1C
    [Key("is_event_rental")] public bool is_event_rental; // 0x1D
}
