// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeSkillUpgrade>))]
public class SingleModeSkillUpgrade
{
    [Key("condition_id")] public int condition_id; // 0x10
    [Key("total_count")] public int total_count; // 0x14
    [Key("current_count")] public int current_count; // 0x18
}
