// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeOnsenChangeShortCutRequest>))]
public class SingleModeOnsenChangeShortCutRequest : RequestBase<SingleModeOnsenChangeShortCutResponse>
{
    [Key("single_mode_change_short_cut_request_common")] public SingleModeChangeShortCutRequestCommon single_mode_change_short_cut_request_common; // 0x88
}
