// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLegendEffectedBuff>))]
public class SingleModeLegendEffectedBuff
{
    [Key("buff_id")] public int buff_id; // 0x10
    [Key("remain_count")] public int remain_count; // 0x14
}
