// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeDifficultyInfo>))]
public class SingleModeDifficultyInfo
{
    [Key("difficulty_id")] public int difficulty_id; // 0x10
    [Key("open_difficulty_index")] public int open_difficulty_index; // 0x14
    [Key("item_num")] public int item_num; // 0x18
    [Key("box_id")] public int box_id; // 0x1C
    [Key("box_item_num")] public int box_item_num; // 0x20
    [Key("gacha_gauge")] public int gacha_gauge; // 0x24
    [Key("box_info_array")] public SingleModeDifficultyBoxInfo[] box_info_array; // 0x28
}
