// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcPotentialLevelUpRequest>))]
public class SingleModeArcPotentialLevelUpRequest : RequestBase<SingleModeArcPotentialLevelUpResponse>
{
    [Key("potential_level_up_info_array")] public PotentialLevelUpInfo[] potential_level_up_info_array; // 0x88
    [Key("current_turn")] public int current_turn; // 0x90
}
