// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeRaceEndRequestCommon>))]
public class SingleModeRaceEndRequestCommon
{
    [Key("current_turn")] public int current_turn; // 0x10
    [Key("exec_auto_play_plan_id")] public int exec_auto_play_plan_id; // 0x14
}
