// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeLiveFactorSelectRequest>))]
public class SingleModeLiveFactorSelectRequest : RequestBase<SingleModeLiveFactorSelectResponse>
{
    [Key("single_mode_factor_select_request_common")] public SingleModeFactorSelectRequestCommon single_mode_factor_select_request_common; // 0x88
}
