// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeArcGetChoiceRewardRequest>))]
public class SingleModeArcGetChoiceRewardRequest : RequestBase<SingleModeArcGetChoiceRewardResponse>
{
    [Key("event_id")] public int event_id; // 0x88
}
