// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCheckEventResponse>))]
public class SingleModeCheckEventResponse : ResponseCommon
{
    [Key("data")] public SingleModeCheckEventResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SingleModeCheckEventResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("chara_info")] public SingleModeChara chara_info; // 0x10
        [Key("gain_parameter_info")] public SingleModeGainParameterInfo gain_parameter_info; // 0x18
        [Key("not_up_parameter_info")] public NotUpParameterInfo not_up_parameter_info; // 0x20
        [Key("not_down_parameter_info")] public NotDownParameterInfo not_down_parameter_info; // 0x28
        [Key("gain_partner_support_effect_array")] public GainPartnerSupportEffect[] gain_partner_support_effect_array; // 0x30
        [Key("home_info")] public SingleModeHomeInfo home_info; // 0x38
        [Key("unchecked_event_array")] public SingleModeEventInfo[] unchecked_event_array; // 0x40
        [Key("event_effected_factor_array")] public SuccessionEffectedFactor[] event_effected_factor_array; // 0x48
        [Key("race_condition_array")] public SingleModeRaceCondition[] race_condition_array; // 0x50
        [Key("race_start_info")] public SingleRaceStartInfo race_start_info; // 0x58
        [Key("race_running_style")] public int race_running_style; // 0x60
        [Key("ura_data_set")] public SingleModeUraDataSet ura_data_set; // 0x68
        [Key("select_index_info_array")] public SingleModeSelectIndexInfo[] select_index_info_array; // 0x70
    }
}
