// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<StartDashExchangePayment>))]
public class StartDashExchangePayment
{
    [Key("product_master_id")] public int product_master_id; // 0x10
    [Key("lineup_time")] public string lineup_time; // 0x18
}
