// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<StoryEventRouletteChangeSheetResponse>))]
public class StoryEventRouletteChangeSheetResponse : ResponseCommon
{
    [Key("data")] public StoryEventRouletteChangeSheetResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<StoryEventRouletteChangeSheetResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("change_sheet_num")] public int change_sheet_num; // 0x10
        [Key("change_roulette_reward_list")] public StoryEventRouletteReward[] change_roulette_reward_list; // 0x18
    }
}
