// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<StoryEventAddPointSummary>))]
public class StoryEventAddPointSummary
{
    [Key("total")] public int total; // 0x10
    [Key("rank_score")] public int rank_score; // 0x14
    [Key("nickname_bonus")] public int nickname_bonus; // 0x18
    [Key("card_bonus")] public int card_bonus; // 0x1C
    [Key("support_card_bonus")] public int support_card_bonus; // 0x20
    [Key("win_num_bonus")] public int win_num_bonus; // 0x24
}
