// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<StoryEventUserInfo>))]
public class StoryEventUserInfo
{
    [Key("event_point")] public int event_point; // 0x10
    [Key("roulette_coin_num")] public int roulette_coin_num; // 0x14
    [Key("roulette_sheet_num")] public int roulette_sheet_num; // 0x18
}
