// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<StoryEventUseStoryEventShioriRequest>))]
public class StoryEventUseStoryEventShioriRequest : RequestBase<StoryEventUseStoryEventShioriResponse>
{
    [Key("story_event_id")] public int story_event_id; // 0x88
}
