// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<StoryEventAnnounceResponse>))]
public class StoryEventAnnounceResponse : ResponseCommon
{
    [Key("data")] public StoryEventAnnounceResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<StoryEventAnnounceResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("content")] public string content; // 0x10
    }
}
