// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SuccessionGainInfo>))]
public class SuccessionGainInfo
{
    [Key("lottery_id")] public int lottery_id; // 0x10
    [Key("speed")] public int speed; // 0x14
    [Key("stamina")] public int stamina; // 0x18
    [Key("power")] public int power; // 0x1C
    [Key("wiz")] public int wiz; // 0x20
    [Key("guts")] public int guts; // 0x24
    [Key("vital")] public int vital; // 0x28
    [Key("max_speed")] public int max_speed; // 0x2C
    [Key("max_stamina")] public int max_stamina; // 0x30
    [Key("max_power")] public int max_power; // 0x34
    [Key("max_wiz")] public int max_wiz; // 0x38
    [Key("max_guts")] public int max_guts; // 0x3C
    [Key("skill_tips_array")] public SkillTips[] skill_tips_array; // 0x40
    [Key("proper_distance_short")] public int proper_distance_short; // 0x48
    [Key("proper_distance_mile")] public int proper_distance_mile; // 0x4C
    [Key("proper_distance_middle")] public int proper_distance_middle; // 0x50
    [Key("proper_distance_long")] public int proper_distance_long; // 0x54
    [Key("proper_running_style_nige")] public int proper_running_style_nige; // 0x58
    [Key("proper_running_style_senko")] public int proper_running_style_senko; // 0x5C
    [Key("proper_running_style_sashi")] public int proper_running_style_sashi; // 0x60
    [Key("proper_running_style_oikomi")] public int proper_running_style_oikomi; // 0x64
    [Key("proper_ground_turf")] public int proper_ground_turf; // 0x68
    [Key("proper_ground_dirt")] public int proper_ground_dirt; // 0x6C
    [Key("skill_point")] public int skill_point; // 0x70
    [Key("effected_factor_array")] public SuccessionEffectedFactor[] effected_factor_array; // 0x78
}
