// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SuccessionEffectedFactor>))]
public class SuccessionEffectedFactor
{
    [Key("position")] public int position; // 0x10
    [Key("factor_info_array")] public FactorInfo[] factor_info_array; // 0x18
}
