// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SuccessionHistory>))]
public class SuccessionHistory
{
    [Key("id")] public int id; // 0x10
    [Key("viewer_id")] public long viewer_id; // 0x18
    [Key("trained_chara_id")] public int trained_chara_id; // 0x20
    [Key("history_type")] public int history_type; // 0x24
    [Key("succession_card_id")] public int succession_card_id; // 0x28
    [Key("date")] public int date; // 0x2C
    [Key("user_name")] public string user_name; // 0x30
    [Key("circle_name")] public string circle_name; // 0x38
}
