// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SuccessionDeckChara>))]
public class SuccessionDeckChara
{
    [Key("succession_trained_chara_id")] public int succession_trained_chara_id; // 0x10
    [Key("succession_trained_chara")] public TrainedChara succession_trained_chara; // 0x18
    [Key("user_info_at_friend")] public UserInfoAtFriend user_info_at_friend; // 0x20
    [Key("is_event_rental")] public bool is_event_rental; // 0x28
}
