// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardGetSupportCardEventSkillRequest>))]
public class SupportCardGetSupportCardEventSkillRequest : RequestBase<SupportCardGetSupportCardEventSkillResponse>
{
    [Key("support_card_id")] public int support_card_id; // 0x88
}
