// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardGetBySkillResponse>))]
public class SupportCardGetBySkillResponse : ResponseCommon
{
    [Key("data")] public SupportCardGetBySkillResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardGetBySkillResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("support_card_id_array")] public int[] support_card_id_array; // 0x10
    }
}
