// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardLimitBreakItemResponse>))]
public class SupportCardLimitBreakItemResponse : ResponseCommon
{
    [Key("data")] public SupportCardLimitBreakItemResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardLimitBreakItemResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("support_card_data")] public UserSupportCard support_card_data; // 0x10
        [Key("item_data_array")] public UserItem[] item_data_array; // 0x18
    }
}
