// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardLimitBreakItemRequest>))]
public class SupportCardLimitBreakItemRequest : RequestBase<SupportCardLimitBreakItemResponse>
{
    [Key("support_card_id")] public int support_card_id; // 0x88
    [Key("limit_break_item_id")] public int limit_break_item_id; // 0x8C
    [Key("limit_break_count")] public int limit_break_count; // 0x90
}
