// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardDeckChangePartyResponse>))]
public class SupportCardDeckChangePartyResponse : ResponseCommon
{
    [Key("data")] public SupportCardDeckChangePartyResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardDeckChangePartyResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("support_card_deck_array")] public UserSupportCardDeck[] support_card_deck_array; // 0x10
        [Key("rental_deck_info")] public RentalDeckInfo rental_deck_info; // 0x18
    }
}
