// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardSellRequest>))]
public class SupportCardSellRequest : RequestBase<SupportCardSellResponse>
{
    [Key("sell_support_card_info_array")] public SellSupportCardInfo[] sell_support_card_info_array; // 0x88
}
