// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingRaceStartResponse>))]
public class TeamBuildingRaceStartResponse : ResponseCommon
{
    [Key("data")] public TeamBuildingRaceStartResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingRaceStartResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("race_scenario")] public string race_scenario; // 0x10
        [Key("state")] public int state; // 0x18
    }
}
