// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingChangeTeamNameResponse>))]
public class TeamBuildingChangeTeamNameResponse : ResponseCommon
{
    [Key("data")] public TeamBuildingChangeTeamNameResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingChangeTeamNameResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("name")] public string name; // 0x10
    }
}
