// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingSaveCollectionRequest>))]
public class TeamBuildingSaveCollectionRequest : RequestBase<TeamBuildingSaveCollectionResponse>
{
    [Key("check_chara_flag")] public int check_chara_flag; // 0x88
    [Key("check_skill_flag")] public int check_skill_flag; // 0x8C
}
