// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamStadiumStartRequest>))]
public class TeamStadiumStartRequest : RequestBase<TeamStadiumStartResponse>
{
    [Key("item_id_array")] public int[] item_id_array; // 0x88
}
