// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingEntryChara>))]
public class TeamBuildingEntryChara
{
    [Key("member_id")] public int member_id; // 0x10
    [Key("trained_chara")] public TrainedChara trained_chara; // 0x18
    [Key("mob_chara")] public EntryMobChara mob_chara; // 0x20
}
