// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamStadiumRaceResult>))]
public class TeamStadiumRaceResult
{
    [Key("distance_type")] public int distance_type; // 0x10
    [Key("race_scenario")] public string race_scenario; // 0x18
    [Key("round")] public int round; // 0x20
    [Key("team_score_array")] public TeamStadiumResultScoreData[] team_score_array; // 0x28
    [Key("team_total_score")] public int team_total_score; // 0x30
    [Key("win_type")] public int win_type; // 0x34
    [Key("current_consecutive_win_count")] public int current_consecutive_win_count; // 0x38
    [Key("bonus_rate_by_next_win")] public int bonus_rate_by_next_win; // 0x3C
    [Key("chara_result_array")] public TeamStadiumRaceCharaResult[] chara_result_array; // 0x40
}
