// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingScoutRankUser>))]
public class TeamBuildingScoutRankUser
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("name")] public string name; // 0x18
    [Key("rank")] public int rank; // 0x20
    [Key("count")] public int count; // 0x24
    [Key("trained_chara")] public TrainedChara trained_chara; // 0x28
}
