// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingRaceResultResponse>))]
public class TeamBuildingRaceResultResponse : ResponseCommon
{
    [Key("data")] public TeamBuildingRaceResultResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingRaceResultResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("race_rotation_info")] public RaceRotationInfo race_rotation_info; // 0x10
        [Key("team_score")] public int team_score; // 0x18
        [Key("scout_point_info")] public TeamBuildingScoutPointInfo scout_point_info; // 0x20
        [Key("basic_reward_array")] public ResponseItem[] basic_reward_array; // 0x28
        [Key("win_reward_array")] public ResponseItem[] win_reward_array; // 0x30
        [Key("super_special_reward_array")] public ResponseItem[] super_special_reward_array; // 0x38
        [Key("team_score_reward_array")] public ResponseItem[] team_score_reward_array; // 0x40
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x48
        [Key("add_collection_chara_array")] public TeamBuildingCollectionChara[] add_collection_chara_array; // 0x50
        [Key("add_collection_group_id_array")] public int[] add_collection_group_id_array; // 0x58
        [Key("state")] public int state; // 0x60
    }
}
