// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingRaceEntryResponse>))]
public class TeamBuildingRaceEntryResponse : ResponseCommon
{
    [Key("data")] public TeamBuildingRaceEntryResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingRaceEntryResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("race_horse_data_array")] public RaceHorseData[] race_horse_data_array; // 0x10
        [Key("item_info_array")] public UserItem[] item_info_array; // 0x18
        [Key("random_seed")] public int random_seed; // 0x20
        [Key("state")] public int state; // 0x24
    }
}
