// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingChangeTeamNameRequest>))]
public class TeamBuildingChangeTeamNameRequest : RequestBase<TeamBuildingChangeTeamNameResponse>
{
    [Key("name")] public string name; // 0x88
}
