// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingChangeRunningStyleRequest>))]
public class TeamBuildingChangeRunningStyleRequest : RequestBase<TeamBuildingChangeRunningStyleResponse>
{
    [Key("running_style_info_array")] public TeamBuildingRunningStyleInfo[] running_style_info_array; // 0x88
}
