// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingEntryCharaSpecial>))]
public class TeamBuildingEntryCharaSpecial
{
    [Key("member_id")] public int member_id; // 0x10
    [Key("mob_chara")] public EntryMobChara mob_chara; // 0x18
    [Key("special_buff")] public TeamBuildingSpecialBuff special_buff; // 0x20
}
