// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamStadiumReplayCheckResponse>))]
public class TeamStadiumReplayCheckResponse : ResponseCommon
{
    [Key("data")] public TeamStadiumReplayCheckResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamStadiumReplayCheckResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("last_checked_round")] public int last_checked_round; // 0x10
    }
}
