// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingOpponentArrayResponse>))]
public class TeamBuildingOpponentArrayResponse : ResponseCommon
{
    [Key("data")] public TeamBuildingOpponentArrayResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingOpponentArrayResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("opponent_array")] public TeamBuidingTeamInfo[] opponent_array; // 0x10
        [Key("expectation_scout_point_array")] public TeamBuildingExpectationScoutPointInfo[] expectation_scout_point_array; // 0x18
    }
}
