// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingMakeTeamRequest>))]
public class TeamBuildingMakeTeamRequest : RequestBase<TeamBuildingMakeTeamResponse>
{
    [Key("trained_chara_id")] public int trained_chara_id; // 0x88
    [Key("running_style")] public int running_style; // 0x8C
    [Key("name")] public string name; // 0x90
}
