// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingTeamInfoSpecial>))]
public class TeamBuildingTeamInfoSpecial
{
    [Key("team_id")] public int team_id; // 0x10
    [Key("viewer_id")] public long viewer_id; // 0x18
    [Key("user_name")] public string user_name; // 0x20
    [Key("honor_data")] public HonorData honor_data; // 0x28
    [Key("team_name")] public string team_name; // 0x30
    [Key("team_score")] public int team_score; // 0x38
    [Key("entry_chara_special_array")] public TeamBuildingEntryCharaSpecial[] entry_chara_special_array; // 0x40
}
