// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamStadiumDispChara>))]
public class TeamStadiumDispChara
{
    [Key("card_id")] public int card_id; // 0x10
    [Key("rarity")] public int rarity; // 0x14
    [Key("distance_type")] public int distance_type; // 0x18
}
