// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamStadiumAllRaceEndResponse>))]
public class TeamStadiumAllRaceEndResponse : ResponseCommon
{
    [Key("data")] public TeamStadiumAllRaceEndResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamStadiumAllRaceEndResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("add_friend_point")] public int add_friend_point; // 0x10
        [Key("add_fan_info_array")] public TeamStadiumAddFanInfo[] add_fan_info_array; // 0x18
        [Key("add_love_point")] public int add_love_point; // 0x20
        [Key("add_trainer_medal")] public int add_trainer_medal; // 0x24
        [Key("update_user_chara_array")] public UserChara[] update_user_chara_array; // 0x28
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x30
        [Key("winning_reward_content_array")] public TeamStadiumWinningRewardContent[] winning_reward_content_array; // 0x38
        [Key("total_score_info")] public TeamStadiumTotalScoreInfo total_score_info; // 0x40
        [Key("final_win_type")] public int final_win_type; // 0x48
        [Key("is_update_high_score")] public int is_update_high_score; // 0x4C
        [Key("ranking_rank")] public int ranking_rank; // 0x50
        [Key("mvp_chara_id")] public int mvp_chara_id; // 0x54
        [Key("limited_shop_info")] public LimitedShopInfo limited_shop_info; // 0x58
        [Key("circle_point")] public ulong circle_point; // 0x60
        [Key("new_chara_profile_array")] public CharaProfileData[] new_chara_profile_array; // 0x68
        [Key("ranking")] public TeamStadiumRanking ranking; // 0x70
        [Key("border_line")] public TeamStadiumBorderLine border_line; // 0x78
        [Key("campaign_id_array")] public int[] campaign_id_array; // 0x80
        [Key("campaign_walking_gauge_info")] public CampaignWalkingGaugeInfo campaign_walking_gauge_info; // 0x88
        [Key("map_event_gauge_info")] public CampaignWalkingGaugeInfo map_event_gauge_info; // 0x90
        [Key("factor_research_gauge_info")] public FactorResearchGaugeInfo factor_research_gauge_info; // 0x98
    }
}
