// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingScoutResponse>))]
public class TeamBuildingScoutResponse : ResponseCommon
{
    [Key("data")] public TeamBuildingScoutResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingScoutResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("reward_array")] public ResponseItem[] reward_array; // 0x10
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x18
        [Key("team_score")] public int team_score; // 0x20
        [Key("item_data_array")] public UserItem[] item_data_array; // 0x28
        [Key("state")] public int state; // 0x30
    }
}
