// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamStadiumUser>))]
public class TeamStadiumUser
{
    [Key("team_class")] public int team_class; // 0x10
    [Key("best_team_class")] public int best_team_class; // 0x14
    [Key("best_point")] public int best_point; // 0x18
}
