// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamStadiumTeamEditResponse>))]
public class TeamStadiumTeamEditResponse : ResponseCommon
{
    [Key("data")] public TeamStadiumTeamEditResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamStadiumTeamEditResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("reward_info_array")] public DisplayRewardInfo[] reward_info_array; // 0x10
        [Key("before_rank")] public int before_rank; // 0x18
        [Key("after_rank")] public int after_rank; // 0x1C
    }
}
