// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingIndexResponse>))]
public class TeamBuildingIndexResponse : ResponseCommon
{
    [Key("data")] public TeamBuildingIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TeamBuildingIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("own_team_info")] public TeamBuidingTeamInfo own_team_info; // 0x10
        [Key("race_rotation_info")] public RaceRotationInfo race_rotation_info; // 0x18
        [Key("item_info_array")] public UserItem[] item_info_array; // 0x20
        [Key("total_race_count")] public int total_race_count; // 0x28
        [Key("total_win_count")] public int total_win_count; // 0x2C
        [Key("straight_win_count")] public int straight_win_count; // 0x30
        [Key("best_team_score")] public int best_team_score; // 0x34
        [Key("state")] public int state; // 0x38
        [Key("purchase_ticket_num")] public int purchase_ticket_num; // 0x3C
        [Key("collection_chara_array")] public TeamBuildingCollectionChara[] collection_chara_array; // 0x40
        [Key("collection_group_id_array")] public int[] collection_group_id_array; // 0x48
        [Key("new_collection_group_id_array")] public int[] new_collection_group_id_array; // 0x50
        [Key("is_season_change")] public int is_season_change; // 0x58
        [Key("mission_badge_num")] public int mission_badge_num; // 0x5C
        [Key("daily_continue_num")] public int daily_continue_num; // 0x60
        [Key("scout_ranking_state")] public int scout_ranking_state; // 0x64
        [Key("special_race_info")] public TeamBuildingSpecialRaceInfo special_race_info; // 0x68
    }
}
