// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ToolStartSessionResponse>))]
public class ToolStartSessionResponse : ResponseCommon
{
    [Key("data")] public ToolStartSessionResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ToolStartSessionResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("is_tutorial")] public bool is_tutorial; // 0x10
        [Key("resource_version")] public string resource_version; // 0x18
        [Key("attest")] public bool attest; // 0x20
        [Key("nonce")] public string nonce; // 0x28
        [Key("terms_updated")] public bool terms_updated; // 0x30
        [Key("auth_key")] public string auth_key; // 0x38
    }
}
