// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ToolGetVerifyTokenResponse>))]
public class ToolGetVerifyTokenResponse : ResponseCommon
{
    [Key("data")] public ToolGetVerifyTokenResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ToolGetVerifyTokenResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("token")] public string token; // 0x10
    }
}
