// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ToolStartSessionRequest>))]
public class ToolStartSessionRequest : RequestBase<ToolStartSessionResponse>
{
    [Key("attestation_type")] public int attestation_type; // 0x88
}
