// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ToolDeviceAttestRequest>))]
public class ToolDeviceAttestRequest : RequestBase<ToolDeviceAttestResponse>
{
    [Key("credential")] public string credential; // 0x88
    [Key("error_code")] public int error_code; // 0x90
    [Key("error_message")] public string error_message; // 0x98
    [Key("attestation_type")] public int attestation_type; // 0xA0
}
