// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaChangeLockMultiRequest>))]
public class TrainedCharaChangeLockMultiRequest : RequestBase<TrainedCharaChangeLockMultiResponse>
{
    [Key("trained_chara_id_array")] public int[] trained_chara_id_array; // 0x88
    [Key("lock_flag")] public int lock_flag; // 0x90
    [Key("icon_type")] public int icon_type; // 0x94
}
