// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaChangeNicknameResponse>))]
public class TrainedCharaChangeNicknameResponse : ResponseCommon
{
    [Key("data")] public TrainedCharaChangeNicknameResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaChangeNicknameResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("trained_chara_info")] public TrainedChara trained_chara_info; // 0x10
    }
}
