// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaChangeLockMultiResponse>))]
public class TrainedCharaChangeLockMultiResponse : ResponseCommon
{
    [Key("data")] public TrainedCharaChangeLockMultiResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaChangeLockMultiResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
