// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaExtraCmPlayResponse>))]
public class TrainedCharaExtraCmPlayResponse : ResponseCommon
{
    [Key("data")] public TrainedCharaExtraCmPlayResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaExtraCmPlayResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("race_result_info")] public RaceResultInfo race_result_info; // 0x10
    }
}
