// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaGetSuccessionHistoryArrayResponse>))]
public class TrainedCharaGetSuccessionHistoryArrayResponse : ResponseCommon
{
    [Key("data")] public TrainedCharaGetSuccessionHistoryArrayResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaGetSuccessionHistoryArrayResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("succession_history_array")] public SuccessionHistory[] succession_history_array; // 0x10
    }
}
