// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedChara>))]
public class TrainedChara
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("trained_chara_id")] public int trained_chara_id; // 0x18
    [Key("owner_viewer_id")] public long owner_viewer_id; // 0x20
    [Key("owner_trained_chara_id")] public int owner_trained_chara_id; // 0x28
    [Key("use_type")] public int use_type; // 0x2C
    [Key("card_id")] public int card_id; // 0x30
    [Key("name")] public string name; // 0x38
    [Key("stamina")] public int stamina; // 0x40
    [Key("speed")] public int speed; // 0x44
    [Key("power")] public int power; // 0x48
    [Key("guts")] public int guts; // 0x4C
    [Key("wiz")] public int wiz; // 0x50
    [Key("fans")] public int fans; // 0x54
    [Key("rank_score")] public int rank_score; // 0x58
    [Key("rank")] public int rank; // 0x5C
    [Key("proper_distance_short")] public int proper_distance_short; // 0x60
    [Key("proper_distance_mile")] public int proper_distance_mile; // 0x64
    [Key("proper_distance_middle")] public int proper_distance_middle; // 0x68
    [Key("proper_distance_long")] public int proper_distance_long; // 0x6C
    [Key("proper_running_style_nige")] public int proper_running_style_nige; // 0x70
    [Key("proper_running_style_senko")] public int proper_running_style_senko; // 0x74
    [Key("proper_running_style_sashi")] public int proper_running_style_sashi; // 0x78
    [Key("proper_running_style_oikomi")] public int proper_running_style_oikomi; // 0x7C
    [Key("proper_ground_turf")] public int proper_ground_turf; // 0x80
    [Key("proper_ground_dirt")] public int proper_ground_dirt; // 0x84
    [Key("succession_num")] public int succession_num; // 0x88
    [Key("is_locked")] public int is_locked; // 0x8C
    [Key("rarity")] public int rarity; // 0x90
    [Key("talent_level")] public int talent_level; // 0x94
    [Key("chara_grade")] public int chara_grade; // 0x98
    [Key("running_style")] public int running_style; // 0x9C
    [Key("nickname_id")] public int nickname_id; // 0xA0
    [Key("wins")] public int wins; // 0xA4
    [Key("total_skill_pt")] public int total_skill_pt; // 0xA8
    [Key("skill_array")] public SkillData[] skill_array; // 0xB0
    [Key("support_card_list")] public TrainedCharaSupportCardList[] support_card_list; // 0xB8
    [Key("is_saved")] public int is_saved; // 0xC0
    [Key("race_result_list")] public TrainedCharaRaceResult[] race_result_list; // 0xC8
    [Key("win_saddle_id_array")] public int[] win_saddle_id_array; // 0xD0
    [Key("nickname_id_array")] public int[] nickname_id_array; // 0xD8
    [Key("factor_info_array")] public FactorInfo[] factor_info_array; // 0xE0
    [Key("factor_extend_array")] public FactorExtend[] factor_extend_array; // 0xE8
    [Key("succession_chara_array")] public SuccessionChara[] succession_chara_array; // 0xF0
    [Key("scenario_data_array")] public ScenarioData[] scenario_data_array; // 0xF8
    [Key("scenario_id")] public int scenario_id; // 0x100
    [Key("create_time")] public string create_time; // 0x108
}
