// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaExtraCmIndexResponse>))]
public class TrainedCharaExtraCmIndexResponse : ResponseCommon
{
    [Key("data")] public TrainedCharaExtraCmIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaExtraCmIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("extra_cm_index_info_array")] public ExtraCmIndexInfo[] extra_cm_index_info_array; // 0x10
        [Key("save_limit_num")] public int save_limit_num; // 0x18
    }
}
