// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaExtraCmPlayRequest>))]
public class TrainedCharaExtraCmPlayRequest : RequestBase<TrainedCharaExtraCmPlayResponse>
{
    [Key("trained_chara_id")] public int trained_chara_id; // 0x88
}
