// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaParam>))]
public class TrainedCharaParam
{
    [Key("skill")] public int[] skill; // 0x10
    [Key("stamina")] public int stamina; // 0x18
    [Key("speed")] public int speed; // 0x1C
    [Key("power")] public int power; // 0x20
    [Key("guts")] public int guts; // 0x24
    [Key("wiz")] public int wiz; // 0x28
}
