// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaRemoveResponse>))]
public class TrainedCharaRemoveResponse : ResponseCommon
{
    [Key("data")] public TrainedCharaRemoveResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaRemoveResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("update_trained_chara_id_array")] public int[] update_trained_chara_id_array; // 0x10
        [Key("remove_trained_chara_id_array")] public int[] remove_trained_chara_id_array; // 0x18
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x20
        [Key("transfer_event_info")] public TransferEventInfo transfer_event_info; // 0x28
        [Key("transfer_rotation_info")] public TransferRotationInfo transfer_rotation_info; // 0x30
    }
}
