// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainedCharaExtraCmSaveRequest>))]
public class TrainedCharaExtraCmSaveRequest : RequestBase<TrainedCharaExtraCmSaveResponse>
{
    [Key("scenario_id")] public int scenario_id; // 0x88
    [Key("trained_chara_id_array")] public int[] trained_chara_id_array; // 0x90
}
