// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingChallengeGetRankingResponse>))]
public class TrainingChallengeGetRankingResponse : ResponseCommon
{
    [Key("data")] public TrainingChallengeGetRankingResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingChallengeGetRankingResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("ranking_user_list")] public TrainingChallengeRankUser[] ranking_user_list; // 0x10
        [Key("card_ranking_info_list")] public TrainingChallengeCardRankingInfo[] card_ranking_info_list; // 0x18
        [Key("user_card_ranking_info")] public TrainingChallengeCardRankingInfo user_card_ranking_info; // 0x20
    }
}
