// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TransferIndexRequest>))]
public class TransferIndexRequest : RequestBase<TransferIndexResponse>
{
    [Key("load_flag")] public bool load_flag; // 0x88
}
