// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TransferEventDetailInfo>))]
public class TransferEventDetailInfo
{
    [Key("transfer_detail_id")] public int transfer_detail_id; // 0x10
    [Key("exists_trained_chara")] public bool exists_trained_chara; // 0x14
    [Key("remaining_num")] public int remaining_num; // 0x18
}
