// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TransferIndexBothResponse>))]
public class TransferIndexBothResponse : ResponseCommon
{
    [Key("data")] public TransferIndexBothResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TransferIndexBothResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("transfer_event_id")] public int transfer_event_id; // 0x10
        [Key("transfer_event_detail_array")] public TransferEventDetailInfo[] transfer_event_detail_array; // 0x18
        [Key("transfer_rotation_id")] public int transfer_rotation_id; // 0x20
        [Key("transfer_rotation_detail_array")] public TransferEventDetailInfo[] transfer_rotation_detail_array; // 0x28
    }
}
