// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TransferDetailResponse>))]
public class TransferDetailResponse : ResponseCommon
{
    [Key("data")] public TransferDetailResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TransferDetailResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("transfer_event_reward_info")] public TransferEventRewardInfo[] transfer_event_reward_info; // 0x10
        [Key("room_match_entry_chara_id_array")] public int[] room_match_entry_chara_id_array; // 0x18
    }
}
