// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrialCharaLoadResponse>))]
public class TrialCharaLoadResponse : ResponseCommon
{
    [Key("data")] public TrialCharaLoadResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrialCharaLoadResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("trial_chara_array")] public TrainedChara[] trial_chara_array; // 0x10
        [Key("next_update_time")] public string next_update_time; // 0x18
    }
}
