// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TutorialSkipResponse>))]
public class TutorialSkipResponse : ResponseCommon
{
    [Key("data")] public TutorialSkipResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TutorialSkipResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("step")] public int step; // 0x10
    }
}
