// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TutorialSingleModeFinishResponse>))]
public class TutorialSingleModeFinishResponse : ResponseCommon
{
    [Key("data")] public TutorialSingleModeFinishResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TutorialSingleModeFinishResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("trained_chara")] public TrainedChara[] trained_chara; // 0x10
        [Key("directory_card_array")] public DirectoryCard[] directory_card_array; // 0x18
        [Key("directory_ranking")] public int directory_ranking; // 0x20
        [Key("trained_chara_id")] public int trained_chara_id; // 0x24
        [Key("love_point_info")] public LovePointInfo love_point_info; // 0x28
        [Key("reward_item_info")] public RewardSummaryInfo reward_item_info; // 0x30
        [Key("limited_shop_info")] public LimitedShopInfo limited_shop_info; // 0x38
        [Key("update_user_chara_info")] public UserChara update_user_chara_info; // 0x40
        [Key("new_chara_profile_array")] public CharaProfileData[] new_chara_profile_array; // 0x48
    }
}
