// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TutorialTeamEditRequest>))]
public class TutorialTeamEditRequest : RequestBase<TutorialTeamEditResponse>
{
    [Key("team_data_array")] public TeamStadiumTeamData[] team_data_array; // 0x88
    [Key("team_evaluation_point")] public int team_evaluation_point; // 0x90
}
