// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TutorialResponse>))]
public class TutorialResponse : ResponseCommon
{
    [Key("data")] public TutorialResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TutorialResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
