// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TutorialSkipRequest>))]
public class TutorialSkipRequest : RequestBase<TutorialSkipResponse>
{
}
