// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UltimateRaceLoadInfo>))]
public class UltimateRaceLoadInfo
{
    [Key("event_id")] public int event_id; // 0x10
    [Key("archive_event_id_array")] public int[] archive_event_id_array; // 0x18
    [Key("entry_race_contents_id")] public int entry_race_contents_id; // 0x20
    [Key("state")] public int state; // 0x24
    [Key("new_flag")] public bool new_flag; // 0x28
    [Key("resume_trained_chara_id")] public int resume_trained_chara_id; // 0x2C
    [Key("all_clear_flag")] public bool all_clear_flag; // 0x30
}
