// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UltimateRaceClearedHistoryRequest>))]
public class UltimateRaceClearedHistoryRequest : RequestBase<UltimateRaceClearedHistoryResponse>
{
    [Key("event_id")] public int event_id; // 0x88
}
