// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UltimateRaceResumeRequest>))]
public class UltimateRaceResumeRequest : RequestBase<UltimateRaceResumeResponse>
{
}
