// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UpdateForceDisplayStatusResponse>))]
public class UpdateForceDisplayStatusResponse : ResponseCommon
{
    [Key("data")] public UpdateForceDisplayStatusResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<UpdateForceDisplayStatusResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
