// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UpdateSuccessionDeckSetResponse>))]
public class UpdateSuccessionDeckSetResponse : ResponseCommon
{
    [Key("data")] public UpdateSuccessionDeckSetResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<UpdateSuccessionDeckSetResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("succession_deck")] public SuccessionDeck[] succession_deck; // 0x10
    }
}
