// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UpdateForceDisplayStatusRequest>))]
public class UpdateForceDisplayStatusRequest : RequestBase<UpdateForceDisplayStatusResponse>
{
    [Key("event_id")] public int event_id; // 0x88
}
