// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UserSetProfileCardInfoRequest>))]
public class UserSetProfileCardInfoRequest : RequestBase<UserSetProfileCardInfoResponse>
{
    [Key("profile_card_info")] public UserProfileCardInfo profile_card_info; // 0x88
    [Key("image_file")] public string image_file; // 0x90
    [Key("partner_chara_id_array")] public int[] partner_chara_id_array; // 0x98
    [Key("support_card_id_array")] public int[] support_card_id_array; // 0xA0
    [Key("honor_id")] public int honor_id; // 0xA8
}
