// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UserSetBirthDayResponse>))]
public class UserSetBirthDayResponse : ResponseCommon
{
    [Key("data")] public UserSetBirthDayResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<UserSetBirthDayResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("user_info")] public UserInfo user_info; // 0x10
    }
}
