// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UserInfoAtFriend>))]
public class UserInfoAtFriend
{
    [Key("viewer_id")] public long viewer_id; // 0x10
    [Key("name")] public string name; // 0x18
    [Key("honor_data")] public HonorData honor_data; // 0x20
    [Key("last_login_time")] public string last_login_time; // 0x28
    [Key("leader_chara_id")] public int leader_chara_id; // 0x30
    [Key("support_card_id_array")] public int[] support_card_id_array; // 0x38
    [Key("comment")] public string comment; // 0x40
    [Key("fan")] public ulong fan; // 0x48
    [Key("directory_level")] public int directory_level; // 0x50
    [Key("rank_score")] public int rank_score; // 0x54
    [Key("team_stadium_win_count")] public int team_stadium_win_count; // 0x58
    [Key("single_mode_play_count")] public int single_mode_play_count; // 0x5C
    [Key("team_evaluation_point")] public int team_evaluation_point; // 0x60
    [Key("best_team_evaluation_point")] public int best_team_evaluation_point; // 0x64
    [Key("friend_state")] public int friend_state; // 0x68
    [Key("circle_info")] public CircleInfoAtFriend circle_info; // 0x70
    [Key("circle_user")] public CircleUser circle_user; // 0x78
    [Key("user_support_card")] public UserSupportCardAtFriend user_support_card; // 0x80
    [Key("leader_chara_dress_id")] public int leader_chara_dress_id; // 0x88
    [Key("user_trained_chara_array")] public UserTrainedCharaAtFriend[] user_trained_chara_array; // 0x90
    [Key("state")] public int state; // 0x98
}
