// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UserMusic>))]
public class UserMusic
{
    [Key("music_id")] public int music_id; // 0x10
    [Key("acquisition_time")] public string acquisition_time; // 0x18
}
