// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UserSupportCardDeck>))]
public class UserSupportCardDeck
{
    [Key("deck_id")] public int deck_id; // 0x10
    [Key("name")] public string name; // 0x18
    [Key("support_card_id_array")] public int[] support_card_id_array; // 0x20
    [Key("campaign_rental_support_card_id_array")] public int[] campaign_rental_support_card_id_array; // 0x28
    [Key("friend_support_card_info")] public UserFriendSupportCardInDeck friend_support_card_info; // 0x30
}
