// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UserCampaignInfo>))]
public class UserCampaignInfo
{
    [Key("campaign_id")] public int campaign_id; // 0x10
    [Key("end_time")] public string end_time; // 0x18
}
