// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UserFriendSupportCardInDeck>))]
public class UserFriendSupportCardInDeck
{
    [Key("friend_viewer_id")] public long friend_viewer_id; // 0x10
    [Key("friend_support_card_id")] public int friend_support_card_id; // 0x18
    [Key("exp")] public int exp; // 0x1C
    [Key("position")] public int position; // 0x20
}
