// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UserChangeStoryFavoriteResponse>))]
public class UserChangeStoryFavoriteResponse : ResponseCommon
{
    [Key("data")] public UserChangeStoryFavoriteResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<UserChangeStoryFavoriteResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("story_favorite_array")] public StoryFavorite[] story_favorite_array; // 0x10
    }
}
