// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UserChangeSupportCardRequest>))]
public class UserChangeSupportCardRequest : RequestBase<UserChangeSupportCardResponse>
{
    [Key("support_card_id_array")] public int[] support_card_id_array; // 0x88
}
