// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UserCardDress>))]
public class UserCardDress
{
    [Key("card_id")] public int card_id; // 0x10
    [Key("cloth_id")] public int cloth_id; // 0x14
}
