// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UserTrophyInfo>))]
public class UserTrophyInfo
{
    [Key("trophy_id")] public int trophy_id; // 0x10
    [Key("create_time")] public string create_time; // 0x18
    [Key("race_instance_info_array")] public RaceInstanceInfo[] race_instance_info_array; // 0x20
}
