// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ValentineReceivedData>))]
public class ValentineReceivedData
{
    [Key("last_received_time")] public string last_received_time; // 0x10
    [Key("card_id_list")] public int[] card_id_list; // 0x18
    [Key("received_card_id_history")] public int[] received_card_id_history; // 0x20
}
