// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ValentineReceiveHistoryData>))]
public class ValentineReceiveHistoryData
{
    [Key("card_id")] public int card_id; // 0x10
    [Key("received_time")] public string received_time; // 0x18
}
