// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ValentineSpecialReceivedData>))]
public class ValentineSpecialReceivedData
{
    [Key("last_received_time")] public string last_received_time; // 0x10
    [Key("card_id_list")] public int[] card_id_list; // 0x18
    [Key("special_item_unconditional_receive_flag")] public int special_item_unconditional_receive_flag; // 0x20
}
